@startuml
title Pipeline & Domain Services
skinparam classAttributeIconSize 0
hide empty members
hide circle

abstract class BaseDomainPipelineService
class CircuitPipelineService
class ConstructorPipelineService
class ConstructorTableExtractionService
class DomainPipelineService
class DriverPipelineService
class PipelineService
abstract class RunDiagnosticsMixin
class SeasonPipelineService

DomainPipelineService <|-- BaseDomainPipelineService
RunDiagnosticsMixin <|-- DomainPipelineService
BaseDomainPipelineService <|-- CircuitPipelineService
BaseDomainPipelineService <|-- ConstructorPipelineService
RunDiagnosticsMixin <|-- ConstructorTableExtractionService
PipelineService <|-- DomainPipelineService
BaseDomainPipelineService <|-- DriverPipelineService
BaseDomainPipelineService <|-- SeasonPipelineService

@enduml
