@startuml
title Classifier Hierarchy (ClassifierABC)
skinparam classAttributeIconSize 0
hide empty members
hide circle

class CircuitLapRecordsTableClassifier
abstract class ClassifierABC
class DriverResultsSectionTableClassifier
class PassthroughSectionTableClassifier
abstract class SectionTableClassifierABC

SectionTableClassifierABC <|-- CircuitLapRecordsTableClassifier
SectionTableClassifierABC <|-- DriverResultsSectionTableClassifier
SectionTableClassifierABC <|-- PassthroughSectionTableClassifier
ClassifierABC <|-- SectionTableClassifierABC

@enduml
