@startuml

hide circle
hide empty members


abstract class SeasonTableOrchestratorABC
abstract class BaseInfoboxOrchestrator
abstract class InfoboxOrchestratorABC
abstract class ParsedRecordsMixin

class SeasonGenericTableOrchestrator
class SeasonStandingsTableOrchestrator

class CircuitInfoboxOrchestrator
class ConstructorInfoboxOrchestrator
class DriverInfoboxOrchestrator


InfoboxOrchestratorABC <|-- BaseInfoboxOrchestrator
InfoboxOrchestratorABC <|-- CircuitInfoboxOrchestrator

ParsedRecordsMixin <|-- BaseInfoboxOrchestrator
ParsedRecordsMixin <|-- CircuitInfoboxOrchestrator

BaseInfoboxOrchestrator <|-- ConstructorInfoboxOrchestrator
BaseInfoboxOrchestrator <|-- DriverInfoboxOrchestrator
SeasonTableOrchestratorABC <|-- SeasonGenericTableOrchestrator
SeasonTableOrchestratorABC <|-- SeasonStandingsTableOrchestrator

@enduml
