@startuml
title Record Validators
skinparam classAttributeIconSize 0
hide empty members
hide circle

class CircuitsRecordValidator
class CompositeRecordValidator
class DriversRecordValidator
class GrandsPrixRecordValidator
abstract class RecordValidator

RecordValidator <|-- CompositeRecordValidator
CompositeRecordValidator <|-- CircuitsRecordValidator
CompositeRecordValidator <|-- DriversRecordValidator
CompositeRecordValidator <|-- GrandsPrixRecordValidator

@enduml
