@startuml

hide circle
hide empty members

abstract class ApplyForElementsMixin
abstract class ArticleScraperBase
abstract class BackgroundMixin
abstract class BaseColumn
abstract class BaseComponent
abstract class BaseConstructorColumn
abstract class BaseConstructorListScraper
abstract class BaseDriverResultsSectionParser
abstract class BaseEngineTableScraper
abstract class BaseExecutor
abstract class BaseInfoboxOrchestrator
abstract class BaseNormalizer
abstract class BaseOrchestrationFlow
abstract class BaseRecordFactory
abstract class BaseRedFlaggedRacesTableMapper
abstract class BaseSeasonParser
abstract class BaseSectionExtractionService
abstract class ClassifierABC
abstract class CompleteExtractorBase
abstract class DeclarativeSectionTableParseMixin
abstract class EnumMarksMixin
abstract class ExtractListItemsMixin
abstract class F1TableScraper
abstract class FileTtlCacheAdapter
abstract class HeaderNormalizationMixin
abstract class HtmlSoupParserABC
abstract class HtmlTagParserABC
abstract class InfoboxExtractorABC
abstract class InfoboxHtmlFieldParserABC
abstract class InfoboxOrchestratorABC
abstract class InfoboxParserABC
abstract class InfoboxRowsParserABC
abstract class LayerJobRunner
abstract class LayerZeroRunConfigFactory
abstract class MapperABC
abstract class NestedChildParser
abstract class ParsedRecordsMixin
abstract class ParseGroupMixin
abstract class ParserABC
abstract class RecordAssemblyStrategy
abstract class RecordSplitStrategy
abstract class RecordTransformer
abstract class RowMappingMixin
abstract class RunDiagnosticsMixin
abstract class SafeParsingMixin
abstract class SeasonTableOrchestratorABC
abstract class SectionAwareMixin
abstract class SectionByIdScraperBase
abstract class SectionInfoboxesHtmlParserABC
abstract class SectionLevelMixin
abstract class SectionListsHtmlParserABC
abstract class SectionParserBase
abstract class SectionTextBlocksHtmlParserABC
abstract class SourceAdapter
abstract class SplitRule
abstract class SubSectionLevelMixin
abstract class SubSubSectionLevelMixin
abstract class TableCellExtractionMixin
abstract class TableDomainMapperABC
abstract class WikiElementParsingMixin
abstract class WikiFigureElementParserABC
abstract class WikiInfoboxElementParserABC
abstract class WikiScraper
abstract class WikiSectionNodeParserABC
abstract class WikiSectionParserABC
abstract class WikiSubSectionParserABC
abstract class WikiSubSubSectionParserABC

class ActiveYearsParser
class AppendLinksColumn
class ArticleTablesAssembler
class ArticleTablesParser
class AttachDetailsStrategy
class AutoColumn
class BaseRecordAssembler
class BaseRegistryEntry
class BestFinishParser
class BodyContentAssembler
class BoolColumn
class BrListColumn
class BundleRecordWithDetailsStrategy
class ByRaceTitleSubSectionParser
class CacheAdapter
class CalendarCircuitColumn
class CallableInfoboxFieldParser
class CancelledRoundsParser
class CarNumbersParser
class CarRecord
class CarRecordFactory
class CategoryLinksParser
class ChampionshipsParser
class Circuit
class CircuitAdditionalInfoExtractor
class CircuitBaseRecord
class CircuitCompleteRecord
class CircuitDetailsRecord
class CircuitEntitiesOrchestrator
class CircuitEntityExtractor
class CircuitEventsSectionParser
class CircuitEventsTableRecordMapper
class CircuitGeoExtractor
class CircuitHistoryExtractor
class CircuitInfoboxExtractor
class CircuitInfoboxOrchestrator
class CircuitInfoboxParser
class CircuitLapRecordExtractor
class CircuitLapRecordsSectionParser
class CircuitLapRecordsTableClassifier
class CircuitLapRecordsTableRecordMapper
class CircuitLayoutHistorySectionParser
class CircuitLayoutsExtractor
class CircuitNameStatusColumn
class CircuitPipelineService
class CircuitRecordAssembler
class CircuitRecordFactory
class CircuitSectionExtractionService
class CircuitsListScraper
class CircuitsListSectionParser
class CircuitsListTableMapper
class CircuitSpecsExtractor
class CircuitsRecordValidator
class CircuitTextProcessing
class ColinChapmanTrophyParser
class CollapsibleTableParser
class ColourListColumn
class CompleteConstructorsDataExtractor
class CompleteDriverDataExtractor
class CompleteSeasonDataExtractor
class ConfigurableSectionServiceFactory
class ConstructorChampionshipResultsSectionParser
class ConstructorColumn
class ConstructorCompleteF1ResultsSectionParser
class ConstructorHistorySectionParser
class ConstructorInfoboxOrchestrator
class ConstructorNameColumn
class ConstructorPartColumn
class ConstructorPartParser
class ConstructorPipelineService
class ConstructorRecordAssembler
class ConstructorRecordFactory
class ConstructorSectionExtractionService
class ConstructorsListScraper
class ConstructorSplitColumn
class ConstructorsSectionParser
class ConstructorTableExtractionService
class ConstructorTablesSectionParser
class ContentTextParser
class CurrentConstructorsSectionParser
class CurrentConstructorsTableMapper
class CurrentRulesSectionParser
class DateColumn
class DateRangeColumn
class DateValue
class DeduplicateRecordStrategy
class DefaultDriverInfoboxProvider
class DefaultLayerZeroRunConfigFactory
class DefaultRetryPolicy
class DetailByDriverSubSectionParser
class DomainParseError
class DomainPipelineService
class DomainSeedExtractor
class DomainSeedNormalizer
class DomainStageOrchestrator
class DriverColumn
class DriverInfoboxBundle
class DriverInfoboxOrchestrator
class DriverInfoboxParser
class DriverListColumn
class DriverNameStatusColumn
class DriverOrderedTableMapper
class DriverPipelineService
class DriverRecordAssembler
class DriverRecordFactory
class DriverResultsSectionParser
class DriverResultsSectionTableClassifier
class DriverResultsTableRecordMapper
class DriversChampionships
class DriversChampionshipsRecordFactory
class DriversChampionshipsTransformer
class DriversCheckpointFlow
class DriverSectionExtractionService
class DriversListSectionParser
class DriversListTableMapper
class DriversRecordValidator
class DriversSectionParser
class DriversSeedNormalizer
class DriversWithRoundsColumn
class EngineColumn
class EngineConfigurationColumn
class EngineManufacturer
class EngineManufacturerNameStatusColumn
class EngineManufacturerRecordFactory
class EngineManufacturersIndianapolisSubSectionParser
class EngineManufacturersListScraper
class EngineManufacturersSectionParser
class EngineManufacturersTableMapper
class EngineRegulation
class EngineRegulationScraper
class EngineRegulationSubSectionParser
class EngineRegulationTableMapper
class EngineRestriction
class EngineRestrictionsScraper
class EngineRestrictionsTableMapper
class EngineRpmLimitColumn
class EngineSubSectionParser
class EntrantColumn
class EntriesStartsColumn
class EventRecordFactory
class ExtractDetailFieldStrategy
class F1CompleteCircuitDataExtractor
class F1CompleteEngineManufacturerDataExtractor
class F1CompleteGrandPrixDataExtractor
class F1DriversListScraper
class F1FatalitiesListScraper
class F1SingleCircuitScraper
class F1SingleGrandPrixScraper
class F1SponsorshipLiveriesScraper
class F1StandingsScraper
class F1StandingsTableParser
class FailedToMakeRestartTransformer
class FatalitiesCarTransformer
class FatalitiesSectionParser
class FatalitiesTableMapper
class FatalityDateColumn
class FatalityEventColumn
class FatalityRecordFactory
class FemaleDriversListScraper
class FemaleDriversTableMapper
class FigureElementParser
class FileCache
class FinishedSeasonParser
class FirstPlaceColumn
class FormerConstructorsSectionParser
class FormerConstructorsTableMapper
class FuelFlowRateColumn
class FuelInjectionPressureLimitColumn
class FuelLimitPerRaceColumn
class FuncColumn
class FunctionExportRunner
class GeminiJsonFileCacheAdapter
class GenericIndianapolisOnlySubSectionParser
class GrandPrixByYearSectionParser
class GrandPrixRunner
class GrandPrixSplitStrategy
class GrandsPrixListScraper
class GrandsPrixRecordFactory
class GrandsPrixRecordValidator
class GrandsPrixTableMapper
class HasMultipleSeasonsRule
class HasPossessiveColoursRule
class HasYearSpecificColoursRule
class HasYearSpecificSponsorsRule
class HeaderParser
class HistorySectionParser
class HtmlFetcher
class HtmlTableParser
class HttpClient
class HTTPError
class HttpResponseFileCacheAdapter
class HttpShimError
class HTTPTimeoutError
class IdentitySectionTableRecordMapper
class IndianapolisConstructorsListParser
class IndianapolisOnlyListParser
class IndianapolisOnlyListScraper
class InfoboxCareerParser
class InfoboxCellValueExtractor
class InfoboxElementParser
class InfoboxSectionCollector
class InfoboxTableParser
class InfoboxTextUtils
class InfoboxTitlesParser
class JimClarkTrophyParser
class LapRecordsTableScraper
class LapRecordsWikiTableMapper
class LastLengthUsedColumn
class LayerOneExecutor
class LayerZeroExecutor
class LicenceParser
class Link
class LinkRecord
class LinksListColumn
class ListColumn
class ListElementParser
class ListJobRegistryEntry
class ListScraper
class LocationColumn
class MinDelayRateLimiter
class MissingSectionError
class MultiColumn
class NameStatusColumn
class NationalityParser
class NavboxElementParser
class NestedTextColumn
class NestedUnitListColumn
class NonChampionshipRacesTableMapper
class NonChampionshipsRacesSubSectionParser
class NormalizedDate
class NormalizeLinksTransformer
class OfficialDriversSubSectionParser
class ParagraphElementParser
class ParsedValueColumn
class PipelineError
class PipelineService
class PointsColumn
class PointsOrTextColumn
class PointsScoringSystemsHistoryTableMapper
class PointsScoringSystemsHistoryTransformer
class PointsScoringSystemsSectionParser
class PointsScraper
class PointsScraper
class PositionColumn
class PossessiveDriverColourSplitStrategy
class PrivateerTeamsListParser
class PrivateerTeamsSectionParser
class RaceEventParser
class RaceResultColumn
class RaceResultsTableMapper
class RacesSectionParser
class RaceTitleStatusColumn
class RangeColumn
class RecordFactoryTransformer
class RecordValidator
class RecursiveSectionParser
class RedFlaggedRacesBaseScraper
class RedFlaggedRacesScraper
class RedFlaggedRacesSectionParser
class RegexColumn
class RequestError
class RestartStatusColumn
class RoundColumn
class ScraperError
class ScraperNetworkError
class ScraperNotFoundError
class ScraperParseError
class ScraperValidationError
class SeasonCalendarParser
class SeasonCalendarSectionParser
class SeasonConstructorsStandingsSectionParser
class SeasonDateColumn
class SeasonDriversStandingsSectionParser
class SeasonEntriesParser
class SeasonFreePracticeParser
class SeasonGenericTableOrchestrator
class SeasonMidSeasonChangesSectionParser
class SeasonNonChampionshipParser
class SeasonPipelineService
class SeasonRecordAssembler
class SeasonRecordFactory
class SeasonRef
class SeasonRegionalChampionshipParser
class SeasonRegulationChangesSectionParser
class SeasonResultsParser
class SeasonResultsSectionParser
class SeasonsColumn
class SeasonScoringSystemParser
class SeasonsListScraper
class SeasonSplitStrategy
class SeasonsSectionParser
class SeasonsTableMapper
class SeasonsTableParser
class SeasonStandingsParser
class SeasonStandingsTableOrchestrator
class SeasonSummaryRecordFactory
class SeasonTablePayloadMapper
class SeasonTextSectionExtractionService
class SectionAdapter
class SectionAssembler
class SectionElementParser
class SeedListTableScraper
class SeedRegistryEntry
class SeedSectionOrchestrationFlow
class SeriesColumn
class ShortenedRacePointsTransformer
class ShortenedRacesPointsTableMapper
class ShortenedRacesSubSubSectionParser
class SingleConstructorScraper
class SingleDriverScraper
class SingleEngineManufacturerScraper
class SingleSeasonScraper
class SkipColumn
class SoupParser
class SourceAdapterFetcherShim
class SourceParseError
class SpecialCasesSubSectionParser
class SpecialCasesSubSubSectionRouter
class SpecialDriverRecordFactory
class SponsorColumn
class SponsorPartsParser
class SponsorshipLiveriesRunConfigFactory
class SponsorshipSeasonsColumn
class SponsorshipSectionParser
class SprintPointsTableMapper
class SprintRacesSubSubSectionParser
class StandingsTableMapper
class StaticScraperKwargsFactory
class TableElementParser
class TableExtractor
class TableRecordMapper
class TableSectionParser
class TeamLiveriesSectionParser
class TeamsParser
class TestingVenuesParser
class TextColumn
class TimeColumn
class TimeRangeColumn
class TransportError
class TyreColumn
class TyreManufacturersBySeasonSubSectionParser
class TyreManufacturersBySeasonTableMapper
class TyreManufacturersScraper
class UnitColumn
class UnknownValueColumn
class UrlColumn
class ValidatedModel
class ValidationError
class ValueObject
class WikiFigureElementParser
class WikiFigureParser
class WikiInfoboxElementParser
class WikiInfoboxHtmlParser
class WikiNavboxElementParser
class WikiNavboxParser
class WikiParagraphElementParser
class WikiParsedPayloadMapper
class WikipediaCachePolicy
class WikipediaSectionByIdSelectionStrategy
class WikiReferencesElementParser
class WikiReferencesElementParser
class WikiSectionElementParser
class WikiTableBaseMapper
class WikiTableElementParser
class WikiTableHtmlParser
class WikiTableParser
class WorldChampionshipsRacesTableMapper
class YearParser

interface CircuitContract
interface DataContract
interface DriverContract
interface PointsContract
interface TextCacheProtocol

ArticleScraperBase <|-- F1SingleCircuitScraper
ArticleScraperBase <|-- F1SingleGrandPrixScraper
ArticleScraperBase <|-- SectionByIdScraperBase
ArticleScraperBase <|-- SingleConstructorScraper
ArticleScraperBase <|-- SingleDriverScraper
ArticleScraperBase <|-- SingleEngineManufacturerScraper
ArticleScraperBase <|-- SingleSeasonScraper

BackgroundMixin <|-- FatalityEventColumn
BackgroundMixin <|-- NameStatusColumn
BackgroundMixin <|-- RaceResultColumn
BackgroundMixin <|-- RestartStatusColumn
BackgroundMixin <|-- RoundColumn

BaseColumn <|-- AutoColumn
BaseColumn <|-- BaseConstructorColumn
BaseColumn <|-- BoolColumn
BaseColumn <|-- BrListColumn
BaseColumn <|-- CalendarCircuitColumn
BaseColumn <|-- ColourListColumn
BaseColumn <|-- ConstructorNameColumn
BaseColumn <|-- ConstructorPartColumn
BaseColumn <|-- DateColumn
BaseColumn <|-- DateRangeColumn
BaseColumn <|-- DriverColumn
BaseColumn <|-- DriverListColumn
BaseColumn <|-- DriversWithRoundsColumn
BaseColumn <|-- EngineColumn
BaseColumn <|-- EngineConfigurationColumn
BaseColumn <|-- EngineRpmLimitColumn
BaseColumn <|-- EntrantColumn
BaseColumn <|-- EntriesStartsColumn
BaseColumn <|-- FatalityDateColumn
BaseColumn <|-- FatalityEventColumn
BaseColumn <|-- FirstPlaceColumn
BaseColumn <|-- FuelFlowRateColumn
BaseColumn <|-- FuelInjectionPressureLimitColumn
BaseColumn <|-- FuelLimitPerRaceColumn
BaseColumn <|-- FuncColumn
BaseColumn <|-- LinksListColumn
BaseColumn <|-- ListColumn
BaseColumn <|-- MultiColumn
BaseColumn <|-- NestedTextColumn
BaseColumn <|-- NestedUnitListColumn
BaseColumn <|-- ParsedValueColumn
BaseColumn <|-- PointsColumn
BaseColumn <|-- PointsOrTextColumn
BaseColumn <|-- PositionColumn
BaseColumn <|-- RaceResultColumn
BaseColumn <|-- RangeColumn
BaseColumn <|-- RegexColumn
BaseColumn <|-- RestartStatusColumn
BaseColumn <|-- RoundColumn
BaseColumn <|-- SeasonDateColumn
BaseColumn <|-- SeasonsColumn
BaseColumn <|-- SeriesColumn
BaseColumn <|-- SkipColumn
BaseColumn <|-- SponsorColumn
BaseColumn <|-- SponsorshipSeasonsColumn
BaseColumn <|-- TextColumn
BaseColumn <|-- TimeColumn
BaseColumn <|-- TimeRangeColumn
BaseColumn <|-- TyreColumn
BaseColumn <|-- UnitColumn
BaseColumn <|-- UnknownValueColumn
BaseColumn <|-- UrlColumn

BaseComponent <|-- BaseNormalizer
BaseComponent <|-- DomainSeedExtractor
BaseComponent <|-- DomainStageOrchestrator

BaseConstructorColumn <|-- ConstructorColumn
BaseEngineTableScraper <|-- EngineRegulationScraper
BaseEngineTableScraper <|-- EngineRestrictionsScraper

BaseExecutor <|-- LayerOneExecutor
BaseExecutor <|-- LayerZeroExecutor

BaseInfoboxOrchestrator <|-- ConstructorInfoboxOrchestrator
BaseInfoboxOrchestrator <|-- DriverInfoboxOrchestrator

BaseNormalizer <|-- DomainSeedNormalizer
BaseNormalizer <|-- DriversSeedNormalizer

BaseOrchestrationFlow <|-- DriversCheckpointFlow
BaseOrchestrationFlow <|-- SeedSectionOrchestrationFlow

BaseRecordAssembler <|-- CircuitRecordAssembler
BaseRecordAssembler <|-- ConstructorRecordAssembler
BaseRecordAssembler <|-- SeasonRecordAssembler

BaseRecordFactory <|-- CarRecordFactory
BaseRecordFactory <|-- CircuitRecordFactory
BaseRecordFactory <|-- ConstructorRecordFactory
BaseRecordFactory <|-- DriverRecordFactory
BaseRecordFactory <|-- DriversChampionshipsRecordFactory
BaseRecordFactory <|-- EngineManufacturerRecordFactory
BaseRecordFactory <|-- EventRecordFactory
BaseRecordFactory <|-- FatalityRecordFactory
BaseRecordFactory <|-- GrandsPrixRecordFactory
BaseRecordFactory <|-- SeasonRecordFactory
BaseRecordFactory <|-- SeasonSummaryRecordFactory
BaseRecordFactory <|-- SpecialDriverRecordFactory

BaseRedFlaggedRacesTableMapper <|-- NonChampionshipRacesTableMapper
BaseRedFlaggedRacesTableMapper <|-- WorldChampionshipsRacesTableMapper

BaseRegistryEntry <|-- ListJobRegistryEntry
BaseRegistryEntry <|-- SeedRegistryEntry

BaseSeasonParser <|-- CancelledRoundsParser
BaseSeasonParser <|-- ColinChapmanTrophyParser
BaseSeasonParser <|-- JimClarkTrophyParser
BaseSeasonParser <|-- SeasonCalendarParser
BaseSeasonParser <|-- SeasonEntriesParser
BaseSeasonParser <|-- SeasonFreePracticeParser
BaseSeasonParser <|-- SeasonNonChampionshipParser
BaseSeasonParser <|-- SeasonRegionalChampionshipParser
BaseSeasonParser <|-- SeasonResultsParser
BaseSeasonParser <|-- SeasonScoringSystemParser
BaseSeasonParser <|-- TestingVenuesParser

BaseSectionExtractionService <|-- CircuitSectionExtractionService
BaseSectionExtractionService <|-- ConstructorSectionExtractionService
BaseSectionExtractionService <|-- DriverSectionExtractionService
BaseSectionExtractionService <|-- SeasonTextSectionExtractionService

CircuitBaseRecord <|-- CircuitCompleteRecord
CircuitBaseRecord <|-- CircuitDetailsRecord

CircuitEntityExtractor <|-- CircuitAdditionalInfoExtractor

CircuitTextProcessing <|-- CircuitEntityExtractor
CircuitTextProcessing <|-- CircuitLapRecordExtractor

ClassifierABC <|-- CircuitLapRecordsTableClassifier
ClassifierABC <|-- DriverResultsSectionTableClassifier

CompleteExtractorBase <|-- CompleteConstructorsDataExtractor
CompleteExtractorBase <|-- CompleteDriverDataExtractor
CompleteExtractorBase <|-- CompleteSeasonDataExtractor
CompleteExtractorBase <|-- F1CompleteCircuitDataExtractor
CompleteExtractorBase <|-- F1CompleteEngineManufacturerDataExtractor
CompleteExtractorBase <|-- F1CompleteGrandPrixDataExtractor

ConstructorPartParser <|-- ConstructorPartColumn

ConstructorsSectionParser <|-- CurrentConstructorsSectionParser
ConstructorsSectionParser <|-- FormerConstructorsSectionParser

ConstructorTablesSectionParser <|-- ConstructorChampionshipResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorCompleteF1ResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorHistorySectionParser

DataContract <|-- CircuitContract
DataContract <|-- DriverContract
DataContract <|-- PointsContract

DeclarativeSectionTableParseMixin <|-- BaseConstructorListScraper
DeclarativeSectionTableParseMixin <|-- BaseConstructorListScraper
DeclarativeSectionTableParseMixin <|-- CircuitsListScraper

DomainPipelineService <|-- CircuitPipelineService
DomainPipelineService <|-- ConstructorPipelineService
DomainPipelineService <|-- DriverPipelineService
DomainPipelineService <|-- SeasonPipelineService

DriverOrderedTableMapper <|-- DriversListTableMapper
DriverOrderedTableMapper <|-- FatalitiesTableMapper

EnumMarksMixin <|-- FatalityDateColumn
EnumMarksMixin <|-- FatalityEventColumn
EnumMarksMixin <|-- NameStatusColumn

ExtractListItemsMixin <|-- SeasonMidSeasonChangesSectionParser
ExtractListItemsMixin <|-- SeasonRegulationChangesSectionParser

F1TableScraper <|-- BaseEngineTableScraper
F1TableScraper <|-- EngineManufacturersListScraper
F1TableScraper <|-- F1FatalitiesListScraper
F1TableScraper <|-- F1StandingsScraper
F1TableScraper <|-- FemaleDriversListScraper
F1TableScraper <|-- LapRecordsTableScraper
F1TableScraper <|-- PointsScraper
F1TableScraper <|-- RedFlaggedRacesBaseScraper
F1TableScraper <|-- SeedListTableScraper
F1TableScraper <|-- TyreManufacturersScraper

FileTtlCacheAdapter <|-- GeminiJsonFileCacheAdapter
FileTtlCacheAdapter <|-- HttpResponseFileCacheAdapter

FuncColumn <|-- LocationColumn

HeaderNormalizationMixin <|-- WikiTableHtmlParser

HtmlFetcher <|-- SourceAdapterFetcherShim

HtmlSoupParserABC <|-- ArticleTablesParser
HtmlSoupParserABC <|-- HtmlTableParser
HtmlSoupParserABC <|-- SeasonStandingsParser
HtmlSoupParserABC <|-- SectionElementParser
HtmlSoupParserABC <|-- SectionInfoboxesHtmlParserABC
HtmlSoupParserABC <|-- SectionListsHtmlParserABC
HtmlSoupParserABC <|-- SectionTextBlocksHtmlParserABC
HtmlSoupParserABC <|-- SponsorshipSectionParser
HtmlSoupParserABC <|-- TeamLiveriesSectionParser
HtmlSoupParserABC <|-- WikiSectionElementParser

HtmlTagParserABC <|-- F1StandingsTableParser
HtmlTagParserABC <|-- InfoboxCellValueExtractor
HtmlTagParserABC <|-- InfoboxParserABC
HtmlTagParserABC <|-- ListElementParser
HtmlTagParserABC <|-- NavboxElementParser
HtmlTagParserABC <|-- PrivateerTeamsListParser
HtmlTagParserABC <|-- TableElementParser
HtmlTagParserABC <|-- WikiNavboxElementParser
HtmlTagParserABC <|-- WikiNavboxParser
HtmlTagParserABC <|-- WikiParagraphElementParser
HtmlTagParserABC <|-- WikiReferencesElementParser
HtmlTagParserABC <|-- WikiReferencesElementParser
HtmlTagParserABC <|-- WikiTableElementParser
HtmlTagParserABC <|-- WikiTableHtmlParser

HttpShimError <|-- HTTPError
HttpShimError <|-- HTTPTimeoutError

InfoboxExtractorABC <|-- CircuitInfoboxExtractor

InfoboxHtmlFieldParserABC <|-- ActiveYearsParser
InfoboxHtmlFieldParserABC <|-- BestFinishParser
InfoboxHtmlFieldParserABC <|-- CallableInfoboxFieldParser
InfoboxHtmlFieldParserABC <|-- CarNumbersParser
InfoboxHtmlFieldParserABC <|-- ChampionshipsParser
InfoboxHtmlFieldParserABC <|-- FinishedSeasonParser
InfoboxHtmlFieldParserABC <|-- LicenceParser
InfoboxHtmlFieldParserABC <|-- NationalityParser
InfoboxHtmlFieldParserABC <|-- RaceEventParser
InfoboxHtmlFieldParserABC <|-- TeamsParser

InfoboxOrchestratorABC <|-- BaseInfoboxOrchestrator
InfoboxOrchestratorABC <|-- CircuitInfoboxOrchestrator

InfoboxRowsParserABC <|-- InfoboxCareerParser
InfoboxRowsParserABC <|-- InfoboxTitlesParser

InfoboxTextUtils <|-- CircuitGeoExtractor
InfoboxTextUtils <|-- CircuitHistoryExtractor
InfoboxTextUtils <|-- CircuitSpecsExtractor
InfoboxTextUtils <|-- CircuitTextProcessing

LayerJobRunner <|-- FunctionExportRunner
LayerJobRunner <|-- GrandPrixRunner

LayerZeroRunConfigFactory <|-- DefaultLayerZeroRunConfigFactory
LayerZeroRunConfigFactory <|-- SponsorshipLiveriesRunConfigFactory
LayerZeroRunConfigFactory <|-- StaticScraperKwargsFactory

LinkRecord <|-- CarRecord

LinksListColumn <|-- AppendLinksColumn

ListScraper <|-- ConstructorsListScraper
ListScraper <|-- IndianapolisOnlyListScraper

MapperABC <|-- CircuitEventsTableRecordMapper
MapperABC <|-- CircuitLapRecordsTableRecordMapper
MapperABC <|-- DriverResultsTableRecordMapper
MapperABC <|-- IdentitySectionTableRecordMapper
MapperABC <|-- ShortenedRacesPointsTableMapper
MapperABC <|-- TableDomainMapperABC
MapperABC <|-- WikiParsedPayloadMapper
MapperABC <|-- WikiTableBaseMapper

MultiColumn <|-- ConstructorSplitColumn
MultiColumn <|-- LastLengthUsedColumn
MultiColumn <|-- NameStatusColumn

NameStatusColumn <|-- CircuitNameStatusColumn
NameStatusColumn <|-- DriverNameStatusColumn
NameStatusColumn <|-- EngineManufacturerNameStatusColumn
NameStatusColumn <|-- RaceTitleStatusColumn

ParsedRecordsMixin <|-- BaseInfoboxOrchestrator
ParsedRecordsMixin <|-- CircuitInfoboxOrchestrator

ParseGroupMixin <|-- TableRecordMapper
ParseGroupMixin <|-- WikiTableBaseMapper

ParserABC <|-- CollapsibleTableParser
ParserABC <|-- ContentTextParser
ParserABC <|-- HeaderParser
ParserABC <|-- HtmlSoupParserABC
ParserABC <|-- HtmlTagParserABC
ParserABC <|-- InfoboxTableParser
ParserABC <|-- SoupParser
ParserABC <|-- SponsorPartsParser
ParserABC <|-- YearParser

PipelineError <|-- SourceParseError
PipelineError <|-- TransportError
PipelineError <|-- ValidationError

PipelineService <|-- DomainPipelineService

RecordAssemblyStrategy <|-- AttachDetailsStrategy
RecordAssemblyStrategy <|-- BundleRecordWithDetailsStrategy
RecordAssemblyStrategy <|-- ExtractDetailFieldStrategy

RecordSplitStrategy <|-- DeduplicateRecordStrategy
RecordSplitStrategy <|-- GrandPrixSplitStrategy
RecordSplitStrategy <|-- PossessiveDriverColourSplitStrategy
RecordSplitStrategy <|-- SeasonSplitStrategy

RecordTransformer <|-- DriversChampionshipsTransformer
RecordTransformer <|-- FailedToMakeRestartTransformer
RecordTransformer <|-- FatalitiesCarTransformer
RecordTransformer <|-- NormalizeLinksTransformer
RecordTransformer <|-- PointsScoringSystemsHistoryTransformer
RecordTransformer <|-- RecordFactoryTransformer
RecordTransformer <|-- ShortenedRacePointsTransformer

RecordValidator <|-- CircuitsRecordValidator
RecordValidator <|-- DriversRecordValidator
RecordValidator <|-- GrandsPrixRecordValidator

RecursiveSectionParser <|-- ByRaceTitleSubSectionParser
RecursiveSectionParser <|-- CurrentRulesSectionParser
RecursiveSectionParser <|-- DetailByDriverSubSectionParser
RecursiveSectionParser <|-- DriversListSectionParser
RecursiveSectionParser <|-- DriversSectionParser
RecursiveSectionParser <|-- EngineManufacturersIndianapolisSubSectionParser
RecursiveSectionParser <|-- EngineManufacturersSectionParser
RecursiveSectionParser <|-- EngineRegulationSubSectionParser
RecursiveSectionParser <|-- EngineSubSectionParser
RecursiveSectionParser <|-- FatalitiesSectionParser
RecursiveSectionParser <|-- GenericIndianapolisOnlySubSectionParser
RecursiveSectionParser <|-- HistorySectionParser
RecursiveSectionParser <|-- ManufacturersSectionParser
RecursiveSectionParser <|-- NonChampionshipsRacesSubSectionParser
RecursiveSectionParser <|-- OfficialDriversSubSectionParser
RecursiveSectionParser <|-- PointsScoringSystemsSectionParser
RecursiveSectionParser <|-- PrivateerTeamsSectionParser
RecursiveSectionParser <|-- RacesSectionParser
RecursiveSectionParser <|-- RedFlaggedRacesSectionParser
RecursiveSectionParser <|-- SeasonsSectionParser
RecursiveSectionParser <|-- ShortenedRacesSubSubSectionParser
RecursiveSectionParser <|-- SpecialCasesSubSectionParser
RecursiveSectionParser <|-- SpecialCasesSubSubSectionRouter
RecursiveSectionParser <|-- SprintRacesSubSubSectionParser
RecursiveSectionParser <|-- TyreManufacturersBySeasonSubSectionParser

RequestError <|-- HttpShimError

RowMappingMixin <|-- TableRecordMapper
RowMappingMixin <|-- WikiTableBaseMapper

RunDiagnosticsMixin <|-- ConstructorTableExtractionService
RunDiagnosticsMixin <|-- DomainPipelineService

SafeParsingMixin <|-- CircuitEntitiesOrchestrator
SafeParsingMixin <|-- CircuitLayoutsExtractor

ScraperError <|-- DomainParseError
ScraperError <|-- PipelineError
ScraperError <|-- ScraperNetworkError
ScraperError <|-- ScraperNotFoundError
ScraperError <|-- ScraperParseError
ScraperError <|-- ScraperValidationError

SeasonTableOrchestratorABC <|-- SeasonGenericTableOrchestrator
SeasonTableOrchestratorABC <|-- SeasonStandingsTableOrchestrator

SectionAdapter <|-- F1SingleCircuitScraper
SectionAdapter <|-- SingleConstructorScraper
SectionAdapter <|-- SingleDriverScraper
SectionAdapter <|-- SingleSeasonScraper

SectionAwareMixin <|-- F1SingleCircuitScraper
SectionAwareMixin <|-- SectionByIdScraperBase
SectionAwareMixin <|-- SingleConstructorScraper
SectionAwareMixin <|-- SingleDriverScraper
SectionAwareMixin <|-- SingleSeasonScraper

SectionLevelMixin <|-- SubSectionLevelMixin
SectionLevelMixin <|-- WikiSectionParserABC

SectionParserBase <|-- BaseDriverResultsSectionParser
SectionParserBase <|-- CircuitLayoutHistorySectionParser
SectionParserBase <|-- CircuitsListSectionParser
SectionParserBase <|-- ConstructorsSectionParser
SectionParserBase <|-- ConstructorTablesSectionParser
SectionParserBase <|-- GrandPrixByYearSectionParser
SectionParserBase <|-- SeasonCalendarSectionParser
SectionParserBase <|-- SeasonConstructorsStandingsSectionParser
SectionParserBase <|-- SeasonDriversStandingsSectionParser
SectionParserBase <|-- SeasonMidSeasonChangesSectionParser
SectionParserBase <|-- SeasonRegulationChangesSectionParser
SectionParserBase <|-- SeasonResultsSectionParser
SectionParserBase <|-- TableSectionParser

SeedListTableScraper <|-- BaseConstructorListScraper
SeedListTableScraper <|-- CircuitsListScraper
SeedListTableScraper <|-- F1DriversListScraper
SeedListTableScraper <|-- GrandsPrixListScraper
SeedListTableScraper <|-- SeasonsListScraper

SourceAdapter <|-- CacheAdapter
SourceAdapter <|-- HtmlFetcher

SplitRule <|-- HasMultipleSeasonsRule
SplitRule <|-- HasPossessiveColoursRule
SplitRule <|-- HasYearSpecificColoursRule
SplitRule <|-- HasYearSpecificSponsorsRule

SubSectionLevelMixin <|-- SubSubSectionLevelMixin
SubSectionLevelMixin <|-- WikiSubSectionParserABC

SubSubSectionLevelMixin <|-- WikiSubSubSectionParserABC

TableCellExtractionMixin <|-- WikiTableHtmlParser

TableDomainMapperABC <|-- WikiTableBaseMapper

TableSectionParser <|-- CircuitEventsSectionParser
TableSectionParser <|-- CircuitLapRecordsSectionParser
TableSectionParser <|-- DriverResultsSectionParser

TextCacheProtocol <|-- FileCache
TextCacheProtocol <|-- WikipediaCachePolicy

ValidatedModel <|-- Circuit
ValidatedModel <|-- EngineManufacturer
ValidatedModel <|-- EngineRegulation
ValidatedModel <|-- EngineRestriction

ValueObject <|-- DateValue
ValueObject <|-- DriversChampionships
ValueObject <|-- Link
ValueObject <|-- NormalizedDate
ValueObject <|-- SeasonRef

WikiElementParsingMixin <|-- RecursiveSectionParser
WikiElementParsingMixin <|-- WikiScraper

WikiFigureElementParserABC <|-- FigureElementParser
WikiFigureElementParserABC <|-- WikiFigureElementParser
WikiFigureElementParserABC <|-- WikiFigureParser

WikiInfoboxElementParserABC <|-- CircuitInfoboxParser
WikiInfoboxElementParserABC <|-- DriverInfoboxParser
WikiInfoboxElementParserABC <|-- InfoboxElementParser
WikiInfoboxElementParserABC <|-- WikiInfoboxElementParser
WikiInfoboxElementParserABC <|-- WikiInfoboxHtmlParser

WikiScraper <|-- ArticleScraperBase
WikiScraper <|-- F1SponsorshipLiveriesScraper
WikiScraper <|-- F1TableScraper
WikiScraper <|-- ListScraper
WikiScraper <|-- RedFlaggedRacesScraper

WikiSectionNodeParserABC <|-- WikiSectionParserABC
WikiSectionNodeParserABC <|-- WikiSubSectionParserABC
WikiSectionNodeParserABC <|-- WikiSubSubSectionParserABC

WikiTableBaseMapper <|-- BaseRedFlaggedRacesTableMapper
WikiTableBaseMapper <|-- CircuitsListTableMapper
WikiTableBaseMapper <|-- CurrentConstructorsTableMapper
WikiTableBaseMapper <|-- DriverOrderedTableMapper
WikiTableBaseMapper <|-- EngineManufacturersTableMapper
WikiTableBaseMapper <|-- EngineRegulationTableMapper
WikiTableBaseMapper <|-- EngineRestrictionsTableMapper
WikiTableBaseMapper <|-- FemaleDriversTableMapper
WikiTableBaseMapper <|-- FormerConstructorsTableMapper
WikiTableBaseMapper <|-- GrandsPrixTableMapper
WikiTableBaseMapper <|-- LapRecordsWikiTableMapper
WikiTableBaseMapper <|-- PointsScoringSystemsHistoryTableMapper
WikiTableBaseMapper <|-- RaceResultsTableMapper
WikiTableBaseMapper <|-- SeasonsTableMapper
WikiTableBaseMapper <|-- SprintPointsTableMapper
WikiTableBaseMapper <|-- StandingsTableMapper
WikiTableBaseMapper <|-- TyreManufacturersBySeasonTableMapper

WikiTableHtmlParser <|-- SeasonsTableParser
WikiTableHtmlParser <|-- WikiTableParser

@enduml
