@startuml

hide circle
hide empty members


class ScraperError
class DomainParseError
class PipelineError
class ScraperNetworkError
class ScraperNotFoundError
class ScraperParseError
class ScraperValidationError
class SourceParseError
class TransportError
class ValidationError


ScraperError <|-- DomainParseError
ScraperError <|-- PipelineError
ScraperError <|-- ScraperNetworkError
ScraperError <|-- ScraperNotFoundError
ScraperError <|-- ScraperParseError
ScraperError <|-- ScraperValidationError

PipelineError <|-- SourceParseError
PipelineError <|-- TransportError
PipelineError <|-- ValidationError

@enduml
