@startuml

hide circle
hide empty members

class CircuitTextProcessing
class CircuitEntityExtractor
class InfoboxTextUtils
class CircuitGeoExtractor
class CircuitHistoryExtractor
class CircuitSpecsExtractor
class CircuitLapRecordExtractor
class CircuitAdditionalInfoExtractor


InfoboxTextUtils <|-- CircuitGeoExtractor
InfoboxTextUtils <|-- CircuitHistoryExtractor
InfoboxTextUtils <|-- CircuitSpecsExtractor
InfoboxTextUtils <|-- CircuitTextProcessing

CircuitTextProcessing <|-- CircuitEntityExtractor
CircuitTextProcessing <|-- CircuitLapRecordExtractor

CircuitEntityExtractor <|-- CircuitAdditionalInfoExtractor

@enduml
