@startuml

hide circle
hide empty members


abstract class BaseSectionExtractionService

class CircuitSectionExtractionService
class ConstructorSectionExtractionService
class DriverSectionExtractionService
class SeasonTextSectionExtractionService


BaseSectionExtractionService <|-- CircuitSectionExtractionService
BaseSectionExtractionService <|-- ConstructorSectionExtractionService
BaseSectionExtractionService <|-- DriverSectionExtractionService
BaseSectionExtractionService <|-- SeasonTextSectionExtractionService

@enduml
