@startuml

hide circle
hide empty members


abstract class RecordSplitStrategy

class DeduplicateRecordStrategy
class GrandPrixSplitStrategy
class PossessiveDriverColourSplitStrategy
class SeasonSplitStrategy


RecordSplitStrategy <|-- DeduplicateRecordStrategy
RecordSplitStrategy <|-- GrandPrixSplitStrategy
RecordSplitStrategy <|-- PossessiveDriverColourSplitStrategy
RecordSplitStrategy <|-- SeasonSplitStrategy

@enduml
