@startuml

hide circle
hide empty members

abstract class BaseComponent
abstract class BaseNormalizer

class DomainSeedExtractor
class DomainStageOrchestrator
class DomainSeedNormalizer
class DriversSeedNormalizer


BaseComponent <|-- BaseNormalizer
BaseComponent <|-- DomainSeedExtractor
BaseComponent <|-- DomainStageOrchestrator

BaseNormalizer <|-- DomainSeedNormalizer
BaseNormalizer <|-- DriversSeedNormalizer

@enduml
