@startuml

hide circle
hide empty members

abstract class WikiFigureElementParserABC

class FigureElementParser
class WikiFigureElementParser
class WikiFigureParser


WikiFigureElementParserABC <|-- FigureElementParser
WikiFigureElementParserABC <|-- WikiFigureElementParser
WikiFigureElementParserABC <|-- WikiFigureParser

@enduml
