@startuml

hide circle
hide empty members


abstract class BaseInfoboxOrchestrator
abstract class InfoboxOrchestratorABC
abstract class ParsedRecordsMixin

class CircuitInfoboxOrchestrator
class ConstructorInfoboxOrchestrator
class DriverInfoboxOrchestrator


InfoboxOrchestratorABC <|-- BaseInfoboxOrchestrator
InfoboxOrchestratorABC <|-- CircuitInfoboxOrchestrator

ParsedRecordsMixin <|-- BaseInfoboxOrchestrator
ParsedRecordsMixin <|-- CircuitInfoboxOrchestrator

BaseInfoboxOrchestrator <|-- ConstructorInfoboxOrchestrator
BaseInfoboxOrchestrator <|-- DriverInfoboxOrchestrator


@enduml
