@startuml
title Column Hierarchy (BaseColumn)
skinparam classAttributeIconSize 0
hide empty members
hide circle

class AppendLinksColumn
class AutoColumn
abstract class BackgroundMixin
abstract class BaseColumn
abstract class BaseConstructorColumn
class BoolColumn
class BrListColumn
class CalendarCircuitColumn
class CircuitNameStatusColumn
class ColourListColumn
class ConstructorColumn
class ConstructorNameColumn
class ConstructorPartColumn
class ConstructorPartParser
class ConstructorSplitColumn
class DateColumn
class DateRangeColumn
class DriverColumn
class DriverListColumn
class DriverNameStatusColumn
class DriversWithRoundsColumn
class EngineColumn
class EngineConfigurationColumn
class EngineManufacturerNameStatusColumn
class EngineRpmLimitColumn
class EntrantColumn
class EntriesStartsColumn
abstract class EnumMarksMixin
class FatalityDateColumn
class FatalityEventColumn
class FirstPlaceColumn
class FuelFlowRateColumn
class FuelInjectionPressureLimitColumn
class FuelLimitPerRaceColumn
class FuncColumn
class LastLengthUsedColumn
class LinksListColumn
class ListColumn
class LocationColumn
class MultiColumn
class NameStatusColumn
class NestedTextColumn
class NestedUnitListColumn
class ParsedValueColumn
class PointsColumn
class PointsOrTextColumn
class PositionColumn
class RaceResultColumn
class RaceTitleStatusColumn
class RangeColumn
class RegexColumn
class RestartStatusColumn
class RoundColumn
class SeasonDateColumn
class SeasonsColumn
class SeriesColumn
class SkipColumn
class SponsorColumn
class SponsorshipSeasonsColumn
class TextColumn
class TimeColumn
class TimeRangeColumn
class TyreColumn
class UnitColumn
class UnknownValueColumn
class UrlColumn

LinksListColumn <|-- AppendLinksColumn
BaseColumn <|-- AutoColumn
BaseColumn <|-- BaseConstructorColumn
BaseColumn <|-- BoolColumn
BaseColumn <|-- BrListColumn
BaseColumn <|-- CalendarCircuitColumn
NameStatusColumn <|-- CircuitNameStatusColumn
BaseColumn <|-- ColourListColumn
BaseConstructorColumn <|-- ConstructorColumn
BaseColumn <|-- ConstructorNameColumn
BaseColumn <|-- ConstructorPartColumn
ConstructorPartParser <|-- ConstructorPartColumn
MultiColumn <|-- ConstructorSplitColumn
BaseColumn <|-- DateColumn
BaseColumn <|-- DateRangeColumn
BaseColumn <|-- DriverColumn
BaseColumn <|-- DriverListColumn
NameStatusColumn <|-- DriverNameStatusColumn
BaseColumn <|-- DriversWithRoundsColumn
BaseColumn <|-- EngineColumn
BaseColumn <|-- EngineConfigurationColumn
NameStatusColumn <|-- EngineManufacturerNameStatusColumn
BaseColumn <|-- EngineRpmLimitColumn
BaseColumn <|-- EntrantColumn
BaseColumn <|-- EntriesStartsColumn
BaseColumn <|-- FatalityDateColumn
EnumMarksMixin <|-- FatalityDateColumn
BackgroundMixin <|-- FatalityEventColumn
BaseColumn <|-- FatalityEventColumn
EnumMarksMixin <|-- FatalityEventColumn
BaseColumn <|-- FirstPlaceColumn
BaseColumn <|-- FuelFlowRateColumn
BaseColumn <|-- FuelInjectionPressureLimitColumn
BaseColumn <|-- FuelLimitPerRaceColumn
BaseColumn <|-- FuncColumn
MultiColumn <|-- LastLengthUsedColumn
BaseColumn <|-- LinksListColumn
BaseColumn <|-- ListColumn
FuncColumn <|-- LocationColumn
BaseColumn <|-- MultiColumn
BackgroundMixin <|-- NameStatusColumn
EnumMarksMixin <|-- NameStatusColumn
MultiColumn <|-- NameStatusColumn
BaseColumn <|-- NestedTextColumn
BaseColumn <|-- NestedUnitListColumn
BaseColumn <|-- ParsedValueColumn
BaseColumn <|-- PointsColumn
BaseColumn <|-- PointsOrTextColumn
BaseColumn <|-- PositionColumn
BackgroundMixin <|-- RaceResultColumn
BaseColumn <|-- RaceResultColumn
NameStatusColumn <|-- RaceTitleStatusColumn
BaseColumn <|-- RangeColumn
BaseColumn <|-- RegexColumn
BackgroundMixin <|-- RestartStatusColumn
BaseColumn <|-- RestartStatusColumn
BackgroundMixin <|-- RoundColumn
BaseColumn <|-- RoundColumn
BaseColumn <|-- SeasonDateColumn
BaseColumn <|-- SeasonsColumn
BaseColumn <|-- SeriesColumn
BaseColumn <|-- SkipColumn
BaseColumn <|-- SponsorColumn
BaseColumn <|-- SponsorshipSeasonsColumn
BaseColumn <|-- TextColumn
BaseColumn <|-- TimeColumn
BaseColumn <|-- TimeRangeColumn
BaseColumn <|-- TyreColumn
BaseColumn <|-- UnitColumn
BaseColumn <|-- UnknownValueColumn
BaseColumn <|-- UrlColumn

@enduml
