HISTORICAL_POSITIONS = [
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
    "9th",
    "10th",
]

SPRINT_POSITIONS = [
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
]

SEASONS_HEADER = "Seasons"
RACE_LENGTH_COMPLETED_HEADER = "Race length completed"  # Kryterium skróconego wyścigu.
FASTEST_LAP_HEADER = "Fastest lap"
DRIVERS_CHAMPIONSHIP_HEADER = "Drivers' Championship"
CONSTRUCTORS_CHAMPIONSHIP_HEADER = "Constructors' Championship"
NOTES_HEADER = "Notes"

SHORTENED_RACE_EXPECTED_HEADERS = [
    SEASONS_HEADER,
    RACE_LENGTH_COMPLETED_HEADER,
    *HISTORICAL_POSITIONS,
    FASTEST_LAP_HEADER,
    NOTES_HEADER,
]

SPRINT_QUALIFYING_EXPECTED_HEADERS = [
    SEASONS_HEADER,
    *SPRINT_POSITIONS,
]

POINTS_SCORING_HISTORY_EXPECTED_HEADERS = [
    SEASONS_HEADER,
    *HISTORICAL_POSITIONS,
    FASTEST_LAP_HEADER,
    DRIVERS_CHAMPIONSHIP_HEADER,
    CONSTRUCTORS_CHAMPIONSHIP_HEADER,
    NOTES_HEADER,
]
