import re

from scrapers.base.constants.shared_headers import SHARED_SEASONS_HEADER

POINTS_SEASONS_HEADER = SHARED_SEASONS_HEADER
POINTS_RACE_LENGTH_COMPLETED_HEADER = (
    "Race length completed"  # Kryterium skróconego wyścigu.
)
POINTS_FASTEST_LAP_HEADER = "Fastest lap"
POINTS_DRIVERS_CHAMPIONSHIP_HEADER = "Towards WDC"
POINTS_CONSTRUCTORS_CHAMPIONSHIP_HEADER = "Towards WCC"
POINTS_NOTES_HEADER = "Notes"


ROLE_PATTERN = re.compile(r"\(\s*([dc])\s*\)", re.IGNORECASE)


HISTORICAL_POSITIONS = [
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
    "9th",
    "10th",
]

SPRINT_POSITIONS = [
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
]

SHORTENED_RACE_EXPECTED_HEADERS = [
    POINTS_SEASONS_HEADER,
    POINTS_RACE_LENGTH_COMPLETED_HEADER,
    *HISTORICAL_POSITIONS,
    POINTS_FASTEST_LAP_HEADER,
    POINTS_NOTES_HEADER,
]

SPRINT_QUALIFYING_EXPECTED_HEADERS = [
    POINTS_SEASONS_HEADER,
    *SPRINT_POSITIONS,
]

POINTS_SCORING_HISTORY_EXPECTED_HEADERS = [
    POINTS_SEASONS_HEADER,
    *HISTORICAL_POSITIONS,
    POINTS_FASTEST_LAP_HEADER,
    POINTS_DRIVERS_CHAMPIONSHIP_HEADER,
    POINTS_CONSTRUCTORS_CHAMPIONSHIP_HEADER,
    POINTS_NOTES_HEADER,
]
