@startuml

hide circle
hide empty members


abstract class AssemblerABC

class BaseRecordAssembler
class CircuitRecordAssembler
class ConstructorRecordAssembler
class SeasonRecordAssembler

class SectionAssembler
class DriverRecordAssembler
class ArticleTablesAssembler


AssemblerABC <|-- BaseRecordAssembler
AssemblerABC <|-- SectionAssembler
AssemblerABC <|-- ArticleTablesAssembler

BaseRecordAssembler <|-- CircuitRecordAssembler
BaseRecordAssembler <|-- ConstructorRecordAssembler
BaseRecordAssembler <|-- SeasonRecordAssembler
BaseRecordAssembler <|-- DriverRecordAssembler

@enduml
