@startuml

hide circle
hide empty members

abstract class InfoboxExtractorABC
abstract class SeasonTableOrchestratorABC
abstract class BaseComponent

abstract class BaseInfoboxOrchestrator
abstract class BaseNormalizer

abstract class SafeParsingMixin


class InfoboxTextUtils

class CircuitTextProcessing

class CircuitEntityExtractor

class CircuitInfoboxExtractor
class TableExtractor
class SeasonGenericTableOrchestrator
class SeasonStandingsTableOrchestrator
class CircuitInfoboxOrchestrator
class ConstructorInfoboxOrchestrator
class DriverInfoboxOrchestrator
class DomainSeedExtractor
class DomainStageOrchestrator
class DomainSeedNormalizer
class DriversSeedNormalizer
class CircuitGeoExtractor
class CircuitHistoryExtractor
class CircuitSpecsExtractor
class CircuitLapRecordExtractor
class CircuitAdditionalInfoExtractor
class CircuitEntitiesOrchestrator
class CircuitLayoutsExtractor


InfoboxTextUtils <|-- CircuitGeoExtractor
InfoboxTextUtils <|-- CircuitHistoryExtractor
InfoboxTextUtils <|-- CircuitSpecsExtractor
InfoboxTextUtils <|-- CircuitTextProcessing

BaseComponent <|-- BaseNormalizer
BaseComponent <|-- DomainSeedExtractor
BaseComponent <|-- DomainStageOrchestrator

SeasonTableOrchestratorABC <|-- SeasonGenericTableOrchestrator
SeasonTableOrchestratorABC <|-- SeasonStandingsTableOrchestrator

InfoboxExtractorABC <|-- CircuitInfoboxExtractor


CircuitTextProcessing <|-- CircuitEntityExtractor
CircuitTextProcessing <|-- CircuitLapRecordExtractor

BaseNormalizer <|-- DomainSeedNormalizer
BaseNormalizer <|-- DriversSeedNormalizer

BaseInfoboxOrchestrator <|-- ConstructorInfoboxOrchestrator
BaseInfoboxOrchestrator <|-- DriverInfoboxOrchestrator
BaseInfoboxOrchestrator <|-- CircuitInfoboxOrchestrator


CircuitEntityExtractor <|-- CircuitAdditionalInfoExtractor


SafeParsingMixin <|-- CircuitEntitiesOrchestrator
SafeParsingMixin <|-- CircuitLayoutsExtractor

@enduml
