@startuml

hide circle
hide empty members


class DomainModel
class CircuitContract
class DriverContract
class PointsContract
class Circuit
class EngineManufacturer
class EngineRegulation
class EngineRestriction
class DateValue
class DriversChampionships
class Link
class NormalizedDate
class SeasonRef
class CircuitBaseRecord
class CircuitCompleteRecord
class CircuitDetailsRecord
class LinkRecord
class CarRecord
class DriverRecordModel
class EngineRecordModel
class RaceRecordModel
class SeasonRecordModel
class TeamRecordModel


DomainModel <|-- CircuitContract
DomainModel <|-- DriverContract
DomainModel <|-- PointsContract

DomainModel <|-- Circuit
DomainModel <|-- EngineManufacturer
DomainModel <|-- EngineRegulation
DomainModel <|-- EngineRestriction

DomainModel <|-- DateValue
DomainModel <|-- DriversChampionships
DomainModel <|-- Link
DomainModel <|-- NormalizedDate
DomainModel <|-- SeasonRef

DomainModel <|-- DriverRecordModel
DomainModel <|-- EngineRecordModel
DomainModel <|-- RaceRecordModel
DomainModel <|-- SeasonRecordModel
DomainModel <|-- TeamRecordModel

CircuitBaseRecord <|-- CircuitCompleteRecord
CircuitBaseRecord <|-- CircuitDetailsRecord
LinkRecord <|-- CarRecord

@enduml
