@startuml

hide circle
hide empty members

abstract class BaseSeasonParser

abstract class SectionParserBase
abstract class BaseDriverResultsSectionParser
abstract class ExtractListItemsMixin

abstract class ParserABC
abstract class HeaderNormalizationMixin
abstract class TableCellExtractionMixin

abstract class InfoboxFieldParserABC
abstract class InfoboxHtmlFieldParserABC
abstract class InfoboxRowsParserABC


class CancelledRoundsParser
class ColinChapmanTrophyParser
class JimClarkTrophyParser
class SeasonCalendarParser
class SeasonEntriesParser
class SeasonFreePracticeParser
class SeasonNonChampionshipParser
class SeasonRegionalChampionshipParser
class SeasonResultsParser
class SeasonScoringSystemParser
class TestingVenuesParser

class ConstructorsSectionParser
class CircuitLayoutHistorySectionParser
class CircuitsListSectionParser
class ConstructorTablesSectionParser
class GrandPrixByYearSectionParser
class SeasonCalendarSectionParser
class SeasonConstructorsStandingsSectionParser
class SeasonDriversStandingsSectionParser
class SeasonMidSeasonChangesSectionParser
class SeasonRegulationChangesSectionParser
class SeasonResultsSectionParser
class TableSectionParser

class CurrentConstructorsSectionParser
class FormerConstructorsSectionParser
class ConstructorChampionshipResultsSectionParser
class ConstructorCompleteF1ResultsSectionParser
class ConstructorHistorySectionParser

class CircuitEventsSectionParser
class CircuitLapRecordsSectionParser
class DriverResultsSectionParser

class CollapsibleTableParser
class ContentTextParser
class InfoboxTableParser
class SponsorPartsParser
class YearParser
class ArticleTablesParser
class HtmlTableParser
class SeasonStandingsParser
class SponsorshipSectionParser
class TeamLiveriesSectionParser
class F1StandingsTableParser
class InfoboxCellValueExtractor
class ListElementParser
class NavboxElementParser
class PrivateerTeamsListParser
class WikiReferencesElementParser
class SeasonsTableParser
class WikiTableParser
class FigureElementParser
class ParagraphElementParser

class ActiveYearsParser
class BestFinishParser
class CallableInfoboxFieldParser
class CarNumbersParser
class ChampionshipsParser
class FinishedSeasonParser
class LicenceParser
class NationalityParser
class RaceEventParser
class TeamsParser

class InfoboxCareerParser
class InfoboxTitlesParser

class CircuitInfoboxParser
class DriverInfoboxParser
class WikiInfoboxHtmlParser

class IndianapolisConstructorsListParser
class IndianapolisOnlyListParser
class CategoryLinksParser

class BodyContentAssembler

class RecursiveSectionParser
class ByRaceTitleSubSectionParser
class CurrentRulesSectionParser
class DetailByDriverSubSectionParser
class DriversListSectionParser
class DriversSectionParser
class EngineManufacturersIndianapolisSubSectionParser
class EngineManufacturersSectionParser
class EngineRegulationSubSectionParser
class EngineSubSectionParser
class FatalitiesSectionParser
class GenericIndianapolisOnlySubSectionParser
class HistorySectionParser
class ManufacturersSectionParser
class NonChampionshipsRacesSubSectionParser
class OfficialDriversSubSectionParser
class PointsScoringSystemsSectionParser
class PrivateerTeamsSectionParser
class RacesSectionParser
class RedFlaggedRacesSectionParser
class SeasonsSectionParser
class ShortenedRacesSubSubSectionParser
class SpecialCasesSubSectionParser
class SpecialCasesSubSubSectionRouter
class SprintRacesSubSubSectionParser
class TyreManufacturersBySeasonSubSectionParser


ParserABC <|-- SectionParserBase
ParserABC <|-- BaseSeasonParser
ParserABC <|-- CategoryLinksParser
ParserABC <|-- RecursiveSectionParser
ParserABC <|-- CollapsibleTableParser
ParserABC <|-- ContentTextParser
ParserABC <|-- InfoboxTableParser
ParserABC <|-- SponsorPartsParser
ParserABC <|-- YearParser
ParserABC <|-- BodyContentAssembler
ParserABC <|-- ArticleTablesParser
ParserABC <|-- HtmlTableParser
ParserABC <|-- SeasonStandingsParser
ParserABC <|-- SponsorshipSectionParser
ParserABC <|-- TeamLiveriesSectionParser
ParserABC <|-- F1StandingsTableParser
ParserABC <|-- InfoboxCellValueExtractor
ParserABC <|-- ListElementParser
ParserABC <|-- NavboxElementParser
ParserABC <|-- PrivateerTeamsListParser
ParserABC <|-- WikiReferencesElementParser
ParserABC <|-- WikiTableParser
ParserABC <|-- FigureElementParser
ParserABC <|-- ParagraphElementParser
ParserABC <|-- WikiInfoboxHtmlParser
ParserABC <|-- InfoboxRowsParserABC
ParserABC <|-- InfoboxHtmlFieldParserABC

HeaderNormalizationMixin <|-- WikiTableParser
TableCellExtractionMixin <|-- WikiTableParser

WikiTableParser <|-- SeasonsTableParser

ListElementParser <|-- IndianapolisOnlyListParser
ListElementParser <|-- IndianapolisConstructorsListParser

RecursiveSectionParser <|-- ByRaceTitleSubSectionParser
RecursiveSectionParser <|-- CurrentRulesSectionParser
RecursiveSectionParser <|-- DetailByDriverSubSectionParser
RecursiveSectionParser <|-- DriversListSectionParser
RecursiveSectionParser <|-- DriversSectionParser
RecursiveSectionParser <|-- EngineManufacturersIndianapolisSubSectionParser
RecursiveSectionParser <|-- EngineManufacturersSectionParser
RecursiveSectionParser <|-- EngineRegulationSubSectionParser
RecursiveSectionParser <|-- EngineSubSectionParser
RecursiveSectionParser <|-- FatalitiesSectionParser
RecursiveSectionParser <|-- GenericIndianapolisOnlySubSectionParser
RecursiveSectionParser <|-- HistorySectionParser
RecursiveSectionParser <|-- ManufacturersSectionParser
RecursiveSectionParser <|-- NonChampionshipsRacesSubSectionParser
RecursiveSectionParser <|-- OfficialDriversSubSectionParser
RecursiveSectionParser <|-- PointsScoringSystemsSectionParser
RecursiveSectionParser <|-- PrivateerTeamsSectionParser
RecursiveSectionParser <|-- RacesSectionParser
RecursiveSectionParser <|-- RedFlaggedRacesSectionParser
RecursiveSectionParser <|-- SeasonsSectionParser
RecursiveSectionParser <|-- ShortenedRacesSubSubSectionParser
RecursiveSectionParser <|-- SpecialCasesSubSectionParser
RecursiveSectionParser <|-- SpecialCasesSubSubSectionRouter
RecursiveSectionParser <|-- SprintRacesSubSubSectionParser
RecursiveSectionParser <|-- TyreManufacturersBySeasonSubSectionParser

WikiInfoboxHtmlParser <|-- CircuitInfoboxParser
WikiInfoboxHtmlParser <|-- DriverInfoboxParser

InfoboxRowsParserABC <|-- InfoboxCareerParser
InfoboxRowsParserABC <|-- InfoboxTitlesParser

InfoboxHtmlFieldParserABC <|-- ActiveYearsParser
InfoboxHtmlFieldParserABC <|-- BestFinishParser
InfoboxHtmlFieldParserABC <|-- CallableInfoboxFieldParser
InfoboxHtmlFieldParserABC <|-- CarNumbersParser
InfoboxHtmlFieldParserABC <|-- ChampionshipsParser
InfoboxHtmlFieldParserABC <|-- FinishedSeasonParser
InfoboxHtmlFieldParserABC <|-- LicenceParser
InfoboxHtmlFieldParserABC <|-- NationalityParser
InfoboxHtmlFieldParserABC <|-- RaceEventParser
InfoboxHtmlFieldParserABC <|-- TeamsParser

SectionParserBase <|-- BaseDriverResultsSectionParser
SectionParserBase <|-- CircuitLayoutHistorySectionParser
SectionParserBase <|-- CircuitsListSectionParser
SectionParserBase <|-- ConstructorsSectionParser
SectionParserBase <|-- ConstructorTablesSectionParser
SectionParserBase <|-- GrandPrixByYearSectionParser
SectionParserBase <|-- SeasonCalendarSectionParser
SectionParserBase <|-- SeasonConstructorsStandingsSectionParser
SectionParserBase <|-- SeasonDriversStandingsSectionParser
SectionParserBase <|-- SeasonMidSeasonChangesSectionParser
SectionParserBase <|-- SeasonRegulationChangesSectionParser
SectionParserBase <|-- SeasonResultsSectionParser
SectionParserBase <|-- TableSectionParser

ExtractListItemsMixin <|-- SeasonMidSeasonChangesSectionParser
ExtractListItemsMixin <|-- SeasonRegulationChangesSectionParser

ConstructorsSectionParser <|-- CurrentConstructorsSectionParser
ConstructorsSectionParser <|-- FormerConstructorsSectionParser

ConstructorTablesSectionParser <|-- ConstructorChampionshipResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorCompleteF1ResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorHistorySectionParser

TableSectionParser <|-- CircuitEventsSectionParser
TableSectionParser <|-- CircuitLapRecordsSectionParser
TableSectionParser <|-- DriverResultsSectionParser

BaseSeasonParser <|-- CancelledRoundsParser
BaseSeasonParser <|-- ColinChapmanTrophyParser
BaseSeasonParser <|-- JimClarkTrophyParser
BaseSeasonParser <|-- SeasonCalendarParser
BaseSeasonParser <|-- SeasonEntriesParser
BaseSeasonParser <|-- SeasonFreePracticeParser
BaseSeasonParser <|-- SeasonNonChampionshipParser
BaseSeasonParser <|-- SeasonRegionalChampionshipParser
BaseSeasonParser <|-- SeasonResultsParser
BaseSeasonParser <|-- SeasonScoringSystemParser
BaseSeasonParser <|-- TestingVenuesParser

@enduml
