@startuml
title Circuit & Infobox Text Utilities
skinparam classAttributeIconSize 0
hide empty members
hide circle

class CircuitAdditionalInfoExtractor
class CircuitEntityExtractor
class CircuitGeoExtractor
class CircuitHistoryExtractor
class CircuitLapRecordExtractor
class CircuitSpecsExtractor
class CircuitTextProcessing
class InfoboxTextUtils

CircuitEntityExtractor <|-- CircuitAdditionalInfoExtractor
CircuitTextProcessing <|-- CircuitEntityExtractor
InfoboxTextUtils <|-- CircuitGeoExtractor
InfoboxTextUtils <|-- CircuitHistoryExtractor
CircuitTextProcessing <|-- CircuitLapRecordExtractor
InfoboxTextUtils <|-- CircuitSpecsExtractor
InfoboxTextUtils <|-- CircuitTextProcessing

@enduml