from __future__ import annotations

# Auto-curated exceptions for intentional wrappers and transitional APIs.
REDUNDANT_ALIAS_EXCEPTIONS: set[tuple[str, str]] = {
    ("complete_extractor/base.py", "get_detail_url"),
    ("config/app_config_provider.py", "get_http_config"),
    ("infrastructure/cache/file_ttl_cache.py", "serialize"),
    ("infrastructure/http_client/clients/base.py", "get_json"),
    ("infrastructure/http_client/clients/base.py", "get_text"),
    ("infrastructure/http_client/requests_shim/ssl.py", "build_ssl_context"),
    ("layers/facade.py", "run_merge_only"),
    ("layers/seed/registry/entries.py", "to_dict"),
    ("layers/seed/registry/helpers.py", "clear_wiki_seed_registry_cache"),
    ("layers/zero/merge_types.py", "is_record_dict"),
    ("layers/zero/record_merge_ops.py", "normalize_incoming_driver_stats"),
    ("layers/zero/run_profile_paths.py", "build_debug_run_config"),
    ("layers/zero/run_profile_paths.py", "raw_file_path"),
    ("models/mappers/serialization.py", "clear_serializable_adapters"),
    ("models/mappers/serialization.py", "to_circuit_record_dict"),
    ("models/records/base_factory.py", "apply_aliases"),
    ("models/records/base_factory.py", "normalize_float_fields"),
    ("models/records/base_factory.py", "normalize_int_fields"),
    ("models/records/base_factory.py", "normalize_link_fields"),
    ("models/records/base_factory.py", "normalize_link_list_fields"),
    ("models/records/factories/build.py", "build"),
    ("models/records/factories/build.py", "build_record"),
    ("models/records/field_normalizer.py", "normalize_bool"),
    ("models/records/field_normalizer.py", "normalize_link"),
    ("models/records/record_definition.py", "to_schema"),
    ("models/records/record_definition.py", "validate_record"),
    ("models/validation/base.py", "validate_schema"),
    ("models/validation/helpers.py", "validate_float"),
    ("models/validation/helpers.py", "validate_int"),
    ("models/validation/validators.py", "normalize_season_list"),
    ("models/value_objects/common_terms.py", "to_export"),
    ("models/value_objects/link_utils.py", "normalize_link"),
    ("models/value_objects/normalized_date.py", "from_mapping"),
    ("models/value_objects/rounds.py", "from_values"),
    ("models/value_objects/rounds.py", "to_list"),
    ("models/value_objects/time_types.py", "from_mapping"),
    ("scrapers/base/abc.py", "build_result"),
    ("scrapers/base/abc.py", "fetch_html"),
    ("scrapers/base/abc.py", "get_http_policy"),
    ("scrapers/base/abc.py", "parse_soup"),
    ("scrapers/base/data_extractor.py", "build_result"),
    ("scrapers/base/data_extractor.py", "get_http_policy"),
    ("scrapers/base/domain_entrypoint.py", "debug_profile"),
    ("scrapers/base/domain_entrypoint.py", "default_profile"),
    ("scrapers/base/error_handler.py", "wrap_domain_parse"),
    ("scrapers/base/error_handler.py", "wrap_network"),
    ("scrapers/base/error_handler.py", "wrap_parse"),
    ("scrapers/base/error_handler.py", "wrap_validation"),
    ("scrapers/base/errors.py", "behavior"),
    ("scrapers/base/export/composition.py", "create_default_export_service"),
    ("scrapers/base/export/metadata.py", "from_result"),
    ("scrapers/base/extractors/table.py", "parse_row"),
    ("scrapers/base/extractors/table.py", "set_run_id"),
    ("scrapers/base/factory/option_adapter.py", "supports"),
    ("scrapers/base/factory/record_factory.py", "builders"),
    ("scrapers/base/factory/record_factory.py", "callable"),
    ("scrapers/base/factory/record_factory.py", "create"),
    ("scrapers/base/factory/record_factory.py", "mapping"),
    ("scrapers/base/helpers/normalize.py", "normalize_auto_value"),
    ("scrapers/base/helpers/parsing.py", "parse_float_from_text"),
    ("scrapers/base/helpers/parsing.py", "parse_int_from_text"),
    ("scrapers/base/helpers/parsing.py", "parse_number_with_unit"),
    ("scrapers/base/helpers/path.py", "ensure_parent"),
    ("scrapers/base/helpers/text.py", "strip_marks"),
    ("scrapers/base/helpers/text.py", "strip_wiki_refs"),
    ("scrapers/base/helpers/value_objects/lap_record.py", "from_dict"),
    ("scrapers/base/helpers/value_objects/lap_record.py", "get"),
    ("scrapers/base/helpers/value_objects/lap_record.py", "items"),
    ("scrapers/base/helpers/value_objects/lap_record.py", "keys"),
    ("scrapers/base/helpers/value_objects/lap_record.py", "pop"),
    ("scrapers/base/helpers/value_objects/lap_record.py", "setdefault"),
    ("scrapers/base/helpers/value_objects/lap_record.py", "update"),
    ("scrapers/base/html_fetcher.py", "get"),
    ("scrapers/base/html_fetcher.py", "metadata"),
    ("scrapers/base/infobox/dsl.py", "build"),
    ("scrapers/base/infobox/dsl.py", "field"),
    ("scrapers/base/infobox/dsl.py", "from_schema"),
    ("scrapers/base/infobox/html_parser.py", "extract_links"),
    ("scrapers/base/infobox/html_parser.py", "find_infobox"),
    ("scrapers/base/infobox/service.py", "as_list"),
    ("scrapers/base/infobox/service.py", "normalize_result"),
    ("scrapers/base/normalization_pipeline.py", "is_link_list"),
    ("scrapers/base/options.py", "build_scraper_options"),
    ("scrapers/base/pipeline_runner.py", "as_dict"),
    ("scrapers/base/run_profiles.py", "coerce_profile"),
    ("scrapers/base/run_profiles.py", "resolve"),
    ("scrapers/base/run_profiles.py", "resolve_cli_profile"),
    ("scrapers/base/scraper_components.py", "build_validation_runner"),
    ("scrapers/base/scraper_components.py", "to_dict_records"),
    ("scrapers/base/sections/resolve_candidates.py", "resolve_section_candidates"),
    ("scrapers/base/sections/section_id_resolver.py", "as_domain_error"),
    ("scrapers/base/sections/section_table_parser_base.py", "build_result"),
    ("scrapers/base/sections/serializer.py", "build_section_parse_result"),
    (
        "scrapers/base/services/result_export_service.py",
        "export_scraper_result_to_json",
    ),
    ("scrapers/base/source_catalog.py", "base_url"),
    ("scrapers/base/source_catalog.py", "url"),
    ("scrapers/base/table/builders.py", "build_table_schema"),
    ("scrapers/base/table/builders.py", "entity_column"),
    ("scrapers/base/table/builders.py", "metric_column"),
    ("scrapers/base/table/columns/helpers/driver_parsing.py", "build_link_lookup"),
    ("scrapers/base/table/columns/helpers/engine_link_helpers.py", "build_link_lookup"),
    ("scrapers/base/table/columns/helpers/engine_parsing.py", "build_link_lookup"),
    (
        "scrapers/base/table/columns/helpers/results_parsing.py",
        "extract_race_result_background",
    ),
    ("scrapers/base/table/columns/types/column_factory.py", "FloatColumn"),
    ("scrapers/base/table/columns/types/column_factory.py", "IntColumn"),
    ("scrapers/base/table/columns/types/constructor_part.py", "parse"),
    ("scrapers/base/table/columns/types/func.py", "parse"),
    ("scrapers/base/table/columns/types/name_status.py", "checker"),
    ("scrapers/base/table/dsl/column.py", "column"),
    ("scrapers/base/table/headers.py", "normalize_header"),
    ("scrapers/base/table/schema.py", "build"),
    ("scrapers/base/table/scraper.py", "parse_row"),
    ("scrapers/circuits/composition.py", "for_tests"),
    ("scrapers/circuits/helpers/sections.py", "is_circuit_like_article"),
    ("scrapers/circuits/infobox/service.py", "build_parser"),
    ("scrapers/circuits/infobox/service.py", "normalize_result"),
    ("scrapers/circuits/infobox/services/text_utils.py", "prune_nulls"),
    ("scrapers/circuits/schemas.py", "build_circuits_schema"),
    ("scrapers/circuits/sections/list_table.py", "build_schema"),
    ("scrapers/circuits/sections/service.py", "build_entries"),
    ("scrapers/config.py", "default_config"),
    ("scrapers/config.py", "default_data_paths"),
    ("scrapers/config.py", "default_scraper_config"),
    (
        "scrapers/constructors/base_constructor_list_scraper.py",
        "build_common_metadata_columns",
    ),
    (
        "scrapers/constructors/base_constructor_list_scraper.py",
        "build_common_stats_columns",
    ),
    ("scrapers/constructors/composition.py", "for_tests"),
    ("scrapers/constructors/config_factory.py", "build_constructor_list_config"),
    ("scrapers/constructors/postprocess/assembler.py", "assemble"),
    ("scrapers/constructors/sections/common.py", "parse"),
    ("scrapers/constructors/sections/service.py", "build_entries"),
    ("scrapers/deprecation_catalog.py", "get_deprecated_module_migrations"),
    ("scrapers/drivers/composition.py", "for_tests"),
    ("scrapers/drivers/female_drivers_list.py", "build_schema"),
    ("scrapers/drivers/infobox/parsers/cell.py", "parse_car_numbers"),
    ("scrapers/drivers/infobox/parsers/cell.py", "parse_entries"),
    ("scrapers/drivers/infobox/parsers/cell.py", "parse_float_cell"),
    ("scrapers/drivers/infobox/parsers/cell.py", "parse_int_cell"),
    ("scrapers/drivers/infobox/parsers/cell.py", "parse_nested_table"),
    ("scrapers/drivers/infobox/parsers/year.py", "detect_url_pattern"),
    ("scrapers/drivers/infobox/service.py", "build_parser"),
    ("scrapers/drivers/list_scraper.py", "build_schema"),
    ("scrapers/drivers/sections/common.py", "from_config"),
    ("scrapers/engines/columns/configuration.py", "parse"),
    ("scrapers/engines/columns/engine_rpm_limit.py", "parse"),
    ("scrapers/engines/columns/fuel_flow_rate.py", "parse"),
    ("scrapers/engines/columns/fuel_injection_pressure_limit.py", "parse"),
    ("scrapers/engines/columns/fuel_limit_per_race.py", "parse"),
    ("scrapers/engines/engine_manufacturers_list.py", "build_schema"),
    ("scrapers/engines/engine_regulation.py", "build_schema"),
    ("scrapers/engines/engine_restrictions.py", "build_schema"),
    ("scrapers/grands_prix/columns/restart_status.py", "parse"),
    ("scrapers/grands_prix/helpers/sections.py", "has_grand_prix_category"),
    ("scrapers/grands_prix/helpers/sections.py", "has_grand_prix_navbox"),
    ("scrapers/grands_prix/list_scraper.py", "build_schema"),
    (
        "scrapers/points/config_factory.py",
        "build_points_scoring_systems_history_config",
    ),
    ("scrapers/seasons/composition.py", "for_tests"),
    ("scrapers/seasons/list_scraper.py", "build_schema"),
    ("scrapers/seasons/postprocess/assembler.py", "empty"),
    ("scrapers/seasons/sections/service.py", "extract"),
    ("scrapers/sponsorship_liveries/parsers/section.py", "build_schema"),
    (
        "scrapers/sponsorship_liveries/parsers/splitters/record/pipeline_record.py",
        "get",
    ),
    (
        "scrapers/sponsorship_liveries/parsers/splitters/record/pipeline_record.py",
        "to_dict",
    ),
    (
        "scrapers/sponsorship_liveries/parsers/splitters/record/pipeline_record.py",
        "with_updates",
    ),
    ("scrapers/sponsorship_liveries/parsers/splitters/record/rules.py", "should_apply"),
    ("scrapers/tyres/list_scraper.py", "build_schema"),
    ("scrapers/wiki/component_metadata.py", "build_layer_one_list_scraper"),
    ("scrapers/wiki/parsers/body_content.py", "find_body_content"),
    ("scrapers/wiki/parsers/elements/infobox.py", "parse"),
    ("scrapers/wiki/parsers/elements/infobox.py", "parse_row_value"),
    ("scrapers/wiki/parsers/elements/mixin.py", "find_infobox"),
    ("scrapers/wiki/parsers/elements/mixin.py", "find_infoboxes"),
    ("scrapers/wiki/parsers/elements/parsers.py", "build_default_wiki_element_parsers"),
    ("scrapers/wiki/parsers/elements/text_cleaning.py", "clean_table_cell_text"),
    ("scrapers/wiki/parsers/header.py", "find_header"),
    ("scrapers/wiki/parsers/sections/base_nested_section.py", "parse"),
    ("scrapers/wiki/parsers/sections/data_classes.py", "with_section"),
    ("scrapers/wiki/parsers/sections/detection.py", "normalize_section_text"),
    (
        "scrapers/wiki/parsers/sections/normalization.py",
        "normalize_section_profile_key",
    ),
    ("scrapers/wiki/parsers/sections/sub_sub_sub_section.py", "parse"),
    ("validation/composite_validator.py", "validate"),
    ("validation/composite_validator.py", "with_rules"),
    ("validation/issue.py", "custom"),
    ("validation/issue.py", "render"),
    ("validation/pipeline.py", "validate"),
    ("validation/record_factory_validator.py", "validate_record"),
    ("validation/rules.py", "range_rule"),
    ("validation/rules.py", "required_field_rule"),
    ("validation/rules.py", "type_rule"),
    ("validation/validator_base.py", "prefix_errors"),
}

MAX_FUNCTION_LINES_EXCEPTIONS: dict[tuple[str, str], int] = {
    ("layers/one/executor.py", "run"): 128,
}
