@startuml
title Error Hierarchy
skinparam classAttributeIconSize 0
hide empty members
hide circle

class DomainParseError
class HTTPError
class HTTPTimeoutError
class HttpShimError
class PipelineError
class RequestError
class ScraperError
class ScraperNetworkError
class ScraperNotFoundError
class ScraperParseError
class ScraperValidationError
class SourceParseError
class TransportError
class ValidationError

ScraperError <|-- DomainParseError
HttpShimError <|-- HTTPError
HttpShimError <|-- HTTPTimeoutError
RequestError <|-- HttpShimError
ScraperError <|-- PipelineError
ScraperError <|-- ScraperNetworkError
ScraperError <|-- ScraperNotFoundError
ScraperError <|-- ScraperParseError
ScraperError <|-- ScraperValidationError
PipelineError <|-- SourceParseError
PipelineError <|-- TransportError
PipelineError <|-- ValidationError

@enduml