@startuml
title Layers, Executors & Job Runners
skinparam classAttributeIconSize 0
hide empty members
hide circle

abstract class BaseExecutor
abstract class BaseOrchestrationFlow
class BaseRegistryEntry
class DefaultLayerZeroRunConfigFactory
class DriversCheckpointFlow
class FunctionExportRunner
class GrandPrixRunner
abstract class LayerJobRunner
class LayerOneExecutor
class LayerZeroExecutor
abstract class LayerZeroRunConfigFactory
class ListJobRegistryEntry
abstract class MetadataBindingMixin
class SeedRegistryEntry
class SeedSectionOrchestrationFlow
class SponsorshipLiveriesRunConfigFactory
class StaticScraperKwargsFactory

LayerZeroRunConfigFactory <|-- DefaultLayerZeroRunConfigFactory
BaseOrchestrationFlow <|-- DriversCheckpointFlow
LayerJobRunner <|-- FunctionExportRunner
LayerJobRunner <|-- GrandPrixRunner
BaseExecutor <|-- LayerOneExecutor
BaseExecutor <|-- LayerZeroExecutor
BaseRegistryEntry <|-- ListJobRegistryEntry
BaseRegistryEntry <|-- SeedRegistryEntry
BaseOrchestrationFlow <|-- SeedSectionOrchestrationFlow
LayerZeroRunConfigFactory <|-- SponsorshipLiveriesRunConfigFactory
LayerZeroRunConfigFactory <|-- StaticScraperKwargsFactory

@enduml
