CONSTRUCTOR_NAME_HEADER = "Constructor"
CONSTRUCTOR_ENGINE_HEADER = "Engine"
CONSTRUCTOR_LICENSED_IN_HEADER = "Licensed in"
CONSTRUCTOR_BASED_IN_HEADER = "Based in"
CONSTRUCTOR_DRIVERS_HEADER = "Drivers"
CONSTRUCTOR_TOTAL_ENTRIES_HEADER = "Total Entries"
CONSTRUCTOR_WCC_HEADER = "WCC"  # World Constructors' Championship.
CONSTRUCTOR_WDC_HEADER = "WDC"  # World Drivers' Championship.
CONSTRUCTOR_ANTECEDENT_TEAMS_HEADER = "Antecedent teams"  # Poprzednie zespoły.

CONSTRUCTOR_SEASONS_HEADER = "Seasons"
CONSTRUCTOR_RACES_ENTERED_HEADER = "Races Entered"
CONSTRUCTOR_RACES_STARTED_HEADER = "Races Started"
CONSTRUCTOR_WINS_HEADER = "Wins"
CONSTRUCTOR_POINTS_HEADER = "Points"
CONSTRUCTOR_POLES_HEADER = "Poles"
CONSTRUCTOR_FASTEST_LAPS_HEADER = "FL"  # Fastest laps.
CONSTRUCTOR_PODIUMS_HEADER = "Podiums"

CONSTRUCTORS_2025_EXPECTED_HEADERS = [
    CONSTRUCTOR_NAME_HEADER,
    CONSTRUCTOR_ENGINE_HEADER,
    CONSTRUCTOR_LICENSED_IN_HEADER,
    CONSTRUCTOR_BASED_IN_HEADER,
]

FORMER_CONSTRUCTORS_EXPECTED_HEADERS = [
    CONSTRUCTOR_NAME_HEADER,
    CONSTRUCTOR_LICENSED_IN_HEADER,
    CONSTRUCTOR_SEASONS_HEADER,
]
