@startuml
scale max 1920 width
left to right direction
"RetryPolicy" <|-- "DefaultRetryPolicy"
"ABC" <|-- "RetryPolicy"
"Protocol" <|-- "TextCacheProtocol"
"Protocol" <|-- "HttpResponseProtocol"
"Protocol" <|-- "SessionProtocol"
"Protocol" <|-- "HttpClientProtocol"
"Exception" <|-- "RequestError"
"HttpShimError" <|-- "HTTPError"
"HttpShimError" <|-- "HTTPTimeoutError"
"RequestError" <|-- "HttpShimError"
"BaseHttpClient" <|-- "UrllibHttpClient"
"ABC" <|-- "BaseHttpClient"
"RateLimiter" <|-- "MinDelayRateLimiter"
"ABC" <|-- "RateLimiter"
"TextCacheProtocol" <|-- "WikipediaCachePolicy"
"TextCacheProtocol" <|-- "FileCache"
"Generic" <|-- "FileTtlCache"
"Generic" <|-- "FileTtlCacheAdapter"
"ABC" <|-- "FileTtlCacheAdapter"
"FileTtlCacheAdapter" <|-- "HttpResponseFileCacheAdapter"
"FileTtlCacheAdapter" <|-- "GeminiJsonFileCacheAdapter"
"WikiScraper" <|-- "RedFlaggedRacesScraper"
"BasePointsScraper" <|-- "PointsScraper"
"CompleteExtractorBase" <|-- "F1CompleteGrandPrixDataExtractor"
"SeedListTableScraper" <|-- "F1DriversListScraper"
"SingleWikiArticleSectionAdapterBase" <|-- "SingleSeasonScraper"
"CompleteExtractorBase" <|-- "CompleteSeasonDataExtractor"
"SingleWikiArticleSectionAdapterBase" <|-- "F1SingleCircuitScraper"
"F1TableScraper" <|-- "LapRecordsTableScraper"
"Protocol" <|-- "ProgressAdapter"
"SeasonScraperCompositionFactory" <|-- "SeasonsFactory"
"Protocol" <|-- "NormalizationPlugin"
"WikiElementParsingMixin" <|-- "WikiScraper"
"ABCScraper" <|-- "WikiScraper"
"BaseInfoboxOrchestrator" <|-- "StrategyBackedInfoboxOrchestrator"
"BaseEngineTableScraper" <|-- "EngineRegulationScraper"
"CompleteExtractorBase" <|-- "F1CompleteCircuitDataExtractor"
"WikiScraper" <|-- "F1TableScraper"
"TableScraperContract" <|-- "F1TableScraper"
"ABC" <|-- "F1TableScraper"
"SeasonPipelineService" <|-- "SeasonsPipelineService"
"SingleWikiArticleScraperBase" <|-- "SingleEngineManufacturerScraper"
"StrategyBackedInfoboxOrchestrator" <|-- "CircuitInfoboxOrchestrator"
"DeclarativeSectionTableParseMixin" <|-- "BaseConstructorListScraper"
"SeedListTableScraper" <|-- "BaseConstructorListScraper"
"Formatter" <|-- "JsonLinesFormatter"
"FetchCapability" <|-- "ScraperLifecycleProtocol"
"ValidateCapability" <|-- "ScraperLifecycleProtocol"
"ExportCapability" <|-- "ScraperLifecycleProtocol"
"Protocol" <|-- "ScraperLifecycleProtocol"
"ABC" <|-- "ScraperLifecycleABC"
"ScraperLifecycleABC" <|-- "BaseScraperCore"
"ABC" <|-- "BaseScraperCore"
"FetchOrchestrationMixin" <|-- "ABCScraper"
"BaseScraperCore" <|-- "ABCScraper"
"SingleWikiArticleSectionAdapterBase" <|-- "SingleConstructorScraper"
"str" <|-- "RunProfileName"
"Enum" <|-- "RunProfileName"
"str" <|-- "RunPathName"
"Enum" <|-- "RunPathName"
"SeedListTableScraper" <|-- "SeasonsListScraper"
"_SeasonsListScraper" <|-- "SeasonsListScraper"
"CompositeRecordValidator" <|-- "SchemaCompositeRecordValidator"
"Protocol" <|-- "RecordAssemblerProtocol"
"Protocol" <|-- "SectionExtractionServiceProtocol"
"UrlResolverMixin" <|-- "DriversSeedNormalizer"
"BaseNormalizer" <|-- "DriversSeedNormalizer"
"BaseOrchestrationFlow" <|-- "DriversCheckpointFlow"
"DeclarativeSectionTableParseMixin" <|-- "CircuitsListScraper"
"SeedListTableScraper" <|-- "CircuitsListScraper"
"_CircuitsListScraper" <|-- "CircuitsListScraper"
"BaseExtractor" <|-- "DomainSeedExtractor"
"UrlResolverMixin" <|-- "DomainSeedNormalizer"
"BaseNormalizer" <|-- "DomainSeedNormalizer"
"QualityMetricsMixin" <|-- "DomainStageOrchestrator"
"BaseOrchestrator" <|-- "DomainStageOrchestrator"
"BaseOrchestrationFlow" <|-- "SeedSectionOrchestrationFlow"
"DriverOrderedTableMapper" <|-- "FatalitiesTableMapper"
"SubSectionParser" <|-- "DetailByDriverSubSectionParser"
"NestedWikiSectionParser" <|-- "FatalitiesSectionParser"
"F1TableScraper" <|-- "F1FatalitiesListScraper"
"Protocol" <|-- "OutputPathRenderer"
"Protocol" <|-- "OutputPathRenderer"
"str" <|-- "TestingVenuesLayout"
"Enum" <|-- "TestingVenuesLayout"
"Protocol" <|-- "ListScraperContract"
"Protocol" <|-- "TableScraperContract"
"Protocol" <|-- "SingleArticleScraperContract"
"F1TableScraper" <|-- "BaseEngineTableScraper"
"ABC" <|-- "BaseEngineTableScraper"
"SchemaCompositeRecordValidator" <|-- "DriversRecordValidator"
"SchemaCompositeRecordValidator" <|-- "GrandsPrixRecordValidator"
"_ConstructorsListScraper" <|-- "ConstructorsListScraper"
"ListScraper" <|-- "ConstructorsListScraper"
"SingleWikiArticleScraperBase" <|-- "F1SingleGrandPrixScraper"
"F1TableScraper" <|-- "RedFlaggedRacesBaseScraper"
"F1TableScraper" <|-- "BasePointsScraper"
"SourceAdapter" <|-- "HtmlFetcher"
"SourceAdapter" <|-- "CacheAdapter"
"WikiTableBaseMapper" <|-- "TyreManufacturersBySeasonTableMapper"
"SubSectionParser" <|-- "TyreManufacturersBySeasonSubSectionParser"
"NestedWikiSectionParser" <|-- "ManufacturersSectionParser"
"F1TableScraper" <|-- "TyreManufacturersScraper"
"CompleteExtractorBase" <|-- "CompleteConstructorsDataExtractor"
"Enum" <|-- "EmptyValuePolicy"
"ABC" <|-- "Extractor"
"Generic" <|-- "Extractor"
"ABC" <|-- "Factory"
"Generic" <|-- "Factory"
"ABC" <|-- "Scraper"
"Generic" <|-- "Scraper"
"ABC" <|-- "PipelineService"
"Generic" <|-- "PipelineService"
"F1TableScraper" <|-- "SeedListTableScraper"
"ListScraperContract" <|-- "SeedListTableScraper"
"ABC" <|-- "BaseDataExtractor"
"CompleteExtractorBase" <|-- "F1CompleteEngineManufacturerDataExtractor"
"Protocol" <|-- "InfoboxOrchestratorProtocol"
"HtmlFetcher" <|-- "SourceAdapterFetcherShim"
"WikiScraper" <|-- "F1SponsorshipLiveriesScraper"
"DriverPipelineService" <|-- "DriversPipelineService"
"ABC" <|-- "BaseInfoboxOrchestrator"
"Generic" <|-- "BaseInfoboxOrchestrator"
"ParsedRecordsMixin" <|-- "BaseInfoboxOrchestrator"
"Protocol" <|-- "ExportableRecord"
"CompleteExtractorBase" <|-- "CompleteDriverDataExtractor"
"ABC" <|-- "SourceAdapter"
"Generic" <|-- "IterableSourceAdapter"
"Generic" <|-- "MultiIterableSourceAdapter"
"DriverScraperCompositionFactory" <|-- "DriversFactory"
"F1SingleCircuitScraper" <|-- "CircuitsDetailScraper"
"SingleWikiArticleSectionAdapterBase" <|-- "SingleDriverScraper"
"BaseEngineTableScraper" <|-- "EngineRestrictionsScraper"
"ConstructorScraperCompositionFactory" <|-- "ConstructorsFactory"
"Protocol" <|-- "ListScraperProtocol"
"Protocol" <|-- "SingleScraperProtocol"
"BaseDataExtractor" <|-- "CompositeDataExtractor"
"BaseInfoboxOrchestrator" <|-- "ConstructorInfoboxOrchestrator"
"F1TableScraper" <|-- "F1StandingsScraper"
"WikiTableBaseMapper" <|-- "GrandsPrixTableMapper"
"SubSectionParser" <|-- "ByRaceTitleSubSectionParser"
"ApplyForElementsMixin" <|-- "ByRaceTitleSubSectionParser"
"NestedWikiSectionParser" <|-- "RacesSectionParser"
"SeedListTableScraper" <|-- "GrandsPrixListScraper"
"SchemaCompositeRecordValidator" <|-- "CircuitsRecordValidator"
"BaseInfoboxOrchestrator" <|-- "DriverInfoboxOrchestrator"
"F1TableScraper" <|-- "EngineManufacturersListScraper"
"Protocol" <|-- "RecordPostProcessor"
"SingleConstructorScraper" <|-- "ConstructorsDetailScraper"
"WikiTableBaseMapper" <|-- "FemaleDriversTableMapper"
"SubSectionParser" <|-- "OfficialDriversSubSectionParser"
"ApplyForElementsMixin" <|-- "OfficialDriversSubSectionParser"
"NestedWikiSectionParser" <|-- "DriversSectionParser"
"F1TableScraper" <|-- "FemaleDriversListScraper"
"ConstructorPipelineService" <|-- "ConstructorsPipelineService"
"CircuitScraperCompositionFactory" <|-- "CircuitsFactory"
"SingleSeasonScraper" <|-- "SeasonsDetailScraper"
"Protocol" <|-- "ScraperCreationAdapter"
"ABC" <|-- "BaseColumn"
"ABC" <|-- "ConstructorPartParserABC"
"Protocol" <|-- "ResultRule"
"Protocol" <|-- "RoundRule"
"BaseColumn" <|-- "SponsorshipSeasonsColumn"
"BaseColumn" <|-- "NestedTextColumn"
"BaseColumn" <|-- "EngineRpmLimitColumn"
"BaseColumn" <|-- "TimeRangeColumn"
"BaseColumn" <|-- "FirstPlaceColumn"
"BackgroundMixin" <|-- "RaceResultColumn"
"BaseColumn" <|-- "RaceResultColumn"
"BaseColumn" <|-- "DriverColumn"
"BaseColumn" <|-- "SponsorColumn"
"BaseColumn" <|-- "FuelFlowRateColumn"
"BaseColumn" <|-- "ColourListColumn"
"BaseColumn" <|-- "PointsOrTextColumn"
"BaseColumn" <|-- "BrListColumn"
"BaseColumn" <|-- "UnitColumn"
"EnumMarksMixin" <|-- "FatalityEventColumn"
"BackgroundMixin" <|-- "FatalityEventColumn"
"BaseColumn" <|-- "FatalityEventColumn"
"BaseColumn" <|-- "TextColumn"
"BaseColumn" <|-- "TimeColumn"
"BaseColumn" <|-- "BoolColumn"
"BaseColumn" <|-- "RangeColumn"
"LinksListColumn" <|-- "AppendLinksColumn"
"BaseColumn" <|-- "EngineConfigurationColumn"
"BaseColumn" <|-- "DriversWithRoundsColumn"
"BaseColumn" <|-- "ListColumn"
"BackgroundMixin" <|-- "RoundColumn"
"BaseColumn" <|-- "RoundColumn"
"BaseColumn" <|-- "SkipColumn"
"BaseColumn" <|-- "SeriesColumn"
"BaseColumn" <|-- "PointsColumn"
"BaseColumn" <|-- "NestedUnitListColumn"
"BaseColumn" <|-- "LinksListColumn"
"BaseColumn" <|-- "DateColumn"
"BaseColumn" <|-- "RegexColumn"
"BackgroundMixin" <|-- "RestartStatusColumn"
"BaseColumn" <|-- "RestartStatusColumn"
"BaseColumn" <|-- "EntrantColumn"
"BaseColumn" <|-- "FuelLimitPerRaceColumn"
"BaseColumn" <|-- "UrlColumn"
"EnumMarksMixin" <|-- "FatalityDateColumn"
"BaseColumn" <|-- "FatalityDateColumn"
"BaseColumn" <|-- "EngineColumn"
"BaseColumn" <|-- "PositionColumn"
"BaseColumn" <|-- "CalendarCircuitColumn"
"BaseColumn" <|-- "DriverListColumn"
"BaseColumn" <|-- "DateRangeColumn"
"BaseColumn" <|-- "TyreColumn"
"BaseColumn" <|-- "EntriesStartsColumn"
"BaseColumn" <|-- "ParsedValueColumn"
"BaseColumn" <|-- "FuelInjectionPressureLimitColumn"
"BaseColumn" <|-- "AutoColumn"
"BaseColumn" <|-- "ConstructorNameColumn"
"BaseColumn" <|-- "SeasonsColumn"
"BaseColumn" <|-- "UnknownValueColumn"
"BaseColumn" <|-- "SeasonDateColumn"
"BaseColumn" <|-- "MultiColumn"
"MultiColumn" <|-- "ConstructorSplitColumn"
"MultiColumn" <|-- "LastLengthUsedColumn"
"NameStatusColumn" <|-- "EngineManufacturerNameStatusColumn"
"NameStatusColumn" <|-- "DriverNameStatusColumn"
"NameStatusColumn" <|-- "CircuitNameStatusColumn"
"BackgroundMixin" <|-- "NameStatusColumn"
"MultiColumn" <|-- "NameStatusColumn"
"EnumMarksMixin" <|-- "NameStatusColumn"
"ABC" <|-- "NameStatusColumn"
"NameStatusColumn" <|-- "RaceTitleStatusColumn"
"FuncColumn" <|-- "LocationColumn"
"BaseColumn" <|-- "FuncColumn"
"BaseConstructorColumn" <|-- "ConstructorColumn"
"BaseColumn" <|-- "ConstructorPartColumn"
"ConstructorPartParserABC" <|-- "ConstructorPartColumn"
"BaseColumn" <|-- "BaseConstructorColumn"
"BaseDomainPipelineService" <|-- "ConstructorPipelineService"
"RunDiagnosticsMixin" <|-- "ConstructorTableExtractionService"
"BaseDomainPipelineService" <|-- "DriverPipelineService"
"BaseDomainPipelineService" <|-- "CircuitPipelineService"
"BaseDomainPipelineService" <|-- "SeasonPipelineService"
"DomainPipelineService" <|-- "BaseDomainPipelineService"
"Generic" <|-- "BaseDomainPipelineService"
"PipelineService" <|-- "DomainPipelineService"
"RunDiagnosticsMixin" <|-- "DomainPipelineService"
"ABC" <|-- "DomainPipelineService"
"Generic" <|-- "DomainPipelineService"
"BaseSectionExtractionService" <|-- "DriverSectionExtractionService"
"BaseSectionExtractionService" <|-- "ConstructorSectionExtractionService"
"BaseSectionExtractionService" <|-- "SeasonTextSectionExtractionService"
"BaseSectionExtractionService" <|-- "CircuitSectionExtractionService"
"ABC" <|-- "BaseSectionExtractionService"
"ValidatingSectionServiceFactory" <|-- "ConfigurableSectionServiceFactory"
"Generic" <|-- "ConfigurableSectionServiceFactory"
"ABC" <|-- "SectionServiceFactoryABC"
"Generic" <|-- "SectionServiceFactoryABC"
"Generic" <|-- "ValidatingSectionServiceFactory"
"ABC" <|-- "InfoboxExtractorProtocol"
"Generic" <|-- "InfoboxExtractorProtocol"
"ABC" <|-- "HasTableParserABC"
"ABC" <|-- "HasTableMapperABC"
"Protocol" <|-- "ListScraperConfigProtocol"
"Protocol" <|-- "DiscoveredListScraperClassProtocol"
"Protocol" <|-- "DiscoveredRunnerProtocol"
"Protocol" <|-- "DiscoveredRunnerClassProtocol"
"Protocol" <|-- "FetchCapability"
"Protocol" <|-- "ValidateCapability"
"Protocol" <|-- "ExportCapability"
"Protocol" <|-- "DataFrameFormatterProtocol"
"Protocol" <|-- "FieldnamesStrategyProtocol"
"SectionTableParseMixin" <|-- "DeclarativeSectionTableParseMixin"
"Extractor" <|-- "TableExtractor"
"SectionTraversalMixin" <|-- "ListScraper"
"WikiScraper" <|-- "ListScraper"
"ABC" <|-- "ListScraper"
"IndianapolisOnlyMixin" <|-- "IndianapolisOnlyListScraper"
"ListScraper" <|-- "IndianapolisOnlyListScraper"
"RuntimeError" <|-- "MissingSectionError"
"str" <|-- "ErrorBehavior"
"Enum" <|-- "ErrorBehavior"
"ScraperError" <|-- "DomainParseError"
"ScraperError" <|-- "ScraperValidationError"
"ScraperError" <|-- "ScraperNetworkError"
"str" <|-- "ErrorCategory"
"Enum" <|-- "ErrorCategory"
"ScraperError" <|-- "ScraperParseError"
"TypedDict" <|-- "ScraperErrorPayload"
"ScraperError" <|-- "ScraperNotFoundError"
"RuntimeError" <|-- "ScraperError"
"PipelineError" <|-- "SourceParseError"
"PipelineError" <|-- "ValidationError"
"PipelineError" <|-- "TransportError"
"ScraperError" <|-- "PipelineError"
"RecordTransformer" <|-- "NormalizeLinksTransformer"
"RecordTransformer" <|-- "PointsScoringSystemsHistoryTransformer"
"RecordTransformer" <|-- "RecordFactoryTransformer"
"RecordTransformer" <|-- "DriversChampionshipsTransformer"
"RecordTransformer" <|-- "FailedToMakeRestartTransformer"
"RecordTransformer" <|-- "ShortenedRacePointsTransformer"
"RecordTransformer" <|-- "FatalitiesCarTransformer"
"ABC" <|-- "RecordTransformer"
"HtmlTagParserABC" <|-- "HtmlElementParserABC"
"ABC" <|-- "HtmlElementParserABC"
"Generic" <|-- "HtmlElementParserABC"
"ElementParserABC" <|-- "ListElementParserABC"
"ABC" <|-- "ListElementParserABC"
"Generic" <|-- "ListElementParserABC"
"ElementParserABC" <|-- "TableElementParserABC"
"ABC" <|-- "TableElementParserABC"
"Generic" <|-- "TableElementParserABC"
"ElementParserABC" <|-- "InfoboxElementParserABC"
"ABC" <|-- "InfoboxElementParserABC"
"Generic" <|-- "InfoboxElementParserABC"
"ElementParserABC" <|-- "SectionElementParserABC"
"ABC" <|-- "SectionElementParserABC"
"Generic" <|-- "SectionElementParserABC"
"ElementParserABC" <|-- "NavboxElementParserABC"
"ABC" <|-- "NavboxElementParserABC"
"Generic" <|-- "NavboxElementParserABC"
"ElementParserABC" <|-- "ReferencesElementParserABC"
"ABC" <|-- "ReferencesElementParserABC"
"Generic" <|-- "ReferencesElementParserABC"
"ElementParserABC" <|-- "ParagraphElementParserABC"
"ABC" <|-- "ParagraphElementParserABC"
"Generic" <|-- "ParagraphElementParserABC"
"ElementParserABC" <|-- "FigureElementParserABC"
"ABC" <|-- "FigureElementParserABC"
"Generic" <|-- "FigureElementParserABC"
"BaseHtmlElementParser" <|-- "ParagraphElementParser"
"ParagraphElementParserABC" <|-- "ParagraphElementParser"
"WikiNavboxParserABC" <|-- "NavboxElementParser"
"NavboxElementParserABC" <|-- "NavboxElementParser"
"ParserABC" <|-- "HtmlSoupParserABC"
"ABC" <|-- "HtmlSoupParserABC"
"Generic" <|-- "HtmlSoupParserABC"
"HtmlSoupParserABC" <|-- "SoupParserABC"
"ABC" <|-- "SoupParserABC"
"Generic" <|-- "SoupParserABC"
"WikiListElementParser" <|-- "PrivateerTeamsListParser"
"WikiSectionParserBase" <|-- "TeamLiveriesSectionParser"
"TableRowParsingMixin" <|-- "HtmlTableParser"
"SoupParserABC" <|-- "HtmlTableParser"
"ParserABC" <|-- "HtmlTagParserABC"
"ABC" <|-- "HtmlTagParserABC"
"Generic" <|-- "HtmlTagParserABC"
"HtmlTagParserABC" <|-- "TagParserABC"
"ABC" <|-- "TagParserABC"
"Generic" <|-- "TagParserABC"
"ABC" <|-- "MatchesMixin"
"WikiSectionParserABC" <|-- "SectionElementParser"
"SectionElementParserABC" <|-- "SectionElementParser"
"DriverOrderedTableMapper" <|-- "DriversListTableMapper"
"TableDomainMapperABC" <|-- "WikiTableBaseMapper"
"MatchesMixin" <|-- "WikiTableBaseMapper"
"RowMappingMixin" <|-- "WikiTableBaseMapper"
"GroupParsingMixin" <|-- "WikiTableBaseMapper"
"WikiTablePayloadTransformMixin" <|-- "WikiTableBaseMapper"
"WikiTablePayloadCollectMixin" <|-- "WikiTableBaseMapper"
"ABC" <|-- "WikiTableBaseMapper"
"ABC" <|-- "StructureParser"
"SectionParserABC" <|-- "SectionStructureParserABC"
"ABC" <|-- "SectionStructureParserABC"
"MappedWikiTableMapper" <|-- "StandingsTableMapper"
"ListElementParserABC" <|-- "WikiListParserABC"
"ABC" <|-- "WikiListParserABC"
"ParsingBundleProviderABC" <|-- "DriverInfoboxProviderABC"
"WikiListParserABC" <|-- "ListElementParser"
"ListElementParserABC" <|-- "ListElementParser"
"ABC" <|-- "RowMappingMixin"
"Generic" <|-- "RowMappingMixin"
"MapperABC" <|-- "TableMapperABC"
"ABC" <|-- "TableMapperABC"
"WikiTableParserABC" <|-- "TableElementParser"
"TableElementParserABC" <|-- "TableElementParser"
"WikiTableBaseMapper" <|-- "EngineRegulationTableMapper"
"ABC" <|-- "MapperABC"
"Generic" <|-- "MapperABC"
"WikiInfoboxParserABC" <|-- "InfoboxElementParser"
"InfoboxElementParserABC" <|-- "InfoboxElementParser"
"SafeParsingMixin" <|-- "CircuitEntitiesOrchestrator"
"WikiSectionParserBase" <|-- "SeasonStandingsParser"
"BaseRedFlaggedRacesTableMapper" <|-- "NonChampionshipsRacesTableMapper"
"InfoboxParserABC" <|-- "WikiInfoboxParserABC"
"InfoboxElementParserABC" <|-- "WikiInfoboxParserABC"
"ABC" <|-- "WikiInfoboxParserABC"
"ABC" <|-- "ParseGroupMixin"
"Generic" <|-- "ParseGroupMixin"
"ParseGroupMixin" <|-- "GroupParsingMixin"
"ABC" <|-- "GroupParsingMixin"
"WikiTableBaseMapper" <|-- "PointsScoringSystemsHistoryTableMapper"
"TableElementParserABC" <|-- "WikiTableParserABC"
"ABC" <|-- "WikiTableParserABC"
"WikiTableBaseMapper" <|-- "FormerConstructorsTableMapper"
"HtmlTagParserABC" <|-- "InfoboxParserABC"
"ABC" <|-- "InfoboxParserABC"
"HtmlTagParserABC" <|-- "InfoboxFieldParserABC"
"ABC" <|-- "InfoboxFieldParserABC"
"HtmlTagParserABC" <|-- "InfoboxCellParserABC"
"ABC" <|-- "InfoboxCellParserABC"
"ABC" <|-- "ParsingBundle"
"WikiSectionParserABC" <|-- "WikiSectionStructureParserABC"
"ABC" <|-- "WikiSectionStructureParserABC"
"WikiTableBaseMapper" <|-- "SeasonsTableMapper"
"WikiTableBaseMapper" <|-- "BaseRedFlaggedRacesTableMapper"
"HtmlSoupParserABC" <|-- "SectionParserABC"
"ABC" <|-- "SectionParserABC"
"SectionParserABC" <|-- "NestedSectionParserABC"
"ABC" <|-- "NestedSectionParserABC"
"NestedSectionParserABC" <|-- "SubSectionParserABC"
"ABC" <|-- "SubSectionParserABC"
"SubSectionParserABC" <|-- "SubSubSectionParserABC"
"ABC" <|-- "SubSubSectionParserABC"
"WikiTableBaseMapper" <|-- "EngineRestrictionsTableMapper"
"NavboxElementParserABC" <|-- "WikiNavboxParserABC"
"ABC" <|-- "WikiNavboxParserABC"
"WikiTableBaseMapper" <|-- "CurrentConstructorsTableMapper"
"ABC" <|-- "ParserABC"
"Generic" <|-- "ParserABC"
"WikiSectionParserABC" <|-- "SeasonSectionParserABC"
"ABC" <|-- "SeasonSectionParserABC"
"BaseRedFlaggedRacesTableMapper" <|-- "WorldChampionshipsRacesTableMapper"
"WikiFigureParserABC" <|-- "FigureElementParser"
"FigureElementParserABC" <|-- "FigureElementParser"
"WikiTableBaseMapper" <|-- "SprintPointsTableMapper"
"Generic" <|-- "ParseResult"
"FigureElementParserABC" <|-- "WikiFigureParserABC"
"TagParserABC" <|-- "WikiFigureParserABC"
"ABC" <|-- "WikiFigureParserABC"
"WikiTableBaseMapper" <|-- "MappedWikiTableMapper"
"WikiTableBaseMapper" <|-- "EngineManufacturersTableMapper"
"WikiTableBaseMapper" <|-- "ShortenedRacesPointsTableMapper"
"DriverInfoboxProviderABC" <|-- "DefaultDriverInfoboxProvider"
"ABC" <|-- "NestedChildParser"
"HtmlTagParserABC" <|-- "TableParserABC"
"ABC" <|-- "TableParserABC"
"HtmlTagParserABC" <|-- "TableRowParserABC"
"ABC" <|-- "TableRowParserABC"
"HtmlTagParserABC" <|-- "TableCellParserABC"
"ABC" <|-- "TableCellParserABC"
"MappedWikiTableMapper" <|-- "RaceResultsTableMapper"
"ParsingBundle" <|-- "DriverInfoboxBundle"
"ABC" <|-- "ParsingBundleProviderABC"
"Generic" <|-- "ParsingBundleProviderABC"
"MappedWikiTableMapper" <|-- "LapRecordsWikiTableMapper"
"SectionElementParserABC" <|-- "WikiSectionParserABC"
"ParserABC" <|-- "WikiSectionParserABC"
"ABC" <|-- "WikiSectionParserABC"
"ElementParserABC" <|-- "BaseHtmlElementParser"
"ABC" <|-- "BaseHtmlElementParser"
"ABC" <|-- "BaseHtmlSectionParser"
"Generic" <|-- "BaseHtmlSectionParser"
"ParserABC" <|-- "SoupParser"
"ABC" <|-- "SoupParser"
"Generic" <|-- "SoupParser"
"MapperABC" <|-- "TableDomainMapperABC"
"ABC" <|-- "TableDomainMapperABC"
"ParserABC" <|-- "SponsorPartsParser"
"RecordSplitStrategy" <|-- "GrandPrixSplitStrategy"
"RecordSplitStrategy" <|-- "PossessiveDriverColourSplitStrategy"
"RecordSplitStrategy" <|-- "DeduplicateRecordStrategy"
"RecordSplitStrategy" <|-- "SeasonSplitStrategy"
"ABC" <|-- "RecordSplitStrategy"
"ABC" <|-- "SplitRule"
"SplitRule" <|-- "HasMultipleSeasonsRule"
"SplitRule" <|-- "HasPossessiveColoursRule"
"SplitRule" <|-- "HasYearSpecificColoursRule"
"SplitRule" <|-- "HasYearSpecificSponsorsRule"
"ListElementParser" <|-- "IndianapolisConstructorsListParser"
"ListElementParser" <|-- "IndianapolisOnlyListParser"
"WikiFigureParserABC" <|-- "WikiFigureParser"
"MappedWikiTableMapper" <|-- "CircuitsListTableMapper"
"ABC" <|-- "ArticleTablesParserABC"
"BaseNestedSectionParser" <|-- "HistorySectionParser"
"ParagraphElementParser" <|-- "WikiParagraphParser"
"WikiElementParsingMixin" <|-- "SubSubSubSectionParser"
"WikiParser" <|-- "SubSubSubSectionParser"
"WikiTableBaseMapper" <|-- "DriverOrderedTableMapper"
"BaseNestedSectionParser" <|-- "NestedWikiSectionParser"
"SubSectionParser" <|-- "SpecialCasesSubSectionParser"
"ApplyForElementsMixin" <|-- "ShortenedRacesSubSubSectionParser"
"SubSubSectionParser" <|-- "ShortenedRacesSubSubSectionParser"
"WikiParser" <|-- "BodyContentAssembler"
"WikiListParserABC" <|-- "WikiListElementParser"
"DomainMapperABC" <|-- "IdentityDomainMapper"
"WikiNavboxParserABC" <|-- "WikiNavboxElementParser"
"SubSectionParser" <|-- "NonChampionshipsRacesSubSectionParser"
"ReferencesWrapParser" <|-- "WikiReferencesElementParser"
"ReferencesElementParserABC" <|-- "WikiReferencesElementParser"
"NestedWikiSectionParser" <|-- "RedFlaggedRacesSectionParser"
"ApplyForElementsMixin" <|-- "SprintRacesSubSubSectionParser"
"SubSubSectionParser" <|-- "SprintRacesSubSubSectionParser"
"WikiNavboxParserABC" <|-- "WikiNavboxParser"
"WikiParser" <|-- "CategoryLinksParser"
"WikiInfoboxHtmlParser" <|-- "WikiInfoboxParser"
"NestedWikiSectionParser" <|-- "DriversListSectionParser"
"NestedWikiSectionParser" <|-- "PrivateerTeamsSectionParser"
"SubSectionParser" <|-- "EngineRegulationSubSectionParser"
"WikiInfoboxParserABC" <|-- "WikiInfoboxElementParser"
"NestedWikiSectionParser" <|-- "SeasonsSectionParser"
"WikiParser" <|-- "HeaderParser"
"RecursiveSectionParser" <|-- "BaseNestedSectionParser"
"WikiSectionParserABC" <|-- "BaseNestedSectionParser"
"WikiSectionParserABC" <|-- "BaseSectionParser"
"ApplyForElementsMixin" <|-- "PointsScoringSystemsSectionParser"
"NestedWikiSectionParser" <|-- "PointsScoringSystemsSectionParser"
"SubSubSectionParser" <|-- "SpecialCasesSubSubSectionRouter"
"BaseNestedSectionParser" <|-- "CurrentRulesSectionParser"
"WikiTableParserABC" <|-- "WikiTableElementParser"
"WikiParser" <|-- "ContentTextParser"
"ApplyForElementsMixin" <|-- "EngineSubSectionParser"
"SubSectionParser" <|-- "EngineSubSectionParser"
"WikiFigureParserABC" <|-- "WikiFigureElementParser"
"WikiElementParsingMixin" <|-- "RecursiveSectionParser"
"WikiParser" <|-- "RecursiveSectionParser"
"WikiSectionParserBase" <|-- "SponsorshipSectionParser"
"ParagraphElementParser" <|-- "WikiParagraphElementParser"
"WikiSectionStructureParserABC" <|-- "WikiSectionElementParser"
"SubSectionParser" <|-- "EngineManufacturersIndianapolisSubSectionParser"
"ApplyForElementsMixin" <|-- "EngineManufacturersSectionParser"
"NestedWikiSectionParser" <|-- "EngineManufacturersSectionParser"
"WikiParser" <|-- "ReferencesWrapParser"
"ParserABC" <|-- "WikiParser"
"ABC" <|-- "WikiParser"
"Generic" <|-- "WikiParser"
"SoupParserABC" <|-- "WikiSectionParserBase"
"ABC" <|-- "WikiSectionParserBase"
"SoupParserABC" <|-- "WikiTableElementParserBase"
"ABC" <|-- "WikiTableElementParserBase"
"TagParserABC" <|-- "WikiListParser"
"ABC" <|-- "WikiListParser"
"TagParserABC" <|-- "WikiTagParser"
"ABC" <|-- "WikiTagParser"
"Generic" <|-- "WikiTagParser"
"BaseSeasonParser" <|-- "ColinChapmanTrophyParser"
"BaseSeasonParser" <|-- "SeasonNonChampionshipParser"
"BaseSeasonParser" <|-- "SeasonEntriesParser"
"BaseSeasonParser" <|-- "CancelledRoundsParser"
"BaseSeasonParser" <|-- "SeasonFreePracticeParser"
"BaseSeasonParser" <|-- "TestingVenuesParser"
"BaseSeasonParser" <|-- "SeasonCalendarParser"
"BaseSeasonParser" <|-- "SeasonResultsParser"
"BaseSeasonParser" <|-- "SeasonScoringSystemParser"
"BaseSeasonParser" <|-- "JimClarkTrophyParser"
"BaseSeasonParser" <|-- "SeasonRegionalChampionshipParser"
"WikiTableElementParserBase" <|-- "BaseSeasonParser"
"ABC" <|-- "BaseSeasonParser"
"BaseNestedSectionParser" <|-- "SubSectionParser"
"BaseNestedSectionParser" <|-- "SubSubSectionParser"
"SubSectionParser" <|-- "GenericIndianapolisOnlySubSectionParser"
"WikiTableParserABC" <|-- "WikiTableHtmlParser"
"WikiTableElementParserBase" <|-- "ArticleTablesParser"
"ArticleTablesParserABC" <|-- "ArticleTablesParser"
"TableParserABC" <|-- "WikiTableBaseParser"
"ABC" <|-- "WikiTableBaseParser"
"ExtractListItemsMixin" <|-- "SeasonRegulationChangesSectionParser"
"BaseSectionParser" <|-- "SeasonRegulationChangesSectionParser"
"ExtractListItemsMixin" <|-- "SeasonMidSeasonChangesSectionParser"
"BaseSectionParser" <|-- "SeasonMidSeasonChangesSectionParser"
"BaseSectionParser" <|-- "BaseDriverResultsSectionParser"
"BaseSectionParser" <|-- "SeasonResultsSectionParser"
"BaseSectionParser" <|-- "GrandPrixByYearSectionParser"
"BaseSectionParser" <|-- "SeasonCalendarSectionParser"
"HtmlTagParserABC" <|-- "F1StandingsTableParser"
"BaseSectionParser" <|-- "SeasonConstructorsStandingsSectionParser"
"BaseSectionParser" <|-- "SeasonDriversStandingsSectionParser"
"TableSectionParser" <|-- "DriverResultsSectionParser"
"BaseSectionParser" <|-- "TableSectionParser"
"ConstructorTablesSectionParser" <|-- "ConstructorHistorySectionParser"
"BaseSectionParser" <|-- "ConstructorTablesSectionParser"
"ConstructorTablesSectionParser" <|-- "ConstructorChampionshipResultsSectionParser"
"ConstructorTablesSectionParser" <|-- "ConstructorCompleteF1ResultsSectionParser"
"TableSectionParser" <|-- "CircuitEventsSectionParser"
"TableSectionParser" <|-- "CircuitLapRecordsSectionParser"
"ConstructorsSectionParser" <|-- "CurrentConstructorsSectionParser"
"ConstructorsSectionParser" <|-- "FormerConstructorsSectionParser"
"BaseSectionParser" <|-- "ConstructorsSectionParser"
"BaseSectionParser" <|-- "CircuitsListSectionParser"
"BaseSectionParser" <|-- "CircuitLayoutHistorySectionParser"
"WikiInfoboxParserABC" <|-- "DriverInfoboxParser"
"WikiInfoboxParserABC" <|-- "WikiInfoboxHtmlParser"
"InfoboxCellParserABC" <|-- "InfoboxCellValueExtractor"
"WikiInfoboxParserABC" <|-- "CircuitInfoboxParser"
"InfoboxFieldParser" <|-- "BestFinishParser"
"InfoboxFieldParser" <|-- "InfoboxCareerParser"
"InfoboxFieldParser" <|-- "NationalityParser"
"InfoboxFieldParserABC" <|-- "InfoboxFieldParser"
"ABC" <|-- "InfoboxFieldParser"
"Generic" <|-- "InfoboxFieldParser"
"InfoboxFieldParser" <|-- "LicenceParser"
"InfoboxFieldParser" <|-- "CallableInfoboxFieldParser"
"Generic" <|-- "CallableInfoboxFieldParser"
"InfoboxFieldParser" <|-- "RaceEventParser"
"InfoboxFieldParser" <|-- "InfoboxTitlesParser"
"InfoboxFieldParser" <|-- "FinishedSeasonParser"
"InfoboxFieldParser" <|-- "ChampionshipsParser"
"InfoboxFieldParser" <|-- "YearParser"
"InfoboxFieldParser" <|-- "CarNumbersParser"
"InfoboxFieldParser" <|-- "ActiveYearsParser"
"InfoboxFieldParser" <|-- "TeamsParser"
"InfoboxTextUtils" <|-- "CircuitSpecsExtractor"
"SafeParsingMixin" <|-- "CircuitLayoutsExtractor"
"InfoboxTextUtils" <|-- "CircuitHistoryExtractor"
"CircuitTextProcessing" <|-- "CircuitLapRecordExtractor"
"InfoboxTextUtils" <|-- "CircuitGeoExtractor"
"InfoboxTextUtils" <|-- "CircuitTextProcessing"
"CircuitEntityExtractor" <|-- "CircuitAdditionalInfoExtractor"
"CircuitTextProcessing" <|-- "CircuitEntityExtractor"
"BaseRecordAssembler" <|-- "ConstructorRecordAssembler"
"BaseRecordAssembler" <|-- "CircuitRecordAssembler"
"BaseRecordAssembler" <|-- "SeasonRecordAssembler"
"RowMappingMixin" <|-- "TableRecordMapper"
"GroupParsingMixin" <|-- "TableRecordMapper"
"ABC" <|-- "SeasonWikiTableParserABC"
"SeasonWikiTableParserABC" <|-- "SeasonStandingsWikiTableParser"
"SeasonWikiTableParserABC" <|-- "SeasonGenericWikiTableParser"
"BaseComponent" <|-- "BaseOrchestrator"
"BaseComponent" <|-- "BaseParsingStage"
"BaseComponent" <|-- "BaseNormalizer"
"BaseComponent" <|-- "BaseExtractor"
"Protocol" <|-- "PipelineStage"
"WikiScraper" <|-- "ArticleScraperBase"
"ABC" <|-- "ArticleScraperBase"
"ArticleScraperBase" <|-- "DomainArticleScraperBase"
"ABC" <|-- "DomainArticleScraperBase"
"SectionAwareMixin" <|-- "SectionByIdScraperBase"
"DomainArticleScraperBase" <|-- "SectionByIdScraperBase"
"ABC" <|-- "SectionByIdScraperBase"
"SectionAdapter" <|-- "SectionAdapterScraperBase"
"SectionAwareMixin" <|-- "SectionAdapterScraperBase"
"DomainArticleScraperBase" <|-- "SectionAdapterScraperBase"
"ABC" <|-- "SectionAdapterScraperBase"
"MetadataBindingMixin" <|-- "SectionMetadataBindingMixin"
"SectionSelectionStrategy" <|-- "WikipediaSectionByIdSelectionStrategy"
"InfoboxExtractorProtocol" <|-- "CircuitInfoboxExtractor"
"Protocol" <|-- "InfoboxSectionDiscovery"
"Protocol" <|-- "StageValidator"
"ABC" <|-- "RecordValidator"
"RecordValidator" <|-- "CompositeRecordValidator"
"Protocol" <|-- "RecordFactoryValidatorProtocol"
"Protocol" <|-- "ValidationRuleProtocol"
"CompositeDataExtractor" <|-- "CompleteExtractorBase"
"str" <|-- "EntityName"
"int" <|-- "SeasonYear"
"Protocol" <|-- "SerializableProtocol"
"str" <|-- "SectionId"
"str" <|-- "WikiUrl"
"Protocol" <|-- "SerializerProtocol"
"TypedDict" <|-- "WikiParsedPayload"
"TypedDict" <|-- "CategoryLinkItem"
"TypedDict" <|-- "CategoryGroup"
"Protocol" <|-- "RecordContract"
"DataContract" <|-- "PointsContract"
"DataContract" <|-- "DriverContract"
"DataContract" <|-- "CircuitContract"
"MutableMapping" <|-- "DataContract"
"ValidatedModel" <|-- "Circuit"
"ValidatedModel" <|-- "EngineRegulation"
"ValidatedModel" <|-- "EngineManufacturer"
"ValidatedModel" <|-- "EngineRestriction"
"TypedDict" <|-- "RichCellData"
"TypedDict" <|-- "FigureParsedData"
"TypedDict" <|-- "ParagraphParsedData"
"TypedDict" <|-- "ListParsedData"
"TypedDict" <|-- "CategoryLinksParsedData"
"TypedDict" <|-- "InfoboxParsedData"
"TypedDict" <|-- "HeaderParsedData"
"TypedDict" <|-- "TableParsedData"
"TypedDict" <|-- "ReferencesWrapParsedData"
"TypedDict" <|-- "NavBoxParsedData"
"TypedDict" <|-- "ParagraphElementData"
"TypedDict" <|-- "FigureElementData"
"TypedDict" <|-- "ListElementData"
"TypedDict" <|-- "InfoboxRowData"
"TypedDict" <|-- "InfoboxElementData"
"TypedDict" <|-- "NavboxLinkData"
"TypedDict" <|-- "NavboxElementData"
"TypedDict" <|-- "TableElementData"
"TypedDict" <|-- "SectionElementData"
"TypedDict" <|-- "WikiFigureData"
"TypedDict" <|-- "WikiSectionData"
"TypedDict" <|-- "WikiListData"
"TypedDict" <|-- "WikiNavboxData"
"TypedDict" <|-- "WikiInfoboxData"
"TypedDict" <|-- "WikiTableData"
"TypedDict" <|-- "WikiNavboxLinkData"
"ValueObject" <|-- "DriversChampionships"
"ValueObject" <|-- "Link"
"ValueObject" <|-- "SeasonRef"
"TypedDict" <|-- "UnitValue"
"ABC" <|-- "ValueObject"
"ValueObject" <|-- "NormalizedDate"
"ValueObject" <|-- "DateValue"
"TypedDict" <|-- "SeasonSummaryRecord"
"TypedDict" <|-- "FatalityRecord"
"TypedDict" <|-- "EngineManufacturerRecord"
"TypedDict" <|-- "DriverSummaryRecord"
"TypedDict" <|-- "SpecialDriverRecord"
"TypedDict" <|-- "GrandsPrixRecord"
"TypedDict" <|-- "ConstructorSummaryRecord"
"TypedDict" <|-- "HasLinkRecord"
"TypedDict" <|-- "HasSeasonsRecord"
"TypedDict" <|-- "HasStatsRecord"
"TypedDict" <|-- "HasStatusRecord"
"TypedDict" <|-- "HasLocationRecord"
"TypedDict" <|-- "LinkRecord"
"TypedDict" <|-- "EventRecord"
"TypedDict" <|-- "DriversChampionshipsRecord"
"LinkRecord" <|-- "CarRecord"
"str" <|-- "RecordType"
"Enum" <|-- "RecordType"
"TypedDict" <|-- "SeasonRecord"
"BaseRecordFactory" <|-- "SeasonSummaryRecordFactory"
"BaseRecordFactory" <|-- "FatalityRecordFactory"
"BaseRecordFactory" <|-- "EngineManufacturerRecordFactory"
"BaseRecordFactory" <|-- "DriverRecordFactory"
"BaseRecordFactory" <|-- "SpecialDriverRecordFactory"
"Protocol" <|-- "RecordBuilder"
"BaseRecordFactory" <|-- "ConstructorRecordFactory"
"BaseRecordFactory" <|-- "GrandsPrixRecordFactory"
"BaseRecordFactory" <|-- "DriversChampionshipsRecordFactory"
"BaseRecordFactory" <|-- "EventRecordFactory"
"BaseRecordFactory" <|-- "CarRecordFactory"
"BaseRecordFactory" <|-- "CircuitRecordFactory"
"BaseRecordFactory" <|-- "SeasonRecordFactory"
"LinkNormalizationMixin" <|-- "BaseRecordFactory"
"SeasonNormalizationMixin" <|-- "BaseRecordFactory"
"StatusNormalizationMixin" <|-- "BaseRecordFactory"
"LocationNormalizationMixin" <|-- "BaseRecordFactory"
"TypedDict" <|-- "FactorySpec"
"ValueError" <|-- "FactoryRegistryError"
"CircuitBaseRecord" <|-- "CircuitCompleteRecord"
"CircuitBaseRecord" <|-- "CircuitDetailsRecord"
"TypedDict" <|-- "CircuitSummaryRecord"
"TypedDict" <|-- "CircuitBaseRecord"
"NodeVisitor" <|-- "DependencyCreationVisitor"
"NodeVisitor" <|-- "ComplexityVisitor"
"NodeVisitor" <|-- "StructuralVisitor"
"str" <|-- "CiStatus"
"Enum" <|-- "CiStatus"
"NamedTuple" <|-- "WikiPipelineComponents"
"Protocol" <|-- "ExporterProtocol"
"RecordAssemblyStrategy" <|-- "ExtractDetailFieldStrategy"
"RecordAssemblyStrategy" <|-- "AttachDetailsStrategy"
"RecordAssemblyStrategy" <|-- "BundleRecordWithDetailsStrategy"
"ABC" <|-- "RecordAssemblyStrategy"
"LayerZeroRunConfigFactory" <|-- "DefaultLayerZeroRunConfigFactory"
"Protocol" <|-- "LayerZeroRunConfigFactoryProtocol"
"LayerZeroRunConfigFactory" <|-- "SponsorshipLiveriesRunConfigFactory"
"LayerZeroRunConfigFactory" <|-- "StaticScraperKwargsFactory"
"LayerZeroRunConfigFactoryProtocol" <|-- "LayerZeroRunConfigFactory"
"ABC" <|-- "LayerZeroRunConfigFactory"
"Protocol" <|-- "LayerZeroJobHook"
"Protocol" <|-- "LayerOneRunnerProtocol"
"Protocol" <|-- "LayerExecutorProtocol"
"Protocol" <|-- "MergeModel"
"Protocol" <|-- "LayerZeroMergeServiceProtocol"
"BaseRegistryEntry" <|-- "ListJobRegistryEntry"
"BaseRegistryEntry" <|-- "SeedRegistryEntry"
"TypedDict" <|-- "RunnerMetadata"
"LayerJobRunner" <|-- "FunctionExportRunner"
"LayerJobRunner" <|-- "GrandPrixRunner"
"ABC" <|-- "LayerJobRunner"
"BaseExecutor" <|-- "LayerOneExecutor"
"BaseExecutor" <|-- "LayerZeroExecutor"
@enduml
