@startuml

hide circle
hide empty members


abstract class RecordAssemblyStrategy

class AttachDetailsStrategy
class BundleRecordWithDetailsStrategy
class ExtractDetailFieldStrategy


RecordAssemblyStrategy <|-- AttachDetailsStrategy
RecordAssemblyStrategy <|-- BundleRecordWithDetailsStrategy
RecordAssemblyStrategy <|-- ExtractDetailFieldStrategy

@enduml
