DRIVER_NAME_HEADER = "Driver name"
NATIONALITY_HEADER = "Nationality"
SEASONS_COMPETED_HEADER = "Seasons competed"
DRIVERS_CHAMPIONSHIPS_HEADER = "Drivers' Championships"
RACE_ENTRIES_HEADER = "Race entries"
RACE_STARTS_HEADER = "Race starts"
POLE_POSITIONS_HEADER = "Pole positions"
RACE_WINS_HEADER = "Race wins"
PODIUMS_HEADER = "Podiums"
FASTEST_LAPS_HEADER = "Fastest laps"
POINTS_HEADER = "Points"

DRIVERS_LIST_HEADERS = [
    DRIVER_NAME_HEADER,
    NATIONALITY_HEADER,
    SEASONS_COMPETED_HEADER,
    DRIVERS_CHAMPIONSHIPS_HEADER,
]

FATALITIES_SECTION_ID = "Detail_by_driver"
FATALITIES_DRIVER_HEADER = "Driver"
FATALITIES_DATE_HEADER = "Date of accident"
FATALITIES_AGE_HEADER = "Age"
FATALITIES_EVENT_HEADER = "Event"
FATALITIES_CIRCUIT_HEADER = "Circuit"
FATALITIES_CAR_HEADER = "Car"
FATALITIES_SESSION_HEADER = "Session"
FATALITIES_REF_HEADER = "Ref."  # Skrót od przypisów w tabeli.
FATALITIES_HEADERS = [
    FATALITIES_DRIVER_HEADER,
    FATALITIES_DATE_HEADER,
    FATALITIES_AGE_HEADER,
    FATALITIES_EVENT_HEADER,
    FATALITIES_CIRCUIT_HEADER,
    FATALITIES_CAR_HEADER,
    FATALITIES_SESSION_HEADER,
]

FEMALE_DRIVERS_SECTION_ID = "Official_drivers"
FEMALE_DRIVER_NAME_HEADER = "Name"
FEMALE_DRIVER_SEASONS_HEADER = "Seasons"
FEMALE_DRIVER_TEAMS_HEADER = "Teams"
FEMALE_DRIVER_ENTRIES_STARTS_HEADER = "Entries (starts)"  # Łączone wpisy i starty.
FEMALE_DRIVER_POINTS_HEADER = "Points"
FEMALE_DRIVERS_HEADERS = [
    FEMALE_DRIVER_NAME_HEADER,
    FEMALE_DRIVER_SEASONS_HEADER,
    FEMALE_DRIVER_TEAMS_HEADER,
    FEMALE_DRIVER_ENTRIES_STARTS_HEADER,
    FEMALE_DRIVER_POINTS_HEADER,
]

INDEX_HEADER = "#"

MARK_ACTIVE_DRIVER = "~"  # Wiki oznacza aktywnego kierowcę.
MARK_ACTIVE_DRIVER_ALT = "*"  # Alternatywny znacznik aktywnego kierowcy w tabelach.
MARK_WORLD_CHAMPION = "^"  # Wiki oznacza mistrza świata.
MARK_F2_CATEGORY = "#"  # Symbol wiki wskazujący start w F2.
MARK_NON_CHAMPIONSHIP_EVENT = "†"  # Symbol wiki oznacza event poza cyklem mistrzostw.
