@startuml
title Parser ABC – Core Contracts & HTML Layer
skinparam classAttributeIconSize 0
hide empty members
hide circle

class ContentTextParser
class HeaderParser
abstract class HtmlSoupParserABC
abstract class HtmlTagParserABC
abstract class InfoboxParserABC
abstract class ParserABC
abstract class SectionInfoboxesHtmlParserABC
abstract class SectionListsHtmlParserABC
abstract class SectionTablesHtmlParserABC
abstract class SectionTextBlocksHtmlParserABC
class SoupParser

ParserABC <|-- ContentTextParser
ParserABC <|-- HeaderParser
ParserABC <|-- HtmlSoupParserABC
ParserABC <|-- HtmlTagParserABC
HtmlTagParserABC <|-- InfoboxParserABC
HtmlSoupParserABC <|-- SectionInfoboxesHtmlParserABC
HtmlSoupParserABC <|-- SectionListsHtmlParserABC
HtmlSoupParserABC <|-- SectionTablesHtmlParserABC
HtmlSoupParserABC <|-- SectionTextBlocksHtmlParserABC
ParserABC <|-- SoupParser

@enduml
