@startuml
title Wiki HTML Parser Hierarchy
skinparam classAttributeIconSize 0
hide empty members
hide circle

abstract class WikiArticleParserABC
abstract class WikiArticleParserBase
abstract class WikiDelegatingHtmlParserBase
abstract class WikiFigureElementParserABC
abstract class WikiFigureParserBase
abstract class WikiInfoboxElementParserABC
abstract class WikiInfoboxParserBase
abstract class WikiListElementParserABC
abstract class WikiListParserBase
abstract class WikiNavboxElementParserABC
abstract class WikiNavboxParserBase
abstract class WikiParagraphElementParserABC
abstract class WikiParagraphParserBase
class WikiReferencesElementParser
abstract class WikiReferencesElementParserABC
abstract class WikiReferencesParserBase
abstract class WikiSectionElementParserABC
abstract class WikiSectionParserBase
abstract class WikiTableElementParserABC
abstract class WikiTableElementParserBase
abstract class WikiTableParserBase

WikiArticleParserABC <|-- WikiArticleParserBase
WikiDelegatingHtmlParserBase <|-- WikiArticleParserBase
WikiDelegatingHtmlParserBase <|-- WikiFigureParserBase
WikiFigureElementParserABC <|-- WikiFigureParserBase
WikiDelegatingHtmlParserBase <|-- WikiInfoboxParserBase
WikiInfoboxElementParserABC <|-- WikiInfoboxParserBase
WikiDelegatingHtmlParserBase <|-- WikiListParserBase
WikiListElementParserABC <|-- WikiListParserBase
WikiDelegatingHtmlParserBase <|-- WikiNavboxParserBase
WikiNavboxElementParserABC <|-- WikiNavboxParserBase
WikiDelegatingHtmlParserBase <|-- WikiParagraphParserBase
WikiParagraphElementParserABC <|-- WikiParagraphParserBase
WikiReferencesParserBase <|-- WikiReferencesElementParser
WikiDelegatingHtmlParserBase <|-- WikiReferencesParserBase
WikiReferencesElementParserABC <|-- WikiReferencesParserBase
WikiDelegatingHtmlParserBase <|-- WikiTableParserBase
WikiTableElementParserABC <|-- WikiTableParserBase

@enduml