@startuml
title Wiki HTML Parser Hierarchy
skinparam classAttributeIconSize 0
hide empty members
hide circle

class CircuitInfoboxParser
class DriverInfoboxParser
class FigureElementParser
abstract class HtmlSoupParserABC
abstract class HtmlTagParserABC
class InfoboxElementParser
class ListElementParser
class NavboxElementParser
class SectionElementParser
class WikiFigureElementParser
abstract class WikiFigureElementParserABC
class WikiFigureParser
class WikiInfoboxElementParser
abstract class WikiInfoboxElementParserABC
class WikiInfoboxHtmlParser
class WikiNavboxElementParser
class WikiNavboxParser
class WikiParagraphElementParser
class WikiReferencesElementParser
class WikiSectionElementParser

WikiInfoboxElementParserABC <|-- CircuitInfoboxParser
WikiInfoboxElementParserABC <|-- DriverInfoboxParser
WikiFigureElementParserABC <|-- FigureElementParser
WikiInfoboxElementParserABC <|-- InfoboxElementParser
HtmlTagParserABC <|-- ListElementParser
HtmlTagParserABC <|-- NavboxElementParser
HtmlSoupParserABC <|-- SectionElementParser
WikiFigureElementParserABC <|-- WikiFigureElementParser
WikiFigureElementParserABC <|-- WikiFigureParser
WikiInfoboxElementParserABC <|-- WikiInfoboxElementParser
WikiInfoboxElementParserABC <|-- WikiInfoboxHtmlParser
HtmlTagParserABC <|-- WikiNavboxElementParser
HtmlTagParserABC <|-- WikiNavboxParser
HtmlTagParserABC <|-- WikiParagraphElementParser
HtmlTagParserABC <|-- WikiReferencesElementParser
HtmlSoupParserABC <|-- WikiSectionElementParser

@enduml
