@startuml
title Wiki HTML Parser Hierarchy
skinparam classAttributeIconSize 0
hide empty members
hide circle

abstract class WikiArticleParserABC
abstract class WikiArticleParserBase
abstract class WikiDelegatingHtmlParserBase
abstract class WikiDocumentParserABC
abstract class WikiFigureElementParserABC
abstract class WikiFigureParserABC
abstract class WikiFigureParserBase
abstract class WikiInfoboxElementParserABC
abstract class WikiInfoboxParserABC
abstract class WikiInfoboxParserBase
abstract class WikiListElementParserABC
abstract class WikiListParserABC
abstract class WikiListParserBase
abstract class WikiNavboxElementParserABC
abstract class WikiNavboxParserABC
abstract class WikiNavboxParserBase
abstract class WikiParagraphElementParserABC
abstract class WikiParagraphParserABC
abstract class WikiParagraphParserBase
class WikiReferencesElementParser
abstract class WikiReferencesElementParserABC
abstract class WikiReferencesParserBase
abstract class WikiSectionElementParserABC
abstract class WikiSectionParserBase
abstract class WikiSectionStructureParserABC
abstract class WikiSoupParserABC
abstract class WikiTableElementParserABC
abstract class WikiTableElementParserBase
abstract class WikiTableParserABC
abstract class WikiTableParserBase
abstract class WikiTagParserABC

WikiSoupParserABC <|-- WikiArticleParserABC
WikiArticleParserABC <|-- WikiArticleParserBase
WikiDelegatingHtmlParserBase <|-- WikiArticleParserBase
WikiSectionElementParserABC <|-- WikiDocumentParserABC
WikiTagParserABC <|-- WikiFigureElementParserABC
WikiFigureElementParserABC <|-- WikiFigureParserABC
WikiListParserABC <|-- WikiFigureParserABC
WikiDelegatingHtmlParserBase <|-- WikiFigureParserBase
WikiFigureElementParserABC <|-- WikiFigureParserBase
WikiTagParserABC <|-- WikiInfoboxElementParserABC
WikiInfoboxElementParserABC <|-- WikiInfoboxParserABC
WikiListParserABC <|-- WikiInfoboxParserABC
WikiDelegatingHtmlParserBase <|-- WikiInfoboxParserBase
WikiInfoboxElementParserABC <|-- WikiInfoboxParserBase
WikiTagParserABC <|-- WikiListElementParserABC
WikiListElementParserABC <|-- WikiListParserABC
WikiDelegatingHtmlParserBase <|-- WikiListParserBase
WikiListElementParserABC <|-- WikiListParserBase
WikiTagParserABC <|-- WikiNavboxElementParserABC
WikiListParserABC <|-- WikiNavboxParserABC
WikiNavboxElementParserABC <|-- WikiNavboxParserABC
WikiDelegatingHtmlParserBase <|-- WikiNavboxParserBase
WikiNavboxElementParserABC <|-- WikiNavboxParserBase
WikiTagParserABC <|-- WikiParagraphElementParserABC
WikiListParserABC <|-- WikiParagraphParserABC
WikiParagraphElementParserABC <|-- WikiParagraphParserABC
WikiDelegatingHtmlParserBase <|-- WikiParagraphParserBase
WikiParagraphElementParserABC <|-- WikiParagraphParserBase
WikiReferencesParserBase <|-- WikiReferencesElementParser
WikiTagParserABC <|-- WikiReferencesElementParserABC
WikiDelegatingHtmlParserBase <|-- WikiReferencesParserBase
WikiReferencesElementParserABC <|-- WikiReferencesParserBase
WikiSoupParserABC <|-- WikiSectionElementParserABC
WikiSectionElementParserABC <|-- WikiSectionStructureParserABC
WikiTagParserABC <|-- WikiTableElementParserABC
WikiListParserABC <|-- WikiTableParserABC
WikiTableElementParserABC <|-- WikiTableParserABC
WikiDelegatingHtmlParserBase <|-- WikiTableParserBase
WikiTableElementParserABC <|-- WikiTableParserBase

@enduml