@startuml
title Scraper Hierarchy
skinparam classAttributeIconSize 0
hide empty members
hide circle

abstract class ArticleScraperBase
class ArticleSectionTablesHtmlParser
class ArticleTablesParser
abstract class ArticleTablesParserABC
abstract class SectionTablesHtmlParserABC
abstract class BaseConstructorListScraper
abstract class BaseEngineTableScraper
class BodyContentAssembler
class ByRaceTitleSubSectionParser
class CircuitsListScraper
class ConstructorsListScraper
class CurrentRulesSectionParser
abstract class DeclarativeSectionTableParseMixin
class DetailByDriverSubSectionParser
class DriversListSectionParser
class DriversSectionParser
class EngineManufacturersIndianapolisSubSectionParser
class EngineManufacturersListScraper
class EngineManufacturersSectionParser
class EngineRegulationScraper
class EngineRegulationSubSectionParser
class EngineRestrictionsScraper
class EngineSubSectionParser
class F1DriversListScraper
class F1FatalitiesListScraper
class F1SingleCircuitScraper
class F1SingleGrandPrixScraper
class F1SponsorshipLiveriesScraper
class F1StandingsScraper
abstract class F1TableScraper
class FatalitiesSectionParser
class FemaleDriversListScraper
abstract class FetchOrchestrationMixin
class GenericIndianapolisOnlySubSectionParser
class GrandsPrixListScraper
class HistorySectionParser
abstract class IndianapolisOnlyMixin
class IndianapolisOnlyListScraper
class LapRecordsTableScraper
class ListScraper
class ManufacturersSectionParser
class NestedWikiSectionParser
abstract class NestedSectionHandlingMixin
class NonChampionshipsRacesSubSectionParser
class OfficialDriversSubSectionParser
class PointsScoringSystemsSectionParser
class PointsScraper
class PointsScraper
class PrivateerTeamsSectionParser
class RacesSectionParser
class RecursiveSectionParser
class RedFlaggedRacesBaseScraper
class RedFlaggedRacesScraper
class RedFlaggedRacesSectionParser
class SeasonsListScraper
class SeasonsSectionParser
class SectionAdapter
abstract class SectionAdapterScraperBase
abstract class SectionAwareMixin
abstract class SectionByIdScraperBase
class SectionTraversalMixin
class SeedListTableScraper
class ShortenedRacesSubSubSectionParser
class SingleConstructorScraper
class SingleDriverScraper
class SingleEngineManufacturerScraper
class SingleSeasonScraper
class SpecialCasesSubSectionParser
class SpecialCasesSubSubSectionRouter
class SprintRacesSubSubSectionParser
class SubSectionParser
class SubSubSectionParser
class SubSubSubSectionParser
class TyreManufacturersBySeasonSubSectionParser
class TyreManufacturersScraper
abstract class WikiElementParsingMixin
abstract class WikiScraper

FetchOrchestrationMixin <|-- WikiScraper
WikiElementParsingMixin <|-- WikiScraper
WikiScraper <|-- ArticleScraperBase
ArticleTablesParserABC <|-- ArticleTablesParser
DeclarativeSectionTableParseMixin <|-- BaseConstructorListScraper
SeedListTableScraper <|-- BaseConstructorListScraper
F1TableScraper <|-- BaseEngineTableScraper
SubSectionParser <|-- ByRaceTitleSubSectionParser
DeclarativeSectionTableParseMixin <|-- CircuitsListScraper
SeedListTableScraper <|-- CircuitsListScraper
ListScraper <|-- ConstructorsListScraper
NestedWikiSectionParser <|-- CurrentRulesSectionParser
SubSectionParser <|-- DetailByDriverSubSectionParser
NestedWikiSectionParser <|-- DriversListSectionParser
NestedWikiSectionParser <|-- DriversSectionParser
SubSectionParser <|-- EngineManufacturersIndianapolisSubSectionParser
F1TableScraper <|-- EngineManufacturersListScraper
NestedWikiSectionParser <|-- EngineManufacturersSectionParser
BaseEngineTableScraper <|-- EngineRegulationScraper
SubSectionParser <|-- EngineRegulationSubSectionParser
BaseEngineTableScraper <|-- EngineRestrictionsScraper
SubSectionParser <|-- EngineSubSectionParser
SeedListTableScraper <|-- F1DriversListScraper
F1TableScraper <|-- F1FatalitiesListScraper
SectionAdapterScraperBase <|-- F1SingleCircuitScraper
ArticleScraperBase <|-- F1SingleGrandPrixScraper
WikiScraper <|-- F1SponsorshipLiveriesScraper
F1TableScraper <|-- F1StandingsScraper
WikiScraper <|-- F1TableScraper
NestedWikiSectionParser <|-- FatalitiesSectionParser
F1TableScraper <|-- FemaleDriversListScraper
SubSectionParser <|-- GenericIndianapolisOnlySubSectionParser
SeedListTableScraper <|-- GrandsPrixListScraper
NestedWikiSectionParser <|-- HistorySectionParser
IndianapolisOnlyMixin <|-- IndianapolisOnlyListScraper
ListScraper <|-- IndianapolisOnlyListScraper
F1TableScraper <|-- LapRecordsTableScraper
SectionTraversalMixin <|-- ListScraper
WikiScraper <|-- ListScraper
NestedWikiSectionParser <|-- ManufacturersSectionParser
NestedSectionHandlingMixin <|-- RecursiveSectionParser
WikiElementParsingMixin <|-- RecursiveSectionParser
RecursiveSectionParser <|-- NestedWikiSectionParser
SubSectionParser <|-- NonChampionshipsRacesSubSectionParser
SubSectionParser <|-- OfficialDriversSubSectionParser
NestedWikiSectionParser <|-- PointsScoringSystemsSectionParser
NestedWikiSectionParser <|-- PrivateerTeamsSectionParser
NestedWikiSectionParser <|-- RacesSectionParser
F1TableScraper <|-- RedFlaggedRacesBaseScraper
WikiScraper <|-- RedFlaggedRacesScraper
NestedWikiSectionParser <|-- RedFlaggedRacesSectionParser
SeedListTableScraper <|-- SeasonsListScraper
NestedWikiSectionParser <|-- SeasonsSectionParser
ArticleScraperBase <|-- SectionAdapterScraperBase
SectionAdapter <|-- SectionAdapterScraperBase
SectionAwareMixin <|-- SectionAdapterScraperBase
ArticleScraperBase <|-- SectionByIdScraperBase
SectionAwareMixin <|-- SectionByIdScraperBase
F1TableScraper <|-- SeedListTableScraper
SubSubSectionParser <|-- ShortenedRacesSubSubSectionParser
SectionAdapterScraperBase <|-- SingleConstructorScraper
SectionAdapterScraperBase <|-- SingleDriverScraper
ArticleScraperBase <|-- SingleEngineManufacturerScraper
SectionAdapterScraperBase <|-- SingleSeasonScraper
SubSectionParser <|-- SpecialCasesSubSectionParser
SubSubSectionParser <|-- SpecialCasesSubSubSectionRouter
SubSubSectionParser <|-- SprintRacesSubSubSectionParser
RecursiveSectionParser <|-- SubSectionParser
RecursiveSectionParser <|-- SubSubSectionParser
RecursiveSectionParser <|-- SubSubSubSectionParser
SubSectionParser <|-- TyreManufacturersBySeasonSubSectionParser
F1TableScraper <|-- TyreManufacturersScraper
F1TableScraper <|-- PointsScraper
SectionTablesHtmlParserABC <|-- ArticleSectionTablesHtmlParser

@enduml
