@startuml
title Scraper Hierarchy
skinparam classAttributeIconSize 0
hide empty members
hide circle

abstract class ArticleScraperBase
class ArticleTablesParser
abstract class BaseConstructorListScraper
abstract class BaseEngineTableScraper
class BodyContentAssembler
class ByRaceTitleSubSectionParser
class CircuitsListScraper
class ConstructorsListScraper
class CurrentRulesSectionParser
abstract class DeclarativeSectionTableParseMixin
class DetailByDriverSubSectionParser
class DriversListSectionParser
class DriversSectionParser
class EngineManufacturersIndianapolisSubSectionParser
class EngineManufacturersListScraper
class EngineManufacturersSectionParser
class EngineRegulationScraper
class EngineRegulationSubSectionParser
class EngineRestrictionsScraper
class EngineSubSectionParser
class F1DriversListScraper
class F1FatalitiesListScraper
class F1SingleCircuitScraper
class F1SingleGrandPrixScraper
class F1SponsorshipLiveriesScraper
class F1StandingsScraper
abstract class F1TableScraper
class FatalitiesSectionParser
class FemaleDriversListScraper
class GenericIndianapolisOnlySubSectionParser
class GrandsPrixListScraper
class HistorySectionParser
class IndianapolisOnlyListScraper
class LapRecordsTableScraper
class ListScraper
class NonChampionshipsRacesSubSectionParser
class OfficialDriversSubSectionParser
class PointsScoringSystemsSectionParser
class PointsScraper
class PointsScraper
class PrivateerTeamsSectionParser
class RacesSectionParser
class RecursiveSectionParser
class RedFlaggedRacesBaseScraper
class RedFlaggedRacesScraper
class RedFlaggedRacesSectionParser
class SeasonsListScraper
class SeasonsSectionParser
class SectionAdapter
abstract class SectionAwareMixin
abstract class SectionByIdScraperBase
class SeedListTableScraper
class ShortenedRacesSubSubSectionParser
class SingleConstructorScraper
class SingleDriverScraper
class SingleEngineManufacturerScraper
class SingleSeasonScraper
class SpecialCasesSubSectionParser
class SpecialCasesSubSubSectionRouter
class SprintRacesSubSubSectionParser
class TyreManufacturersBySeasonSubSectionParser
class TyreManufacturersScraper
abstract class WikiElementParsingMixin
abstract class WikiScraper

WikiElementParsingMixin <|-- WikiScraper
WikiScraper <|-- ArticleScraperBase
HtmlSoupParserABC <|-- ArticleTablesParser
DeclarativeSectionTableParseMixin <|-- BaseConstructorListScraper
SeedListTableScraper <|-- BaseConstructorListScraper
F1TableScraper <|-- BaseEngineTableScraper
RecursiveSectionParser <|-- ByRaceTitleSubSectionParser
DeclarativeSectionTableParseMixin <|-- CircuitsListScraper
SeedListTableScraper <|-- CircuitsListScraper
ListScraper <|-- ConstructorsListScraper
RecursiveSectionParser <|-- CurrentRulesSectionParser
RecursiveSectionParser <|-- DetailByDriverSubSectionParser
RecursiveSectionParser <|-- DriversListSectionParser
RecursiveSectionParser <|-- DriversSectionParser
RecursiveSectionParser <|-- EngineManufacturersIndianapolisSubSectionParser
F1TableScraper <|-- EngineManufacturersListScraper
RecursiveSectionParser <|-- EngineManufacturersSectionParser
BaseEngineTableScraper <|-- EngineRegulationScraper
RecursiveSectionParser <|-- EngineRegulationSubSectionParser
BaseEngineTableScraper <|-- EngineRestrictionsScraper
RecursiveSectionParser <|-- EngineSubSectionParser
SeedListTableScraper <|-- F1DriversListScraper
F1TableScraper <|-- F1FatalitiesListScraper
ArticleScraperBase <|-- F1SingleCircuitScraper
SectionAdapter <|-- F1SingleCircuitScraper
SectionAwareMixin <|-- F1SingleCircuitScraper
ArticleScraperBase <|-- F1SingleGrandPrixScraper
WikiScraper <|-- F1SponsorshipLiveriesScraper
F1TableScraper <|-- F1StandingsScraper
WikiScraper <|-- F1TableScraper
RecursiveSectionParser <|-- FatalitiesSectionParser
F1TableScraper <|-- FemaleDriversListScraper
RecursiveSectionParser <|-- GenericIndianapolisOnlySubSectionParser
SeedListTableScraper <|-- GrandsPrixListScraper
RecursiveSectionParser <|-- HistorySectionParser
ListScraper <|-- IndianapolisOnlyListScraper
F1TableScraper <|-- LapRecordsTableScraper
WikiScraper <|-- ListScraper
RecursiveSectionParser <|-- ManufacturersSectionParser
WikiElementParsingMixin <|-- RecursiveSectionParser
RecursiveSectionParser <|-- NonChampionshipsRacesSubSectionParser
RecursiveSectionParser <|-- OfficialDriversSubSectionParser
RecursiveSectionParser <|-- PointsScoringSystemsSectionParser
RecursiveSectionParser <|-- PrivateerTeamsSectionParser
RecursiveSectionParser <|-- RacesSectionParser
F1TableScraper <|-- RedFlaggedRacesBaseScraper
WikiScraper <|-- RedFlaggedRacesScraper
RecursiveSectionParser <|-- RedFlaggedRacesSectionParser
SeedListTableScraper <|-- SeasonsListScraper
RecursiveSectionParser <|-- SeasonsSectionParser
ArticleScraperBase <|-- SectionByIdScraperBase
SectionAwareMixin <|-- SectionByIdScraperBase
F1TableScraper <|-- SeedListTableScraper
RecursiveSectionParser <|-- ShortenedRacesSubSubSectionParser
ArticleScraperBase <|-- SingleConstructorScraper
SectionAdapter <|-- SingleConstructorScraper
SectionAwareMixin <|-- SingleConstructorScraper
ArticleScraperBase <|-- SingleDriverScraper
SectionAdapter <|-- SingleDriverScraper
SectionAwareMixin <|-- SingleDriverScraper
ArticleScraperBase <|-- SingleEngineManufacturerScraper
ArticleScraperBase <|-- SingleSeasonScraper
SectionAdapter <|-- SingleSeasonScraper
SectionAwareMixin <|-- SingleSeasonScraper
RecursiveSectionParser <|-- SpecialCasesSubSectionParser
RecursiveSectionParser <|-- SpecialCasesSubSubSectionRouter
RecursiveSectionParser <|-- SprintRacesSubSubSectionParser
RecursiveSectionParser <|-- TyreManufacturersBySeasonSubSectionParser
F1TableScraper <|-- TyreManufacturersScraper
F1TableScraper <|-- PointsScraper

@enduml
