@startuml
title Domain Section Parsers
skinparam classAttributeIconSize 0
hide empty members
hide circle

abstract class ApplyForElementsMixin
class CancelledRoundsParser
class CircuitEventsSectionParser
class CircuitLapRecordsSectionParser
class CircuitLayoutHistorySectionParser
class CircuitsListSectionParser
class ColinChapmanTrophyParser
class ConstructorChampionshipResultsSectionParser
class ConstructorCompleteF1ResultsSectionParser
class ConstructorHistorySectionParser
class ConstructorTablesSectionParser
class ConstructorsSectionParser
class CurrentConstructorsSectionParser
abstract class DeclarativeSectionTableParseMixin
class DriverResultsSectionParser
abstract class ExtractListItemsMixin
class FormerConstructorsSectionParser
class GrandPrixByYearSectionParser
class JimClarkTrophyParser
abstract class NestedSectionHandlingMixin
class SeasonCalendarParser
class SeasonCalendarSectionParser
class SeasonConstructorsStandingsSectionParser
class SeasonDriversStandingsSectionParser
class SeasonEntriesParser
class SeasonFreePracticeParser
class SeasonMidSeasonChangesSectionParser
class SeasonNonChampionshipParser
class SeasonRegionalChampionshipParser
class SeasonRegulationChangesSectionParser
class SeasonResultsParser
class SeasonResultsSectionParser
class SeasonScoringSystemParser
abstract class SectionTableParseMixin
class SponsorshipSectionParser
class TeamLiveriesSectionParser
class TestingVenuesParser

ConstructorTablesSectionParser <|-- ConstructorChampionshipResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorCompleteF1ResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorHistorySectionParser
ConstructorsSectionParser <|-- CurrentConstructorsSectionParser
SectionTableParseMixin <|-- DeclarativeSectionTableParseMixin
ConstructorsSectionParser <|-- FormerConstructorsSectionParser
ExtractListItemsMixin <|-- SeasonMidSeasonChangesSectionParser
ExtractListItemsMixin <|-- SeasonRegulationChangesSectionParser

@enduml