@startuml
title Miscellaneous Parser Utilities
skinparam classAttributeIconSize 0
hide empty members
hide circle

class ActiveYearsParser
class ArticleTablesAssembler
class BestFinishParser
class CallableInfoboxFieldParser
class CarNumbersParser
class CategoryLinksParser
class ChampionshipsParser
class FinishedSeasonParser
abstract class HasTableMapperABC
abstract class HasTableParserABC
abstract class HtmlTagParserABC
class HtmlInfoboxFieldParser
class IndianapolisConstructorsListParser
class IndianapolisOnlyListParser
abstract class IndianapolisOnlyMixin
class InfoboxCareerParser
abstract class InfoboxCellParserABC
class InfoboxCellValueExtractor
abstract class InfoboxHtmlFieldParserABC
class InfoboxRowsParser
abstract class InfoboxRowsParserABC
class InfoboxTitlesParser
class LicenceParser
class NationalityParser
abstract class NestedChildParser
class ParagraphElementParser
class PrivateerTeamsListParser
abstract class ParserABC
class RaceEventParser
class ReferencesWrapParser
class SectionAssembler
abstract class SectionTraversalMixin
class SponsorPartsParser
abstract class StructureParser
class TeamsParser
class WikiListElementParser
class WikiListParser
abstract class WikiTagParser
class YearParser

HtmlInfoboxFieldParser <|-- ActiveYearsParser
HtmlInfoboxFieldParser <|-- BestFinishParser
HtmlInfoboxFieldParser <|-- CallableInfoboxFieldParser
HtmlInfoboxFieldParser <|-- CarNumbersParser
HtmlInfoboxFieldParser <|-- ChampionshipsParser
HtmlInfoboxFieldParser <|-- FinishedSeasonParser
InfoboxHtmlFieldParserABC <|-- HtmlInfoboxFieldParser
ListElementParser <|-- IndianapolisConstructorsListParser
ListElementParser <|-- IndianapolisOnlyListParser
InfoboxRowsParser <|-- InfoboxCareerParser
InfoboxCellParserABC <|-- InfoboxCellValueExtractor
InfoboxRowsParserABC <|-- InfoboxRowsParser
InfoboxRowsParser <|-- InfoboxTitlesParser
HtmlInfoboxFieldParser <|-- LicenceParser
HtmlInfoboxFieldParser <|-- NationalityParser
HtmlInfoboxFieldParser <|-- RaceEventParser
HtmlInfoboxFieldParser <|-- TeamsParser
WikiListElementParser <|-- PrivateerTeamsListParser
ParserABC <|-- ReferencesWrapParser
ParserABC <|-- SponsorPartsParser
HtmlTagParserABC <|-- WikiListParser
HtmlTagParserABC <|-- WikiTagParser
ParserABC <|-- YearParser

@enduml
