@startuml

hide circle
hide empty members

abstract class ParserABC
abstract class HtmlTagParserABC
abstract class HtmlSoupParserABC
abstract class HeaderNormalizationMixin
abstract class SectionInfoboxesHtmlParserABC
abstract class SectionListsHtmlParserABC
abstract class SectionTextBlocksHtmlParserABC
abstract class InfoboxParserABC
abstract class TableCellExtractionMixin

class WikiTableHtmlParser
class CollapsibleTableParser
class ContentTextParser
class HeaderParser
class InfoboxTableParser
class SoupParser
class SponsorPartsParser
class YearParser
class ArticleTablesParser
class HtmlTableParser
class SeasonStandingsParser
class SectionElementParser
class SponsorshipSectionParser
class TeamLiveriesSectionParser
class WikiSectionElementParser
class F1StandingsTableParser
class InfoboxCellValueExtractor
class ListElementParser
class NavboxElementParser
class PrivateerTeamsListParser
class TableElementParser
class WikiNavboxElementParser
class WikiNavboxParser
class WikiParagraphElementParser
class WikiReferencesElementParser
class WikiTableElementParser
class SeasonsTableParser
class WikiTableParser


ParserABC <|-- CollapsibleTableParser
ParserABC <|-- ContentTextParser
ParserABC <|-- HeaderParser
ParserABC <|-- HtmlSoupParserABC
ParserABC <|-- HtmlTagParserABC
ParserABC <|-- InfoboxTableParser
ParserABC <|-- SoupParser
ParserABC <|-- SponsorPartsParser
ParserABC <|-- YearParser

HtmlSoupParserABC <|-- ArticleTablesParser
HtmlSoupParserABC <|-- HtmlTableParser
HtmlSoupParserABC <|-- SeasonStandingsParser
HtmlSoupParserABC <|-- SectionElementParser
HtmlSoupParserABC <|-- SectionInfoboxesHtmlParserABC
HtmlSoupParserABC <|-- SectionListsHtmlParserABC
HtmlSoupParserABC <|-- SectionTextBlocksHtmlParserABC
HtmlSoupParserABC <|-- SponsorshipSectionParser
HtmlSoupParserABC <|-- TeamLiveriesSectionParser
HtmlSoupParserABC <|-- WikiSectionElementParser

HtmlTagParserABC <|-- F1StandingsTableParser
HtmlTagParserABC <|-- InfoboxCellValueExtractor
HtmlTagParserABC <|-- InfoboxParserABC
HtmlTagParserABC <|-- ListElementParser
HtmlTagParserABC <|-- NavboxElementParser
HtmlTagParserABC <|-- PrivateerTeamsListParser
HtmlTagParserABC <|-- TableElementParser
HtmlTagParserABC <|-- WikiNavboxElementParser
HtmlTagParserABC <|-- WikiNavboxParser
HtmlTagParserABC <|-- WikiParagraphElementParser
HtmlTagParserABC <|-- WikiReferencesElementParser
HtmlTagParserABC <|-- WikiTableElementParser
HtmlTagParserABC <|-- WikiTableHtmlParser

HeaderNormalizationMixin <|-- WikiTableHtmlParser
TableCellExtractionMixin <|-- WikiTableHtmlParser

WikiTableHtmlParser <|-- SeasonsTableParser
WikiTableHtmlParser <|-- WikiTableParser

@enduml
