@startuml

hide circle
hide empty members


abstract class WikiInfoboxElementParserABC

class CircuitInfoboxParser
class DriverInfoboxParser
class InfoboxElementParser
class WikiInfoboxElementParser
class WikiInfoboxHtmlParser


WikiInfoboxElementParserABC <|-- CircuitInfoboxParser
WikiInfoboxElementParserABC <|-- DriverInfoboxParser
WikiInfoboxElementParserABC <|-- InfoboxElementParser
WikiInfoboxElementParserABC <|-- WikiInfoboxElementParser
WikiInfoboxElementParserABC <|-- WikiInfoboxHtmlParser

@enduml
