@startuml All Classes Diagram
!theme plain
skinparam backgroundColor #FAFAFA
skinparam handwritten false
skinparam shadowing false
skinparam classAttributeIconSize 0
hide members
hide circle

title F1 Project - Diagram wszystkich klas

package "Complete Extractor" {
    class AttachDetailsStrategy
    class BundleRecordWithDetailsStrategy
    class CompleteExtractorBase
    class CompleteExtractorDomainConfig
    class ExtractDetailFieldStrategy
    class RecordAssemblyStrategy
}

package "Config" {
    class AppConfig
    class AppConfigProvider
    class AppPaths
    class GeminiAppConfig
    class HttpAppConfig
}

package "Infrastructure" {
    class BaseHttpClient
    class DefaultHttpPolicyFactory
    class DefaultRetryPolicy
    class FileCache
    class FileTtlCache
    class FileTtlCacheAdapter
    class GeminiCache
    class GeminiCacheService
    class GeminiClient
    class GeminiJsonFileCacheAdapter
    class GeminiOrchestrationService
    class GeminiResponseParser
    class GeminiTransport
    class HTTPError
    class HTTPTimeoutError
    class HeaderResolver
    class HttpClientConfig
    class HttpClientProtocol
    class HttpPolicy
    class HttpResponseFileCacheAdapter
    class HttpResponseProtocol
    class HttpShimError
    class HttpShimErrorResponseAdapter
    class MinDelayRateLimiter
    class ModelConfig
    class ModelSelector
    class ModelState
    class RateLimiter
    class RequestError
    class RequestExecutor
    class Response
    class ResponseCacheService
    class RetryPolicy
    class Session
    class SessionProtocol
    class TextCacheProtocol
    class UrllibHttpClient
    class WikipediaCachePolicy
}

package "Layers" {
    class BaseExecutor
    class BaseRegistryEntry
    class CompositeLayerZeroJobHook
    class ConstructorsMirrorService
    class DefaultLayerZeroRunConfigFactory
    class DomainPipelineConfig
    class DriverRecordModel
    class DriverSeriesStats
    class EngineRecordModel
    class FunctionExportRunner
    class GrandPrixRunner
    class LayerExecutorProtocol
    class LayerJobRunner
    class LayerOneExecutor
    class LayerOneRunnerProtocol
    class LayerZeroExecutor
    class LayerZeroJobHook
    class LayerZeroMergeService
    class LayerZeroMergeServiceProtocol
    class LayerZeroRunConfigFactory
    class LayerZeroRunConfigFactoryProtocol
    class LinkValue
    class ListJobRegistryEntry
    class MergeModel
    class MirrorConstructorsJobHook
    class MirrorToDomainByFilenameJobHook
    class NullLayerZeroJobHook
    class PathResolver
    class RaceRecordModel
    class RawRegistrySpec
    class RegistryValidationRule
    class RegistryValidationSpec
    class RunnerMetadata
    class SeasonRecordModel
    class SeedRegistryEntry
    class SponsorshipLiveriesRunConfigFactory
    class StaticScraperKwargsFactory
    class TeamRecordModel
    class WikiPipelineApplication
    class WikiPipelineComponents
    class WikiPipelineComponentsFactory
    class WikiPipelineFacade
}

package "Models" {
    class BaseRecordFactory
    class CarRecord
    class CarRecordFactory
    class Circuit
    class CircuitBaseRecord
    class CircuitCompleteRecord
    class CircuitContract
    class CircuitDetailsRecord
    class CircuitRecord
    class CircuitRecordFactory
    class ConstructorRecord
    class ConstructorRecordFactory
    class DataContract
    class DateValue
    class DriverContract
    class DriverRecord
    class DriverRecordFactory
    class DriversChampionships
    class DriversChampionshipsRecord
    class DriversChampionshipsRecordFactory
    class EngineManufacturer
    class EngineManufacturerRecord
    class EngineManufacturerRecordFactory
    class EngineRegulation
    class EngineRestriction
    class EntityName
    class EventRecord
    class EventRecordFactory
    class FactoryRegistryError
    class FactoryRegistryProvider
    class FactorySpec
    class FatalityRecord
    class FatalityRecordFactory
    class FieldNormalizer
    class GrandsPrixRecord
    class GrandsPrixRecordFactory
    class Link
    class LinkRecord
    class NormalizedDate
    class PointsContract
    class RecordBuilders
    class RecordContract
    class RecordDefinition
    class RecordFactoryProtocol
    class RecordType
    class Rounds
    class SeasonRecord
    class SeasonRecordFactory
    class SeasonRef
    class SeasonSummaryRecord
    class SeasonSummaryRecordFactory
    class SeasonYear
    class SectionId
    class SerializableProtocol
    class SerializerProtocol
    class SpecialDriverRecord
    class SpecialDriverRecordFactory
    class ValidatedModel
    class ValueObject
    class WikiUrl
}

package "Scrapers (root)" {
    class DataPaths
    class DeprecatedModuleEntry
    class ModuleDefinition
}

package "Scrapers / Base" {
    class ABCScraper
    class AllInfoboxTablesExtractor
    class ApplyForElementsMixin
    class AuditEntry
    class AutoColumn
    class BackgroundMixin
    class BaseColumn
    class BaseConstructorColumn
    class BaseDataExtractor
    class BaseInfoboxExtractionService
    class BaseRecordAssembler
    class BaseRecordAssemblerInput
    class BaseSectionExtractionService
    class BoolColumn
    class BrListColumn
    class CacheAdapter
    class CacheOptions
    class CallableRecordFactoryAdapter
    class CheckpointMetadata
    class CheckpointMetrics
    class CheckpointPayload
    class ColumnContext
    class ColumnFactory
    class ColumnRef
    class ColumnSpec
    class CommonMetadataPostProcessor
    class CompactStepDiffWriter
    class CompositeDataExtractor
    class CompositeDataExtractorChildren
    class ConfigurableSectionServiceFactory
    class ConstructorIntrospection
    class ConstructorParsingHelpers
    class ConstructorPartColumn
    class CriticalSection
    class CsvFormatter
    class CurrentYearOutputPathRenderer
    class DataExporter
    class DataFrameFormatterProtocol
    class DateColumn
    class DeclarativeSectionTableParseMixin
    class DomainEntrypointConfig
    class DomainParseError
    class DriverColumn
    class DriverListColumn
    class DriverParsingHelpers
    class DriversChampionshipsTransformer
    class EmptyValuePolicy
    class EngineColumn
    class EngineLinkHelpers
    class EngineParsingHelpers
    class EngineTextHelpers
    class EntityColumnSpec
    class EntrantColumn
    class EnumMarksMixin
    class ErrorBehavior
    class ErrorCategory
    class ErrorCodeDefinition
    class ErrorHandler
    class ErrorPolicy
    class ErrorReport
    class ExecutedStep
    class ExportMetadata
    class ExportService
    class ExportableRecord
    class ExporterProtocol
    class ExtractListItemsMixin
    class F1ListScraper
    class F1TableScraper
    class FailedToMakeRestartTransformer
    class FatalitiesCarTransformer
    class FieldnamesStrategyProtocol
    class FieldnamesStrategySelector
    class FirstInfoboxTableExtractor
    class FuncColumn
    class HtmlFetcher
    class HtmlRowBackgroundColorAdapter
    class HtmlTableParser
    class HttpOptions
    class IdentityOutputPathRenderer
    class IndianapolisOnlyListConfig
    class IndianapolisOnlyListScraper
    class IndianapolisOnlyMixin
    class InfoboxExtractionResult
    class InfoboxExtractionService
    class InfoboxExtractor
    class InfoboxFieldMapper
    class InfoboxFieldSpec
    class InfoboxHtmlParser
    class InfoboxPayloadDTO
    class InfoboxRecordInput
    class InfoboxRecordMapper
    class InfoboxSchema
    class InfoboxSchemaDSL
    class InfoboxSchemaField
    class IterableSourceAdapter
    class JsonFormatter
    class JsonLinesFormatter
    class LapRecord
    class LapRecordsTableScraper
    class LayoutTableRecordMapper
    class LayoutTableRowsInput
    class LazyScraperClassProxy
    class LegacyScraperAdapter
    class LinksListColumn
    class ListColumn
    class ListScraperProtocol
    class MappingRecordFactory
    class MetricColumnSpec
    class MissingSectionError
    class MultiColumn
    class MultiIterableSourceAdapter
    class MultiLevelHeaderBuilder
    class NameStatusColumn
    class NoOpProgressAdapter
    class NormalizationPlugin
    class NormalizeLinksTransformer
    class NormalizedTime
    class OptionsScraperAdapter
    class OrchestrationPaths
    class OutputPathRenderer
    class PandasDataFrameFormatter
    class ParsedValueColumn
    class PipelineError
    class PipelineIssue
    class PipelineOptions
    class PipelineOrchestrator
    class PipelineProfile
    class PipelineStage
    class PipelineStep
    class PointsColumn
    class PointsScoringSystemsHistoryTransformer
    class PositionColumn
    class ProfileResolver
    class ProgressAdapter
    class QualityReportService
    class QualityReporter
    class RangeColumn
    class RecordAssemblerProtocol
    class RecordFactory
    class RecordFactoryAdapters
    class RecordFactoryTransformer
    class RecordNormalizer
    class RecordPostProcessor
    class RecordTransformer
    class RegexColumn
    class ResolvedInput
    class RestartStatusColumn
    class ResultExportService
    class ResultTabularAdapter
    class ResultsParsingHelpers
    class RunConfig
    class RunConfigOptionsMapper
    class RunPathConfig
    class RunPathName
    class RunProfileName
    class RunProfileSpec
    class RunTraceWriter
    class RuntimeComponents
    class RuntimeInitializer
    class SafeParserMixin
    class SchemaCompositeRecordValidator
    class ScrapeResult
    class ScrapeResultNormalizer
    class ScraperCommonConfig
    class ScraperConfig
    class ScraperCreationAdapter
    class ScraperCreationContext
    class ScraperError
    class ScraperErrorPayload
    class ScraperFactory
    class ScraperNetworkError
    class ScraperNotFoundError
    class ScraperOptions
    class ScraperOptionsBuilder
    class ScraperParseError
    class ScraperPipelineBinding
    class ScraperPipelineRunner
    class ScraperRunner
    class ScraperRuntime
    class ScraperRuntimeFactory
    class ScraperValidationError
    class SeasonsColumn
    class SectionAdapter
    class SectionAdapterEntry
    class SectionExtractionServiceProtocol
    class SectionIdResolver
    class SectionParseResult
    class SectionRecordInput
    class SectionRecordMapper
    class SectionResolution
    class SectionSelectionStrategy
    class SectionServiceFactory
    class SectionSourceAdapter
    class SectionTableParseMixin
    class SectionTableParserBase
    class SectionsPayloadDTO
    class SeedListTableScraper
    class ShortenedRacePointsTransformer
    class SingleScraperProtocol
    class SingleWikiArticleScraperBase
    class SingleWikiArticleSectionAdapterBase
    class SingleWikiArticleSectionByIdBase
    class SkipColumn
    class SoupParser
    class SourceAdapter
    class SourceParseError
    class SourceRef
    class StageCheckpointDumper
    class StageEnvelope
    class StepDeclaration
    class StrategyInfoboxExtractionService
    class TableExtractor
    class TableParsingHelper
    class TablePipeline
    class TablePipelineDebugContext
    class TableRecordInput
    class TableRecordMapper
    class TableRow
    class TableSchema
    class TableSchemaBuilder
    class TableSchemaDSL
    class TableSectionParser
    class TablesPayloadDTO
    class TextColumn
    class TimeColumn
    class TimeRangeColumn
    class TqdmProgressAdapter
    class TransformersPipeline
    class TransportError
    class TyreColumn
    class UnitColumn
    class UnitValue
    class UrlColumn
    class ValidatingSectionServiceFactory
    class ValidationError
    class ValidationRunner
    class ValueNormalizationPipeline
    class WikipediaInfoboxScraper
    class WikipediaSectionByIdSelectionStrategy
    class YearExtractor
    class YearPlaceholderOutputPathRenderer
    class _ConstructorPartParser
    class _DomainEntrypointSpec
    class _HasTableParser
    class _SourceAdapterFetcherShim
}

package "Scrapers / Circuits" {
    class CircuitAdditionalInfoParser
    class CircuitEntitiesParser
    class CircuitEntityParser
    class CircuitEventsSectionParser
    class CircuitGeoParser
    class CircuitHistoryParser
    class CircuitInfoboxExtractionService
    class CircuitInfoboxExtractor
    class CircuitLapRecordParser
    class CircuitLapRecordsSectionParser
    class CircuitLayoutHistorySectionParser
    class CircuitLayoutsParser
    class CircuitNameStatusColumn
    class CircuitRecordAssembler
    class CircuitRecordDTO
    class CircuitScraperCompositionFactory
    class CircuitScraperDependencies
    class CircuitSectionExtractionService
    class CircuitService
    class CircuitSpecsParser
    class CircuitTextProcessing
    class CircuitsListScraper
    class CircuitsListSectionParser
    class CircuitsListTableParser
    class CircuitsRecordValidator
    class F1CircuitInfoboxParser
    class F1CompleteCircuitDataExtractor
    class F1SingleCircuitScraper
    class InfoboxTextUtils
    class LastLengthUsedColumn
}

package "Scrapers / Constructors" {
    class BaseConstructorListScraper
    class CompleteConstructorsDataExtractor
    class ConstructorChampionshipResultsSectionParser
    class ConstructorColumn
    class ConstructorCompleteF1ResultsSectionParser
    class ConstructorHistorySectionParser
    class ConstructorInfoboxExtractionService
    class ConstructorNameColumn
    class ConstructorRecordAssembler
    class ConstructorRecordDTO
    class ConstructorScraperCompositionFactory
    class ConstructorScraperDependencies
    class ConstructorSectionExtractionService
    class ConstructorTablesSectionParser
    class ConstructorsListScraper
    class ConstructorsSectionParser
    class CurrentConstructorsSectionParser
    class CurrentConstructorsTableParser
    class FormerConstructorsSectionParser
    class FormerConstructorsTableParser
    class PrivateerTeamsListParser
    class PrivateerTeamsSectionParser
    class SingleConstructorScraper
    class _IndianapolisConstructorsListParser
}

package "Scrapers / Drivers" {
    class ActiveYearsParser
    class BaseDriverResultsSectionParser
    class BestFinishParser
    class CarNumbersParser
    class ChampionshipsParser
    class CollapsibleTableParser
    class CompleteDriverDataExtractor
    class DefaultDriverInfoboxParserProvider
    class DetailByDriverSubSectionParser
    class DriverInfoboxExtractionService
    class DriverInfoboxParser
    class DriverInfoboxParserBundle
    class DriverInfoboxParserProvider
    class DriverNameStatusColumn
    class DriverOrderedTableParser
    class DriverRecordAssembler
    class DriverRecordDTO
    class DriverResultsSchemaFactory
    class DriverResultsSectionConfig
    class DriverResultsSectionParser
    class DriverResultsTableClassifier
    class DriverScraperCompositionFactory
    class DriverScraperDependencies
    class DriverSectionExtractionService
    class DriversListSectionParser
    class DriversListTableParser
    class DriversRecordValidator
    class DriversSectionParser
    class EntriesStartsColumn
    class EntriesStartsPointsPostProcessor
    class F1DriversListScraper
    class F1FatalitiesListScraper
    class FatalitiesSectionParser
    class FatalitiesTableParser
    class FatalityDateColumn
    class FatalityEventColumn
    class FemaleDriversListScraper
    class FemaleDriversTableParser
    class FinishedSeasonParser
    class InfoboxCareerParser
    class InfoboxCellParser
    class InfoboxGeneralParser
    class InfoboxLinkExtractor
    class InfoboxSectionCollector
    class InfoboxSectionDiscovery
    class InfoboxTitlesParser
    class LicenceParser
    class NationalityParser
    class NumericParser
    class OfficialDriversSubSectionParser
    class PointsOrTextColumn
    class RaceEventParser
    class RoundColumn
    class SeasonParser
    class SeriesColumn
    class SingleDriverScraper
    class TeamsParser
    class UnknownValueColumn
    class YearParser
}

package "Scrapers / Engines" {
    class BaseEngineTableScraper
    class CurrentRulesSectionParser
    class EngineConfigurationColumn
    class EngineManufacturerNameStatusColumn
    class EngineManufacturersListScraper
    class EngineManufacturersSectionParser
    class EngineManufacturersTableParser
    class EngineRegulationScraper
    class EngineRegulationSubSectionParser
    class EngineRegulationTableParser
    class EngineRestrictionsScraper
    class EngineRestrictionsTableParser
    class EngineRpmLimitColumn
    class EngineSubSectionParser
    class F1CompleteEngineManufacturerDataExtractor
    class FuelFlowRateColumn
    class FuelInjectionPressureLimitColumn
    class FuelLimitPerRaceColumn
    class HistorySectionParser
    class IndianapolisOnlyListParser
    class IndianapolisOnlySubSectionParser
    class NestedTextColumn
    class NestedUnitListColumn
    class SingleEngineManufacturerScraper
}

package "Scrapers / Grands Prix" {
    class ByRaceTitleSubSectionParser
    class ConstructorSplitColumn
    class F1CompleteGrandPrixDataExtractor
    class F1SingleGrandPrixScraper
    class GrandPrixByYearRecordAssembler
    class GrandPrixByYearRecordInput
    class GrandPrixByYearRecordMapper
    class GrandPrixByYearSectionParser
    class GrandPrixChampionshipResolver
    class GrandsPrixListScraper
    class GrandsPrixRecordValidator
    class GrandsPrixTableParser
    class LocationColumn
    class RaceTitleStatusColumn
    class RacesSectionParser
}

package "Scrapers / Points" {
    class BasePointsScraper
    class FirstPlaceColumn
    class PointsScoringSystemsHistoryTableParser
    class PointsScoringSystemsSectionParser
    class PointsScraper
    class ShortenedRacesPointsTableParser
    class ShortenedRacesSubSubSectionParser
    class SpecialCasesSubSectionParser
    class SpecialCasesSubSubSectionRouter
    class SprintPointsTableParser
    class SprintRacesSubSubSectionParser
    class _SprintQualifyingPointsScraper
}

package "Scrapers / Races" {
    class BaseRedFlaggedRacesTableParser
    class NonChampionshipsRacesSubSectionParser
    class NonChampionshipsRacesTableParser
    class RedFlaggedRacesBaseScraper
    class RedFlaggedRacesScraper
    class RedFlaggedRacesSectionParser
    class WorldChampionshipsRacesTableParser
}

package "Scrapers / Seasons" {
    class CalendarCircuitColumn
    class CancelledRoundsParser
    class ClassifiedDNFRule
    class ColinChapmanTrophyParser
    class CompleteSeasonDataExtractor
    class DateRangeColumn
    class DomainParsingPolicy
    class DomainRecordService
    class DoublePointsRoundRule
    class DriversWithRoundsColumn
    class EntryMerger
    class F1StandingsScraper
    class F2EligibilityRule
    class FatalAccidentRule
    class HalfPointsRoundRule
    class JimClarkTrophyParser
    class MarkBasedEligibilityRule
    class RaceResultBackgroundMapper
    class RaceResultCellTransformer
    class RaceResultColumn
    class ResultRule
    class ResultRuleContext
    class RoundRule
    class RoundRuleContext
    class SeasonCalendarParser
    class SeasonCalendarSectionParser
    class SeasonConstructorsStandingsSectionParser
    class SeasonDateColumn
    class SeasonDriversStandingsSectionParser
    class SeasonEntriesParser
    class SeasonFreePracticeParser
    class SeasonMidSeasonChangesSectionParser
    class SeasonNonChampionshipParser
    class SeasonParserSet
    class SeasonParserSetBuilder
    class SeasonPayloadDTO
    class SeasonRecordAssembler
    class SeasonRecordSections
    class SeasonRegionalChampionshipParser
    class SeasonRegulationChangesSectionParser
    class SeasonResultsParser
    class SeasonResultsSectionParser
    class SeasonScoringSystemParser
    class SeasonScraperCompositionFactory
    class SeasonScraperDependencies
    class SeasonSectionDataCollector
    class SeasonSectionParser
    class SeasonSectionParserBinding
    class SeasonSectionPipeline
    class SeasonStandingsService
    class SeasonTableParser
    class SeasonTextSectionExtractionService
    class SeasonYearResolver
    class SeasonsListScraper
    class SeasonsSectionParser
    class SeasonsTableParser
    class SharedDriveRule
    class SingleSeasonScraper
    class StarMarkNoteRule
    class SuperscriptParseResult
    class TestingVenuesLayout
    class TestingVenuesParser
}

package "Scrapers / Sponsorship & Liveries" {
    class BroaderScopeSplitter
    class ColourListColumn
    class ColourScopeHandler
    class DeduplicateRecordStrategy
    class DepthAwareColourSplitter
    class F1SponsorshipLiveriesScraper
    class GrandPrixScopeAccumulator
    class GrandPrixScopeTransformer
    class GrandPrixSplitStrategy
    class ParenClassifier
    class PipelineRecord
    class PossessiveDriverColourSplitStrategy
    class RecordSplitPipeline
    class RecordSplitStrategy
    class Rule
    class SeasonSplitStrategy
    class SplitRule
    class SponsorColumn
    class SponsorPartsParser
    class SponsorScopeHandler
    class SponsorshipRecordSplitter
    class SponsorshipRecordText
    class SponsorshipSeasonsColumn
    class SponsorshipSectionParser
    class SponsorshipTableParser
    class TeamLiveriesSectionParser
    class TeamLiveriesTableParser
    class _RuleContext
}

package "Scrapers / Tyres" {
    class AppendLinksColumn
    class ManufacturersSectionParser
    class TyreManufacturersBySeasonSubSectionParser
    class TyreManufacturersBySeasonTableParser
    class TyreManufacturersScraper
}

package "Scrapers / Wiki" {
    class ArticleTablesParser
    class BaseNestedSectionParser
    class BaseOrchestrationFlow
    class BodyContentParser
    class CategoryGroup
    class CategoryLinkItem
    class CategoryLinksParsedData
    class CategoryLinksParser
    class ComponentMetadata
    class ContentTextParser
    class DiscoveredComponent
    class DiscoveredListScraperClassProtocol
    class DiscoveredRunnerClassProtocol
    class DiscoveredRunnerProtocol
    class DriversCheckpointFlow
    class FigureParsedData
    class FigureParser
    class HeaderParsedData
    class HeaderParser
    class InfoboxParsedData
    class InfoboxParser
    class LapRecordsWikiTableParser
    class ListParsedData
    class ListParser
    class ListScraperConfigProtocol
    class MappedWikiTableParser
    class NavBoxParsedData
    class NavBoxParser
    class NestedChildParser
    class ParagraphParsedData
    class ParagraphParser
    class ParserRule
    class RaceResultsTableParser
    class ReferencesWrapParsedData
    class ReferencesWrapParser
    class RichCellData
    class SectionDomainConfig
    class SectionExtractionContext
    class SectionMatch
    class SectionMatchPriorities
    class SectionParser
    class SectionProfile
    class SectionTreeMatch
    class SeedQualityReport
    class SeedSectionOrchestrationFlow
    class StandingsTableParser
    class SubSectionParser
    class SubSubSectionParser
    class SubSubSubSectionParser
    class TableParsedData
    class TableParser
    class WikiElementParserMixin
    class WikiElementParsers
    class WikiParsedPayload
    class WikiParser
    class WikiScraper
    class WikiSourceDefinition
    class WikiTableBaseParser
}

package "Validation" {
    class CompositeRecordValidator
    class FunctionalValidator
    class IssueMessageFormatter
    class LegacyValidationIssueAdapter
    class ModelValidateRecordFactoryValidatorAdapter
    class NestedSchema
    class QualityStats
    class RangeRule
    class RecordFactoryValidatorProtocol
    class RecordSchema
    class RecordValidator
    class RequiredFieldRule
    class SchemaValidationEngine
    class StageValidator
    class TypeRule
    class ValidateMethodRecordFactoryValidatorAdapter
    class ValidateRecordFactoryValidatorAdapter
    class ValidationIssue
    class ValidationPipeline
    class ValidationResult
    class ValidationRuleProtocol
    class ValidationStage
    class ValueRange
}

' Inheritance relationships
ABCScraper <|-- WikiScraper
ApplyForElementsMixin <|-- ByRaceTitleSubSectionParser
ApplyForElementsMixin <|-- EngineManufacturersSectionParser
ApplyForElementsMixin <|-- EngineSubSectionParser
ApplyForElementsMixin <|-- OfficialDriversSubSectionParser
ApplyForElementsMixin <|-- PointsScoringSystemsSectionParser
ApplyForElementsMixin <|-- ShortenedRacesSubSubSectionParser
ApplyForElementsMixin <|-- SprintRacesSubSubSectionParser
BackgroundMixin <|-- FatalityEventColumn
BackgroundMixin <|-- NameStatusColumn
BackgroundMixin <|-- RestartStatusColumn
BaseColumn <|-- AutoColumn
BaseColumn <|-- BaseConstructorColumn
BaseColumn <|-- BoolColumn
BaseColumn <|-- BrListColumn
BaseColumn <|-- CalendarCircuitColumn
BaseColumn <|-- ColourListColumn
BaseColumn <|-- ConstructorNameColumn
BaseColumn <|-- ConstructorPartColumn
BaseColumn <|-- DateColumn
BaseColumn <|-- DateRangeColumn
BaseColumn <|-- DriverColumn
BaseColumn <|-- DriverListColumn
BaseColumn <|-- DriversWithRoundsColumn
BaseColumn <|-- EngineColumn
BaseColumn <|-- EngineConfigurationColumn
BaseColumn <|-- EngineRpmLimitColumn
BaseColumn <|-- EntrantColumn
BaseColumn <|-- EntriesStartsColumn
BaseColumn <|-- EnumMarksMixin
BaseColumn <|-- FatalityDateColumn
BaseColumn <|-- FatalityEventColumn
BaseColumn <|-- FirstPlaceColumn
BaseColumn <|-- FuelFlowRateColumn
BaseColumn <|-- FuelInjectionPressureLimitColumn
BaseColumn <|-- FuelLimitPerRaceColumn
BaseColumn <|-- FuncColumn
BaseColumn <|-- LinksListColumn
BaseColumn <|-- ListColumn
BaseColumn <|-- MultiColumn
BaseColumn <|-- NestedTextColumn
BaseColumn <|-- NestedUnitListColumn
BaseColumn <|-- ParsedValueColumn
BaseColumn <|-- PointsColumn
BaseColumn <|-- PointsOrTextColumn
BaseColumn <|-- PositionColumn
BaseColumn <|-- RaceResultColumn
BaseColumn <|-- RangeColumn
BaseColumn <|-- RegexColumn
BaseColumn <|-- RestartStatusColumn
BaseColumn <|-- RoundColumn
BaseColumn <|-- SeasonDateColumn
BaseColumn <|-- SeasonsColumn
BaseColumn <|-- SeriesColumn
BaseColumn <|-- SkipColumn
BaseColumn <|-- SponsorColumn
BaseColumn <|-- SponsorshipSeasonsColumn
BaseColumn <|-- TextColumn
BaseColumn <|-- TimeColumn
BaseColumn <|-- TimeRangeColumn
BaseColumn <|-- TyreColumn
BaseColumn <|-- UnitColumn
BaseColumn <|-- UnknownValueColumn
BaseColumn <|-- UrlColumn
BaseDataExtractor <|-- CompositeDataExtractor
BaseEngineTableScraper <|-- EngineRegulationScraper
BaseEngineTableScraper <|-- EngineRestrictionsScraper
BaseExecutor <|-- LayerOneExecutor
BaseExecutor <|-- LayerZeroExecutor
BaseHttpClient <|-- UrllibHttpClient
BaseNestedSectionParser <|-- SectionParser
BaseNestedSectionParser <|-- SubSectionParser
BaseNestedSectionParser <|-- SubSubSectionParser
BaseOrchestrationFlow <|-- DriversCheckpointFlow
BaseOrchestrationFlow <|-- SeedSectionOrchestrationFlow
BasePointsScraper <|-- PointsScraper
BasePointsScraper <|-- _SprintQualifyingPointsScraper
BaseRecordAssembler <|-- CircuitRecordAssembler
BaseRecordAssembler <|-- ConstructorRecordAssembler
BaseRecordAssembler <|-- SeasonRecordAssembler
BaseRecordFactory <|-- CarRecordFactory
BaseRecordFactory <|-- CircuitRecordFactory
BaseRecordFactory <|-- ConstructorRecordFactory
BaseRecordFactory <|-- DriverRecordFactory
BaseRecordFactory <|-- DriversChampionshipsRecordFactory
BaseRecordFactory <|-- EngineManufacturerRecordFactory
BaseRecordFactory <|-- EventRecordFactory
BaseRecordFactory <|-- FatalityRecordFactory
BaseRecordFactory <|-- GrandsPrixRecordFactory
BaseRecordFactory <|-- SeasonRecordFactory
BaseRecordFactory <|-- SeasonSummaryRecordFactory
BaseRecordFactory <|-- SpecialDriverRecordFactory
BaseRedFlaggedRacesTableParser <|-- NonChampionshipsRacesTableParser
BaseRedFlaggedRacesTableParser <|-- WorldChampionshipsRacesTableParser
BaseRegistryEntry <|-- ListJobRegistryEntry
BaseRegistryEntry <|-- SeedRegistryEntry
BaseSectionExtractionService <|-- CircuitSectionExtractionService
BaseSectionExtractionService <|-- ConstructorSectionExtractionService
BaseSectionExtractionService <|-- DriverSectionExtractionService
BaseSectionExtractionService <|-- SeasonTextSectionExtractionService
CircuitBaseRecord <|-- CircuitCompleteRecord
CircuitBaseRecord <|-- CircuitDetailsRecord
CircuitEntityParser <|-- CircuitAdditionalInfoParser
CircuitTextProcessing <|-- CircuitEntityParser
CircuitTextProcessing <|-- CircuitLapRecordParser
CompleteExtractorBase <|-- CompleteConstructorsDataExtractor
CompleteExtractorBase <|-- CompleteDriverDataExtractor
CompleteExtractorBase <|-- CompleteSeasonDataExtractor
CompleteExtractorBase <|-- F1CompleteCircuitDataExtractor
CompleteExtractorBase <|-- F1CompleteEngineManufacturerDataExtractor
CompleteExtractorBase <|-- F1CompleteGrandPrixDataExtractor
CompositeDataExtractor <|-- CompleteExtractorBase
CompositeRecordValidator <|-- SchemaCompositeRecordValidator
ConstructorTablesSectionParser <|-- ConstructorChampionshipResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorCompleteF1ResultsSectionParser
ConstructorTablesSectionParser <|-- ConstructorHistorySectionParser
ConstructorsSectionParser <|-- CurrentConstructorsSectionParser
ConstructorsSectionParser <|-- FormerConstructorsSectionParser
DataContract <|-- CircuitContract
DataContract <|-- DriverContract
DataContract <|-- PointsContract
DeclarativeSectionTableParseMixin <|-- BaseConstructorListScraper
DeclarativeSectionTableParseMixin <|-- CircuitsListScraper
DriverOrderedTableParser <|-- DriversListTableParser
DriverOrderedTableParser <|-- FatalitiesTableParser
EnumMarksMixin <|-- FatalityEventColumn
EnumMarksMixin <|-- NameStatusColumn
ExtractListItemsMixin <|-- SeasonMidSeasonChangesSectionParser
ExtractListItemsMixin <|-- SeasonRegulationChangesSectionParser
F1ListScraper <|-- ConstructorsListScraper
F1ListScraper <|-- IndianapolisOnlyListScraper
F1TableScraper <|-- BaseEngineTableScraper
F1TableScraper <|-- BasePointsScraper
F1TableScraper <|-- EngineManufacturersListScraper
F1TableScraper <|-- F1FatalitiesListScraper
F1TableScraper <|-- FemaleDriversListScraper
F1TableScraper <|-- LapRecordsTableScraper
F1TableScraper <|-- RedFlaggedRacesBaseScraper
F1TableScraper <|-- SeedListTableScraper
F1TableScraper <|-- TyreManufacturersScraper
FuncColumn <|-- LocationColumn
HtmlFetcher <|-- _SourceAdapterFetcherShim
HttpShimError <|-- HTTPError
HttpShimError <|-- HTTPTimeoutError
IndianapolisOnlyMixin <|-- IndianapolisOnlyListScraper
InfoboxParser <|-- DriverInfoboxParser
InfoboxParser <|-- F1CircuitInfoboxParser
InfoboxParser <|-- InfoboxHtmlParser
InfoboxTextUtils <|-- CircuitGeoParser
InfoboxTextUtils <|-- CircuitHistoryParser
InfoboxTextUtils <|-- CircuitSpecsParser
InfoboxTextUtils <|-- CircuitTextProcessing
LayerJobRunner <|-- FunctionExportRunner
LayerJobRunner <|-- GrandPrixRunner
LayerZeroRunConfigFactory <|-- DefaultLayerZeroRunConfigFactory
LayerZeroRunConfigFactory <|-- SponsorshipLiveriesRunConfigFactory
LayerZeroRunConfigFactory <|-- StaticScraperKwargsFactory
LayerZeroRunConfigFactoryProtocol <|-- LayerZeroRunConfigFactory
LinkRecord <|-- CarRecord
LinksListColumn <|-- AppendLinksColumn
ListParser <|-- IndianapolisOnlyListParser
ListParser <|-- PrivateerTeamsListParser
ListParser <|-- _IndianapolisConstructorsListParser
MappedWikiTableParser <|-- LapRecordsWikiTableParser
MappedWikiTableParser <|-- RaceResultsTableParser
MappedWikiTableParser <|-- StandingsTableParser
MultiColumn <|-- ConstructorSplitColumn
MultiColumn <|-- LastLengthUsedColumn
MultiColumn <|-- NameStatusColumn
NameStatusColumn <|-- CircuitNameStatusColumn
NameStatusColumn <|-- DriverNameStatusColumn
NameStatusColumn <|-- EngineManufacturerNameStatusColumn
NameStatusColumn <|-- RaceTitleStatusColumn
PipelineError <|-- SourceParseError
PipelineError <|-- TransportError
PipelineError <|-- ValidationError
RateLimiter <|-- MinDelayRateLimiter
RecordAssemblyStrategy <|-- AttachDetailsStrategy
RecordAssemblyStrategy <|-- BundleRecordWithDetailsStrategy
RecordAssemblyStrategy <|-- ExtractDetailFieldStrategy
RecordTransformer <|-- DriversChampionshipsTransformer
RecordTransformer <|-- FailedToMakeRestartTransformer
RecordTransformer <|-- FatalitiesCarTransformer
RecordTransformer <|-- NormalizeLinksTransformer
RecordTransformer <|-- PointsScoringSystemsHistoryTransformer
RecordTransformer <|-- RecordFactoryTransformer
RecordTransformer <|-- ShortenedRacePointsTransformer
RecordValidator <|-- CompositeRecordValidator
RequestError <|-- HttpShimError
RetryPolicy <|-- DefaultRetryPolicy
SafeParserMixin <|-- CircuitEntitiesParser
SafeParserMixin <|-- CircuitLayoutsParser
SchemaCompositeRecordValidator <|-- CircuitsRecordValidator
SchemaCompositeRecordValidator <|-- DriversRecordValidator
SchemaCompositeRecordValidator <|-- GrandsPrixRecordValidator
ScraperError <|-- DomainParseError
ScraperError <|-- PipelineError
ScraperError <|-- ScraperNetworkError
ScraperError <|-- ScraperNotFoundError
ScraperError <|-- ScraperParseError
ScraperError <|-- ScraperValidationError
SectionAdapter <|-- SingleWikiArticleSectionAdapterBase
SectionParser <|-- CircuitsListSectionParser
SectionParser <|-- CurrentRulesSectionParser
SectionParser <|-- DriversListSectionParser
SectionParser <|-- DriversSectionParser
SectionParser <|-- EngineManufacturersSectionParser
SectionParser <|-- FatalitiesSectionParser
SectionParser <|-- HistorySectionParser
SectionParser <|-- ManufacturersSectionParser
SectionParser <|-- PointsScoringSystemsSectionParser
SectionParser <|-- RacesSectionParser
SectionParser <|-- RedFlaggedRacesSectionParser
SectionParser <|-- SeasonsSectionParser
SectionParser <|-- TeamLiveriesSectionParser
SectionSelectionStrategy <|-- WikipediaSectionByIdSelectionStrategy
SectionTableParseMixin <|-- DeclarativeSectionTableParseMixin
SectionTableParserBase <|-- CircuitEventsSectionParser
SectionTableParserBase <|-- CircuitLapRecordsSectionParser
SectionTableParserBase <|-- DriverResultsSectionParser
SeedListTableScraper <|-- BaseConstructorListScraper
SeedListTableScraper <|-- CircuitsListScraper
SeedListTableScraper <|-- F1DriversListScraper
SeedListTableScraper <|-- GrandsPrixListScraper
SeedListTableScraper <|-- SeasonsListScraper
SingleWikiArticleScraperBase <|-- F1SingleGrandPrixScraper
SingleWikiArticleScraperBase <|-- SingleEngineManufacturerScraper
SingleWikiArticleScraperBase <|-- SingleWikiArticleSectionAdapterBase
SingleWikiArticleScraperBase <|-- SingleWikiArticleSectionByIdBase
SingleWikiArticleSectionAdapterBase <|-- F1SingleCircuitScraper
SingleWikiArticleSectionAdapterBase <|-- SingleConstructorScraper
SingleWikiArticleSectionAdapterBase <|-- SingleDriverScraper
SingleWikiArticleSectionAdapterBase <|-- SingleSeasonScraper
SourceAdapter <|-- CacheAdapter
SourceAdapter <|-- HtmlFetcher
SubSectionParser <|-- ByRaceTitleSubSectionParser
SubSectionParser <|-- DetailByDriverSubSectionParser
SubSectionParser <|-- EngineRegulationSubSectionParser
SubSectionParser <|-- EngineSubSectionParser
SubSectionParser <|-- IndianapolisOnlySubSectionParser
SubSectionParser <|-- NonChampionshipsRacesSubSectionParser
SubSectionParser <|-- OfficialDriversSubSectionParser
SubSectionParser <|-- SpecialCasesSubSectionParser
SubSectionParser <|-- TyreManufacturersBySeasonSubSectionParser
SubSubSectionParser <|-- ShortenedRacesSubSubSectionParser
SubSubSectionParser <|-- SpecialCasesSubSubSectionRouter
SubSubSectionParser <|-- SprintRacesSubSubSectionParser
TableParser <|-- F1StandingsScraper
TableParser <|-- SponsorshipTableParser
TableParser <|-- TeamLiveriesTableParser
TextCacheProtocol <|-- FileCache
TextCacheProtocol <|-- WikipediaCachePolicy
ValidatedModel <|-- Circuit
ValidatedModel <|-- EngineManufacturer
ValidatedModel <|-- EngineRegulation
ValidatedModel <|-- EngineRestriction
ValueObject <|-- DateValue
ValueObject <|-- DriversChampionships
ValueObject <|-- Link
ValueObject <|-- NormalizedDate
ValueObject <|-- SeasonRef
WikiElementParserMixin <|-- SubSubSubSectionParser
WikiElementParserMixin <|-- WikiScraper
WikiParser <|-- ContentTextParser
WikiParser <|-- SubSubSubSectionParser
WikiScraper <|-- F1ListScraper
WikiScraper <|-- F1SponsorshipLiveriesScraper
WikiScraper <|-- F1TableScraper
WikiScraper <|-- RedFlaggedRacesScraper
WikiScraper <|-- SingleWikiArticleScraperBase
WikiTableBaseParser <|-- BaseRedFlaggedRacesTableParser
WikiTableBaseParser <|-- CircuitsListTableParser
WikiTableBaseParser <|-- CurrentConstructorsTableParser
WikiTableBaseParser <|-- DriverOrderedTableParser
WikiTableBaseParser <|-- EngineManufacturersTableParser
WikiTableBaseParser <|-- EngineRegulationTableParser
WikiTableBaseParser <|-- EngineRestrictionsTableParser
WikiTableBaseParser <|-- FemaleDriversTableParser
WikiTableBaseParser <|-- FormerConstructorsTableParser
WikiTableBaseParser <|-- GrandsPrixTableParser
WikiTableBaseParser <|-- MappedWikiTableParser
WikiTableBaseParser <|-- PointsScoringSystemsHistoryTableParser
WikiTableBaseParser <|-- SeasonsTableParser
WikiTableBaseParser <|-- ShortenedRacesPointsTableParser
WikiTableBaseParser <|-- SprintPointsTableParser
WikiTableBaseParser <|-- TyreManufacturersBySeasonTableParser

@enduml
